var indikatorensetData = [
	{
		"template": "befragungen001",
		"data-id": 12514,
		"chart-id": 12514,
		"filter": "",
		"parentId": "5821",
		"children": [],
		"title": "Bewertung der Lebensqualität",
		"subtitle": "«Wie würden Sie die Lebensqualität im Kanton Basel-Stadt insgesamt bewerten?», Basel-Stadt",
		"lesehilfe": "Auf einer 10er-Skala konnten die befragten Personen die Lebensqualität im Kanton Basel-Stadt bewerten. 2023 geben die Befragten der Lebensqualität im Stadtkanton im Durchschnitt eine 7,9. Die Lebensqualität wird damit vergleichbar hoch bewertet wie in den Jahren davor.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.<br>Um die Daten über die Jahre zu vergleichen, bleiben die befragten Personen, welche die Frage mit «Weiss nicht» oder gar nicht beantwortet haben, unberücksichtigt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppen gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bewertung der Lebensqualität",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12514",
		"kennzahlenset": "Befragungen",
		"kuerzelKunde": "BB 1-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-29T11:57:49",
		"id": 12514
	},
	{
		"template": "befragungen001",
		"data-id": 12515,
		"chart-id": 12515,
		"filter": "",
		"parentId": "9735",
		"children": [],
		"title": "Beitrag Klimaschutz",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beitrag Klimaschutz",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12515",
		"kennzahlenset": "Befragungen",
		"kuerzelKunde": "BB 1-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-29T12:16:26",
		"id": 12515
	},
	{
		"template": "befragungen001",
		"data-id": 12516,
		"chart-id": 12516,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Aspekten am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den folgenden Aspekten an Ihrem Wohnort?», nur Personen mit Angaben zur Wichtigkeit",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Aspekten am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12516",
		"kennzahlenset": "Befragungen",
		"kuerzelKunde": "BB 1-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-29T06:18:12",
		"id": 12516
	},
	{
		"template": "befragungen001",
		"data-id": 12517,
		"chart-id": 12517,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wichtigkeit mit Aspekten am Wohnort",
		"subtitle": "«Wie wichtig sind Ihnen folgenden Aspekten an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wichtigkeit mit Aspekten am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12517",
		"kennzahlenset": "Befragungen",
		"kuerzelKunde": "BB 1-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-29T06:20:20",
		"id": 12517
	},
	{
		"template": "befragungen001",
		"data-id": 12519,
		"chart-id": 12519,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Kantonale Online-Dienstleistungen",
		"subtitle": "«Welche Dienstleistungen des Kantons nutzen Sie online bzw. kennen Sie?», nur Personen mit Internetzugang, 2023",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonale Online-Dienstleistungen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12519",
		"kennzahlenset": "Befragungen",
		"kuerzelKunde": "BB 1-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-01T10:11:23",
		"id": 12519
	}
];