var indikatorensetData = [
	{
		"template": "map_gemeinden_print",
		"data-id": 8095,
		"chart-id": 8095,
		"filter": "",
		"parentId": "7952",
		"children": [],
		"title": "Perimeter der trinationalen Agglomeration Basel",
		"subtitle": "",
		"lesehilfe": "Die trinationale Agglomeration Basel umfasst 203 Gemeinden. Sie besteht aus der Kernstadt Basel, 106 übrigen Gemeinden in der Schweiz, 24 in Deutschland und 72 in Frankreich.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Perimeter der trinationalen Agglomeration Basel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08095",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "1.1",
		"stufe1": "1. Einführung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:46",
		"id": 8095
	},
	{
		"template": "template001_print",
		"data-id": 8096,
		"chart-id": 8096,
		"filter": "",
		"parentId": "7953",
		"children": [],
		"title": "Gesamtbevölkerung",
		"subtitle": "2019",
		"lesehilfe": "Die trinationale Agglomeration Basel zählt 2019 rund 859 300 Einwohnerinnen und Einwohner und ist damit die drittgrösste Agglomeration der Schweiz, nach Zürich und Genf (grenzüberschreitend). Ein Fünftel der Bevölkerung wohnt in der Kernstadt Basel, 44% in den übrigen schweizerischen Gemeinden, 25% in Deutschland und 11% in Frankreich. Der Anteil der in der Kernstadt wohnenden Bevölkerung ist in Basel (20%) sowie in Genf (22%) deutlich kleiner als in Zürich (30%), Bern (32%) oder Lausanne (33%).",
		"erlaeuterungen": "Hier ist die ständige Wohnbevölkerung dargestellt. Die Agglomerationen sind gemäss Typologie «Raum mit städtischem Charakter 2012» des BFS definiert. Eine Agglomeration besteht aus einer Kernstadt und den übrigen Agglomerationsgemeinden. Die Agglomerationen Basel und Genf sind grenzüberschreitend.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Gesamtbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08096",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.1",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:47",
		"id": 8096
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 8097,
		"chart-id": 8097,
		"filter": "",
		"parentId": "7954",
		"children": [],
		"title": "Bevölkerungsdichte nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2019",
		"lesehilfe": "Mit 7 223 Einwohnern pro Quadratkilometer ist die Stadt Basel die Gemeinde mit der höchsten Bevölkerungsdichte. In den Agglomerationsteilen zeigen folgende Gemeinden die höchste Bevölkerungsdichte: Birsfelden (4 105) in der Schweiz; Huningue (2 358) in Frankreich; Weil am Rhein (1 550) in Deutschland.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bevölkerungsdichte nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08097",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.3",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:47",
		"id": 8097
	},
	{
		"template": "template001_print",
		"data-id": 8098,
		"chart-id": 8098,
		"filter": "",
		"parentId": "7955",
		"children": [],
		"title": "Jugendquotient",
		"subtitle": "2019",
		"lesehilfe": "Die Anzahl Jugendlicher unter 20 Jahren pro 100 Personen im Alter von 20 bis 64 Jahren ist in den Kernstädten tiefer als in den jeweiligen übrigen Agglomerationsgemeinden. Der Jugendquotient ist vor allem im französischen Teil der Agglomerationen Basel (39,0) und Genf (43,4) hoch. In der gesamten Agglomeration Basel ist der Jugendquotient (32,0) tiefer als in der Agglomerationen Genf und Lausanne.",
		"erlaeuterungen": "Der Jugendquotient ergibt sich aus der Anzahl unter 20-Jähriger pro 100 20- bis 64-Jähriger (Personen im erwerbsfähigen Alter).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08098",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.4",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:48",
		"id": 8098
	},
	{
		"template": "template001_print",
		"data-id": 8100,
		"chart-id": 8100,
		"filter": "",
		"parentId": "7957",
		"children": [],
		"title": "Altersquotient",
		"subtitle": "2019",
		"lesehilfe": "Die Bevölkerung der Agglomeration Basel ist vergleichsweise alt: Der Altersquotient ist mit 33,9 im Jahr 2019 deutlich höher als in den Agglomerationen Genf, Lausanne und Zürich. Dies ist auf die relativ ältere Bevölkerung in der Kernstadt Basel (Altersquotient von 29,8) sowie im Schweizer und im deutschen Gürtel der Agglomeration (37,0 bzw. 33,8) zurückzuführen. Nach Basel weist die Agglomeration Bern den höchsten Altersquotienten auf (33,2).",
		"erlaeuterungen": "Der Altersquotient ergibt sich aus der Anzahl über 64-Jähriger pro 100 20- bis 64-Jähriger (Personen im erwerbsfähigen Alter).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08100",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.5",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:49",
		"id": 8100
	},
	{
		"template": "template001_print",
		"data-id": 8101,
		"chart-id": 8101,
		"filter": "",
		"parentId": "7958",
		"children": [],
		"title": "Ausländeranteil",
		"subtitle": "2019",
		"lesehilfe": "Den grössten Ausländeranteil weist die Kernstadt Genf (47,9%) auf. Ausländeranteile von gerade 15% werden hingegen in den Agglomerationsgemeinden (ohne Kernstadt) in Bern sowie in den deutschen und französischen Gemeinden der Agglomeration Basel registriert. Als gesamte Agglomeration betrachtet haben nur Lausanne und Genf einen Ausländeranteil von über 30%, in Basel liegt der Anteil bei 23,2%.",
		"erlaeuterungen": "Anteil der ständigen ausländischen Wohnbevölkerung an der gesamten ständigen Wohnbevölkerung in %.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08101",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.6",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:49",
		"id": 8101
	},
	{
		"template": "template001_print",
		"data-id": 8102,
		"chart-id": 8102,
		"filter": "",
		"parentId": "7959",
		"children": [],
		"title": "Geburten und Sterbefälle",
		"subtitle": "Saldo (pro 1000 Einwohner), 2019",
		"lesehilfe": "Der Saldo der Geburten und Sterbefälle pro 1000 Einwohner liegt 2018 in Basel bei 0,2, während dieser in Genf, Lausanne und auch in Zürich deutlich höher ist. Für den tiefen Wert in der Agglomeration Basel sind insbesondere die Gemeinden in der Schweiz (ohne Kernstadt, Saldo 0) und in Deutschland (-0,3) verantwortlich. Der Saldo ist in den Kernstädten jeweils grösser als in den übrigen Schweizer Gemeinden. Mit Abstand am grössten ist er im französischen Teil der Agglomeration Genf (7,6).",
		"erlaeuterungen": "Rohe Geburtenziffer pro 1000 Einwohner minus rohe Sterbeziffer pro 1000 Einwohner.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Geburten und Sterbefälle",
		"thema": "01 Bevölkerung",
		"unterthema": "Geburten und Todesfälle",
		"kuerzel": "I.01.3.08102",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.7",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:50",
		"id": 8102
	},
	{
		"template": "template001_print",
		"data-id": 8104,
		"chart-id": 8104,
		"filter": "",
		"parentId": "7961",
		"children": [],
		"title": "Anteil der Privathaushalte mit minderjährigen Kindern",
		"subtitle": "2019",
		"lesehilfe": "Der Anteil der Privathaushalte mit Kindern unter 18 Jahren beträgt in der Agglomeration Basel 25,2%. Über alle Agglomerationen verglichen ist der Anteil in den deutschen Gemeinden (34,3%) am höchsten. In jeder Agglomeration ist der Anteil der Privathaushalte mit minderjährigen Kindern in der Kernstadt kleiner als in den jeweiligen übrigen Agglomerationsgemeinden.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Anteil der Privathaushalte mit minderjährigen Kindern",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.08104",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.1",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:51",
		"id": 8104
	},
	{
		"template": "template001_print",
		"data-id": 8105,
		"chart-id": 8105,
		"filter": "",
		"parentId": "7962",
		"children": [],
		"title": "Anteil der privaten Einelternhaushalte",
		"subtitle": "mit Kindern unter 18 Jahren, 2019",
		"lesehilfe": "Der Anteil der Einelternhaushalte mit Kindern am Total der privaten Haushalte variiert zwischen 2,5% in der Agglomeration Bern und 4,9% in Genf. In den französischen Gemeinden der Agglomeration Genf liegt er bei 6,2%. In der Agglomeration Basel haben 3,4% der Haushalte alleinerziehende Eltern, wobei der Anteil in den französischen und in den deutschen Agglomerationsgemeinden grösser als im Schweizer Teil der Agglomeration ist.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Anteil der privaten Einelternhaushalte",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.08105",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.2",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:51",
		"id": 8105
	},
	{
		"template": "befragungen001_print",
		"data-id": 8106,
		"chart-id": 8106,
		"filter": "",
		"parentId": "7963",
		"children": [],
		"title": "Bildungsniveau der Bevölkerung",
		"subtitle": "nach höchster abgeschlossener Ausbildung, 2019",
		"lesehilfe": "Die Bevölkerung zwischen 25 und 64 Jahren weist in der Agglomeration Basel 2019 den grössten Anteil an Sekundarstufe II als höchste abgeschlossene Ausbildung (46,8%) auf. Am höchsten ist der Anteil der Sekundarstufe II in den Agglomerationsgemeinden in Deutschland (53,9%). Der Anteil der Bevölkerung mit tertiärer Ausbildung ist in der Agglomeration Basel (38,3%) tiefer als in den Vergleichsagglomerationen.",
		"erlaeuterungen": "Bevölkerung (25- bis 64-jährig) ohne nachobligatorische Ausbildung (ISCED Stufen 1 oder 2), mit Sekundarstufe II (ISCED Stufen 3 oder 4) oder mit tertiärer Ausbildung (ISCED Stufen 5 bis 8) als höchstem Bildungsabschluss.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Bildungsniveau der Bevölkerung",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.08106",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.4",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "large",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:52",
		"id": 8106
	},
	{
		"template": "template001_print",
		"data-id": 8108,
		"chart-id": 8108,
		"filter": "",
		"parentId": "7965",
		"children": [],
		"title": "Nettoerwerbsquote der 15- bis 64-Jährigen",
		"subtitle": "2019",
		"lesehilfe": "Die Nettoerwerbsquote in der Agglomeration Basel liegt 2019 bei rund 78%. Am höchsten ist die Erwerbsquote in den Kernstädten Bern (84%) und Zürich (83%). Es gibt allgemein nur kleine Unterschiede zwischen Kernstadt und Rest der Agglomeration, ausser in Genf, wo die Erwerbsquote im französischen Teil der Agglomeration höher als in der Kernstadt ist.",
		"erlaeuterungen": "Die Nettoerwerbsquote enspricht der Anzahl Erwerbspersonen geteilt durch die 15- bis 64-jährige Bevölkerung, in %. Die Erwerbspersonen sind die Summe der Erwerbstätigen und der Erwerbslosen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Nettoerwerbsquote der 15- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08108",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.1",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:53",
		"id": 8108
	},
	{
		"template": "template001_print",
		"data-id": 8109,
		"chart-id": 8109,
		"filter": "",
		"parentId": "7966",
		"children": [],
		"title": "Erwerbstätige im Alter von 20 bis 64 Jahren",
		"subtitle": "2019",
		"lesehilfe": "Rund 395 000 Einwohner der Agglomeration Basel von 20 bis 64 Jahren sind erwerbstätig, ähnlich viele wie in der Agglomeration Genf. Davon wohnen 35,9% im ausländischen Teil der Agglomeration Basel (in Genf wohnen 38,6% im ausländischen Teil). Lediglich rund ein Fünftel der Erwerbstätigen der Agglomerationen Basel und Genf wohnen in der Kernstadt, während dieser Anteil in den Agglomerationen Bern, Lausanne und Zürich zwischen 32% und 34% liegt.",
		"erlaeuterungen": "Als Erwerbstätige werden Personen definiert, die eine entlohnte Berufstätigkeit ausüben (selbständig oder angestellt). Sie werden am Wohnort (nicht am Arbeitsort) erfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Erwerbstätige im Alter von 20 bis 64 Jahren",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08109",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.2",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:54",
		"id": 8109
	},
	{
		"template": "template001_print",
		"data-id": 8110,
		"chart-id": 8110,
		"filter": "",
		"parentId": "7967",
		"children": [],
		"title": "Erwerbstätigenquote der 20- bis 64-Jährigen",
		"subtitle": "2019",
		"lesehilfe": "Von den Einwohnern von 20 bis 64 Jahren sind in der Agglomeration Basel 78% erwerbstätig. Im Schweizer Agglomerationsgürtel und in den deutschen Gemeinden ist die Quote höher als in der Kernstadt und in den französischen Gemeinden. Die Erwerbstätigenquote in der Agglomeration Basel ist höher als in Genf und Lausanne, aber tiefer als in Bern und Zürich.",
		"erlaeuterungen": "Anteil der Erwerbstätigen an der ständigen Wohnbevölkerung von 20 bis 64 Jahren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Erwerbstätigenquote der 20- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08110",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.3",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:54",
		"id": 8110
	},
	{
		"template": "befragungen001_print",
		"data-id": 8111,
		"chart-id": 8111,
		"filter": "",
		"parentId": "7968",
		"children": [],
		"title": "Beschäftigte nach Wirtschaftssektor",
		"subtitle": "2019",
		"lesehilfe": "Der Anteil des sekundären Sektors am Total der Beschäftigten ist in der Agglomeration Basel mit 25,2% deutlich höher als in den Vergleichsagglomerationen. Am wichtigsten ist der sekundäre Sektor im deutschen Teil der Agglomeration Basel (36,6%), aber auch in der Kernstadt ist dieser Sektor überdurchschnittlich vertreten (18,9%), was für eine Stadt aussergewöhnlich ist. Der hohe Anteil des sekundären Sektors in Basel ist auf die wichtige Rolle der pharmazeutischen Industrie zurückzuführen.",
		"erlaeuterungen": "Der 1. Sektor beinhaltet die Land- und Forstwirtschaft. Der 2. Sektor ist das Aggregat von verarbeitendem Gewerbe, Energie- und Wasserversorgung und Baugewerbe. Der 3. Sektor ist die Zusammenfassung von allen Dienstleistungen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigte nach Wirtschaftssektor",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08111",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.5",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:56",
		"id": 8111
	},
	{
		"template": "template001_print",
		"data-id": 8112,
		"chart-id": 8112,
		"filter": "",
		"parentId": "7969",
		"children": [],
		"title": "Beschäftigtendichte",
		"subtitle": "Beschäftigte pro Einwohner, 2019",
		"lesehilfe": "Die Beschäftigtendichte, oder auch Arbeitsstellendichte, ist in den Kernstädten am höchsten: Die Städte Bern (1,4), Zürich (1,2) und Basel (1,1) weisen mehr als eine Arbeitsstelle pro Einwohner oder Einwohnerin auf. In den Städten Genf und Lausanne ist der Wert leicht tiefer (0,9). In den französischen bzw. deutschen Teilen der Agglomerationen Genf und Basel ist die Beschäftigtendichte am tiefsten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigtendichte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08112",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.6",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:57",
		"id": 8112
	},
	{
		"template": "template001_print",
		"data-id": 8113,
		"chart-id": 8113,
		"filter": "",
		"parentId": "7970",
		"children": [],
		"title": "Personenwagen",
		"subtitle": "pro 1000 Einwohner, 2019",
		"lesehilfe": "2019 sind in der Agglomeration Basel 513 Personenwagen pro 1000 Einwohner registriert. Nur in Genf ist der Wert höher. Es sind deutliche Unterscheide zwischen den Agglomerationsteilen zu beobachten: Die Stadt Basel (328) weist den tiefsten Wert aller Kernstädte aus. Deutlich höher ist er in den deutschen (589) und in den französischen (651) Gemeinden der Agglomeration Basel. Auch in der Agglomeration Genf ist der Motorisierungsgrad im französischen Teil höher als in den Schweizer Gemeinden.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Personenwagen",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.08113",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.1",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_017",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:57",
		"id": 8113
	},
	{
		"template": "template001_print",
		"data-id": 8114,
		"chart-id": 8114,
		"filter": "",
		"parentId": "7971",
		"children": [],
		"title": "Hotelübernachtungen",
		"subtitle": "pro Einwohner, 2019",
		"lesehilfe": "Die Kernstädte weisen die höchste Übernachtungskonzentration in Hotelbetrieben auf. Am meisten Hotelübernachtungen pro Einwohner werden 2019 in der Stadt Genf (10,8) registriert, gefolgt von den Städten Zürich (8,7) und Basel (8,2). In der Agglomeration Basel zeigen auch die deutschen Gemeinden eine relativ hohe touristische Attraktivität (4,1 Hotelübernachtungen pro Einwohner).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Hotelübernachtungen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.08114",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.2",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_018",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:58",
		"id": 8114
	},
	{
		"template": "template001_print",
		"data-id": 8115,
		"chart-id": 8115,
		"filter": "",
		"parentId": "7993",
		"children": [],
		"title": "Beschäftigte",
		"subtitle": "2019",
		"lesehilfe": "In der trinationalen Agglomeration Basel sind im Jahr 2019 insgesamt 471 200 Beschäftigte tätig. Rund 78% davon arbeiten in der Schweiz (je zur Hälfte in der Kernstadt und in den übrigen Gemeinden), 16% im deutschen Teil der Agglomeration und 6% im französischen Teil. Die Beschäftigtenzahl in der Agglomeration Basel ist geringfügig tiefer als in Genf.",
		"erlaeuterungen": "Der Begriff Beschäftigte bezeichnet die Anzahl der besetzten Stellen. Diese wird am Arbeitsort erfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08115",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.4",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-27T07:48:55",
		"id": 8115
	},
	{
		"template": "template001_print",
		"data-id": 9481,
		"chart-id": 9481,
		"filter": "",
		"parentId": "9406",
		"children": [],
		"title": "Entwicklung der Gesamtbevölkerung",
		"subtitle": "durchschnittliche jährliche Veränderungsrate, 2014 bis 2019",
		"lesehilfe": "Zwischen 2014 und 2019 ist die Gesamtbevölkerung der Agglomeration Basel (+0,7% pro Jahr) weniger gewachsen als die Bevölkerung in den Vergleichsagglomerationen. Bescheiden war das Bevölkerungswachstum in der Kernstadt sowie in den übrigen Gemeinden in der Schweiz und in Deutschland. Der höchste Bevölkerungszuwachs ist im französischen Teil der Agglomeration Genf zu beobachten (+2,0%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung der Gesamtbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09406",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-17T08:11:07",
		"id": 9481
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9482,
		"chart-id": 9482,
		"filter": "",
		"parentId": "9407",
		"children": [],
		"title": "Jugendquotient nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2019",
		"lesehilfe": "Die Anzahl Jugendlicher pro 100 Personen zwischen 20 und 64 Jahren variiert in den Gemeinden der grenzüberschreitenden Agglomeration Basel zwischen 21 in Augst (Schweiz) und 51 in Folgensbourg (Frankreich). Die Quotienten sind in den meisten Gemeinden in Frankreich höher als in der Schweiz und in Deutschland. Der höchste Jugendquotient in der Schweiz weist Zullwil auf (45), in Deutschland Binzen (40). In der Kernstadt Basel leben 26 Jugendlichen pro 100 20- bis 64-Jähriger.",
		"erlaeuterungen": "Der Jugendquotient ergibt sich aus der Anzahl unter 20-Jähriger pro 100 20- bis 64-Jähriger (Personen im erwerbsfähigen Alter).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jugendquotient nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09407",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.8",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_000",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-17T08:11:07",
		"id": 9482
	},
	{
		"template": "template001_print",
		"data-id": 9483,
		"chart-id": 9483,
		"filter": "",
		"parentId": "9409",
		"children": [],
		"title": "Entwicklung der Beschäftigtenzahl",
		"subtitle": "durchschnittliche jährliche Veränderungsrate, 2014 bis 2019",
		"lesehilfe": "Zwischen 2014 und 2019 war das Wachstum der Beschäftigtenzahl in der Agglomeration Basel (+0,7% im Jahresdurchschnitt) geringer als in den Vergleichsagglomerationen. Innerhalb der Agglomeration Basel gab es grosse Unterschiede: Am höchsten war das Wachstum im deutschen Teil (+1,7% pro Jahr), am tiefsten in der Kernstadt (+0,2%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung der Beschäftigtenzahl",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09409",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.7",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-17T08:11:07",
		"id": 9483
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9484,
		"chart-id": 9484,
		"filter": "",
		"parentId": "9410",
		"children": [],
		"title": "Anteil der Einpersonenhaushalte nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2019",
		"lesehilfe": "Der Anteil der Haushalte mit nur einer Person ist in der Kernstadt Basel mit 48% bei weitem der höchste in der trinationalen Agglomeration. Anteile von über oder gerade 40% verzeichnen ausser Basel nur noch Birsfelden in der Schweiz, Lörrach in Deutschland sowie Saint-Louis, Huningue und Ferrette in Frankreich.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil der Einpersonenhaushalte nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.09484",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.3",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_000",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-11-24T02:56:48",
		"id": 9484
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9485,
		"chart-id": 9485,
		"filter": "",
		"parentId": "9411",
		"children": [],
		"title": "Personenwagen nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, pro 1000 Einwohner, 2019",
		"lesehilfe": "Die Stadt Basel weist mit 328 Personenwagen pro 1000 Einwohner mit Abstand den tiefsten Motorisierungsgrad in der Agglomeration. Es folgen die Nachbargemeinden Riehen und Birsfelden, mit je 400 Autos pro 1000 Einwohner. In der gesamten Agglomeration gibt es viele Gemeinden mit mehr als 700 Autos pro 1000 Einwohner, wobei die grosse Mehrheit davon in Frankreich sind. Den Rekordwert erreicht die französische Gemeinde Bettlach (802).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Personenwagen nach Gemeinde",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09411",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.3",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_000",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-17T08:11:07",
		"id": 9485
	}
];