var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9000,
		"chart-id": 9000,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttoenergieverbrauch nach Energieträger",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Bruttoenergieverbrauch im Kanton Basel-Stadt ging von 5 762 GWh im Jahr 2010 um gut 22% zurück auf 4 473 GWh im Jahr 2020. Neben dem Rückgang beim Heizöl von 54% ist in diesem Zeitraum auch der Erdgasverbrauch um rund 34% und der ausserkantonale Bezug von Elektrizität um rund 28% zurückgegangen. Gestiegen ist der Bruttoenergieverbrauch der erneuerbaren Energien, und zwar um 48% zwischen 2010 und 2020.",
		"erlaeuterungen": "Der Bruttoenergieverbrauch zeigt die Energie in der Form, in welcher sie in den Kanton importiert (ohne Flugtreibstoffe) oder im Kanton aus natürlichen Quellen gewonnen wird. Die im Kanton gewonnenen Erneuerbaren sind in einer Kategorie zusammengefasst und umfasst auch den erneuerbaren Teil des Abfalls (50% des Kehrichts und Klärschlamm). Der nicht erneuerbare Anteil des Abfalls (50% des Kehrichts und Industrieabfall) ist separat aufgelistet.<br><br>Der Treibstoffverbrauch wurde aufgrund des aktualisierten Gesamtverkehrsmodell Basel-Stadt berechnet, was einen Teil der Veränderung erklärt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'http://www.statistik.bs.ch/zahlen/tabellen/8-energie.html' target = '_blank'>Energiestatistik Kanton Basel-Stadt</a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-06-0602' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoenergieverbrauch nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09000",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-09-21T08:09:41",
		"id": 9000
	},
	{
		"template": "template001",
		"data-id": 9006,
		"chart-id": 9006,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Elektrizitätsverbrauch nach Produktionsart",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Elektrizitätsverbrauch ging zwischen 2010 und 2020 um 15% von 1 628 GWh auf 1 378 GWh zurück. Während der ausserkantonale Bezug (-28%) und die Produktion aus Erdgas (-44%) in diesem Zeitraum zurückgegangen sind, haben Wasserkraft (35%), die thermische Erzeugung (7%) und Photovoltaik (668%, auf tiefem Niveau) zum Teil stark zugenommen. Der ausserkantonale Bezug macht 2020 immer noch rund zwei Drittel des Elektrizitätsverbrauch aus. Der Anteil Elektrizität am Endenergieverbrauch stieg zwischen 2010 und 2020 von 29% auf 33%.",
		"erlaeuterungen": "Unter den ausserkantonalen Bezug von Elektrizität fällt der Import von Mengen aus Schweizer Wasserkraftwerken, Wind- und Sonnenenergie sowie Biomasse.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'http://www.statistik.bs.ch/zahlen/tabellen/8-energie.html' target = '_blank'>Energiestatistik Kanton Basel-Stadt</a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-06-0613' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Elektrizitätsverbrauch nach Produktionsart",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09006",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-09-21T08:09:48",
		"id": 9006
	},
	{
		"template": "template001",
		"data-id": 9008,
		"chart-id": 9008,
		"filter": "",
		"parentId": null,
		"children": [
			5794,
			6160,
			6312,
			8915
		],
		"title": "Endenergieverbrauch nach Verbrauchergruppe",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch hat zwischen 2010 und 2020 um 22,9% abgenommen. Der Rückgang verteilt sich hauptsächlich auf die Verbrauchergruppen «Wohnen» und «Nichtwohnen (ohne Verkehr)».",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Primärenergie, welcher von den Energienutzern verbraucht wird. Bei den Energienutzern wird zwischen «Verkehr», «Wohnen» und «Nichtwohnen (ohne Verkehr)» unterschieden, wobei zum Wohnen die privaten Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen und Industrie gehören.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'https://www.statistik.bs.ch/analysen-berichte/raum-umwelt/energiestatistik.html' target = '_blank'>Energiestatistik Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09008",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "3.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:07",
		"id": 9008
	},
	{
		"template": "template001",
		"data-id": 9614,
		"chart-id": 9614,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttoenergieverbrauch Erneuerbare",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Verbrauch erneuerbarer Energie hat zwischen 2010 und 2020 von 741 GWh auf 1088 GWh zugenommen, was einem Plus von 46% entspricht. Eine starke Zunahme ist beim Holz mit 120% zu verzeichnen. Um 34% angestiegen ist der Verbrauch aus Wasserkraft. Um 3% hat der Verbrauch von erneuerbaren Kehricht und Klärschlamm zugenommen. Starke Zunahmen, allerdings auf sehr tiefem Niveau, sind bei der Fotovoltaik (+668%) der  Umweltwärme (+274%) und der thermischen Solarenergie (+191%) zu beobachten.",
		"erlaeuterungen": "Der Bruttoenergieverbrauch zeigt die Energie in der Form, in welcher sie in den Kanton importiert (ohne Flugtreibstoffe) oder im Kanton aus natürlichen Quellen gewonnen wird. In diesem Indikator wird der Bruttoenergieverbrauch der Erneuerbaren gezeigt, die im Kanton gewonnen wurden, also ohne allfälligen Import von Erbeuerbaren in den Kanton (z.B. ausserkantonaler Bezug von Elektrizität).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoenergieverbrauch Erneuerbare",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09614",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T09:52:50",
		"id": 9614
	},
	{
		"template": "template001",
		"data-id": 9615,
		"chart-id": 9615,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch nach Energieträger",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch ist zwischen 2010 und 2020 von 5 572 GWh rund 26% auf 4 127 GWh zurückgegangen. Die Menge des verbrauchten Heizöls ist seit 2010 um 61% zurückgegangen, die Menge des Erdgases um 45%. Auch die beim Endverbraucher verwendete Elektrizität sank um 15%. Der Verbrauch von Fern- und Nahwärme ist ungefähr konstant geblieben. Der Verbrauch der Treibstoffe reduzierte sich um 34%.",
		"erlaeuterungen": "Im Gegensatz zum Bruttoenergieverbrauch bildet der Endenergieverbrauch die Energie in der Form ab, wie sie beim Endverbraucher eingesetzt wird. Die Differenz zwischen den beiden Grössen entspricht den Zu- respektive Abgängen infolge der Umwandlung in Elektrizität und Fernwärme innerhalb des Kantons.<br><br>In der Kategorie Sonstiges sind die Endverbräuche von Abfall, Holz, Biogas, Solarenergie und Umweltwärme zusammengefasst.<br><br>Der Treibstoffverbrauch wurde aufgrund des aktualisierten Gesamtverkehrsmodell Basel-Stadt berechnet, was einen Teil der Veränderung erklärt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09615",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T10:01:09",
		"id": 9615
	},
	{
		"template": "template001",
		"data-id": 9617,
		"chart-id": 9617,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch von fossilen Energieträgern",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch fossiler Energieträger hat von 2010 bis 2020 um 46% von 2 580 GWh auf 1 431 GWh abgenommen. Erdgas macht davon mit 695 GWh 2020 rund die Hälfte aus, Heizöl mit 198 GWh nur noch rund 14%. Der Anteil aller fossiler Energieträger am Endenergieverbrauch ging damit zwischen 2010 und 2020 von 46% auf 35% zurück.",
		"erlaeuterungen": "Als fossile Energieträger werden Heizöl, Erdgas sowie die Treibstoffe Benzin und Diesel gezählt. Weil in den für  Menschen relevanten Zeiträumen keine neuen fossilen Energien mehr entstehen können, werden sie als nicht erneuerbare Energien bezeichnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch von fossilen Energieträgern",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09617",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T10:26:36",
		"id": 9617
	},
	{
		"template": "template001",
		"data-id": 9618,
		"chart-id": 9618,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fernwärmeverbrauch nach Produktionsart",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "<bitte Lesehilfe erfassen>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fernwärmeverbrauch nach Produktionsart",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09618",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9618
	},
	{
		"template": "template001",
		"data-id": 9619,
		"chart-id": 9619,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch nach Energieträger und Verbrauchergruppe",
		"subtitle": "in GWh, 2022, Basel-Stadt",
		"lesehilfe": "Nicht-Wohnen mit insgesamt 1 966 GWh stellte 2020 die grösste Verbrauchergruppe dar, gefolgt von Wohnen mit total 1 438 GWh und dem Verkehr mit 597 GWh. Fernwärme, Elektrizität und Erdgas stellen für die Verbraucher Wohnen und Nicht-Wohnen die Energieträger mit den grössten Anteilen dar. Beim Verkehr sind es nach wie vor Benzin und Diesel.",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Primärenergie, welcher von den Energienutzern verbraucht wird. Bei den Energienutzern wird zwischen «Verkehr», «Wohnen» und «Nichtwohnen (ohne Verkehr)» unterschieden, wobei zum Wohnen die privaten Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen und Industrie gehören.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Energieträger und Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09619",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "3.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9619
	},
	{
		"template": "template001",
		"data-id": 9620,
		"chart-id": 9620,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "CO<sub>2 </sub> Emissionen nach Energieträger",
		"subtitle": "in Tonnen, Basel-Stadt",
		"lesehilfe": "Die Menge CO2 pro Einwohner hat zwischen 2010 und 2020 von 4.7 Tonnen auf 3.1 Tonnen und Jahr abgenommen. Der Rückgang geht auf Heizöl (-54%), Treibstoffe (-34%), Erdgas (-23%) sowie den nicht erbeuerbaren Teil von Kehricht und Industrieabfall (-2%) zurück. 2022 sind die Emissionen aus Erdgas mit 41% für den grössten Teil aller CO2-Emission verantwortlich.",
		"erlaeuterungen": "Es sind zur Hauptsache CO2-Emissionen berücksichtigt, welche bei der Verbrennung von fossilen Energieträgern (Brenn- und Treibstoffe) innerhalb des Kantons entstehen (Territorialprinzip). Die Emissionen aus der energetischen Nutzung von Holz werden nicht ausgewiesen, da Holz als CO2-neutral gilt. Die Verbrennung von biogenem Material wird ebenso als CO2-neutral betrachtet, weshalb nur 50% des in der Kehrichtverwertungsanlage verbrannten Abfalls berücksichtigt wird. Auch der Klärschlamm wird als biogen taxiert; demzufolge bleiben die entsprechenden CO2-Emissionen ebenfalls unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2 </sub> Emissionen nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09620",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "4.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9620
	},
	{
		"template": "template001",
		"data-id": 9621,
		"chart-id": 9621,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "CO<sub>2 </sub> Emissionen nach Verbrauchergruppe",
		"subtitle": "in Tonnen, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2 </sub> Emissionen nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09621",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "4.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:35:00",
		"id": 9621
	},
	{
		"template": "stock001",
		"data-id": 9622,
		"chart-id": 9622,
		"filter": "",
		"parentId": null,
		"children": [
			9653
		],
		"title": "Jahresmitteltemperatur und Heizgradtage",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "«Das 30-jähriges gleitendes Mittel der Lufttemperatur der Heizperiode Zeigt seit dem Anfang des 20. Jahrhunderts eine stetige Zunahme, bzw. eine Erwärmung der Heizperiode.»",
		"erlaeuterungen": "Als Heizperiode wird der Zeitraum bezeichnet, in dem die Heizanlage in Betrieb genommen werden muss, um die Innentemperatur zu halten. Dies Betrift die Periode vom September bis Juni.<br><br> Der Wert des 30-jährigen gleitenden Mittels eines Jahres ist der Mittelwert der Jahresmittelwerte über einen Zeitraum von -14 bis +15 Jahren und zeigt die längerfristige, geglättete Entwicklung.<br> <br> Für alle Tage in der Heizperiode (September des Vorjahres bis Juni des laufenden Jahres) welche eine mittlere Aussenlufttemperatur von kleiner oder gleich 12 °C (Heizgrenze) aufweisen, wird die Differenz zwischen 20 °C (angenommene gewünschte Raumtemperatur) und der mittleren Aussenlufttemperatur summiert (Beispiel: Beträgt die mittlere Aussenlufttemperatur an einem Tag 8,5 °C, so resultiert daraus für diesen Tag ein Wert von 20 - 8,5 = 11,5 Heizgradtagen). Allfällige Heizgradtage in den Monaten Juli und August werden nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jahresmitteltemperatur und Heizgradtage",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09622",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "5.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:35:00",
		"id": 9622
	},
	{
		"template": "line001",
		"data-id": 9623,
		"chart-id": 9623,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Energieproduktivität und Pro-Kopf-Verbrauch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 1995 ist der kWh-Einsatz pro erwirtschaftetem Franken des Bruttoinlandprodukts (BIP) kontinuierlich gesunken. 2020 betrug er noch 0,102 kWh pro Franken und damit um 63% tiefer als 1995. Der Energieeinsatz pro Kopf sinkt insbesondere seit 2010 und liegt 2020 21 091 kWh pro Person, rund 21% tiefer als 1995.",
		"erlaeuterungen": "Die Energieproduktivität weist die eingesetzte Energie bezogen auf den Endenergieverbrauch pro erzeugter Geldmenge wirtschaftlicher Leistung (Bruttoinlandprodukt, BIP) aus, der Pro-Kopf-Verbrauch die eingesetzte Energie pro Kopf.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Energieproduktivität und Pro-Kopf-Verbrauch",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09623",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:38:46",
		"id": 9623
	},
	{
		"template": "line001",
		"data-id": 9624,
		"chart-id": 9624,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veränderung der Energiebezugsfläche",
		"subtitle": "in Quadratmeter, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veränderung der Energiebezugsfläche",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09624",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "5.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:38:46",
		"id": 9624
	}
];