var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9000,
		"chart-id": 9000,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttoenergieverbrauch nach Energieträger",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Bruttoenergieverbrauch im Kanton Basel-Stadt ging von 6 490 GWh im Jahr 1995 um gut 28,4% zurück auf 4 645 GWh im Jahr 2018. Neben dem Rückgang beim Heizöl von über 83% ist auch der Erdgasverbrauch in diesem Zeitraum um über 31% zurückgegangen.",
		"erlaeuterungen": "Der Bruttoenergieverbrauch zeigt die Energie in der Form, in welcher sie in den Kanton importiert oder im Kanton aus natürlichen Quellen gewonnen wird (ohne Flugtreibstoffe). Im Gegensatz dazu bildet der Endenergieverbrauch die Energie in der Form ab, wie sie beim Endverbraucher eingesetzt wird. <br><br>Die Differenz zwischen den beiden Grössen entspricht den Zu- respektive Abgängen infolge der Umwandlung in Elektrizität und Fernwärme. Der Bruttoenergieverbrauch wird für die leitungsgebundenen Energieträger erhoben und für die nicht leitungsgebundenen Energieträger geschätzt. Für detaillierte Angaben zur Methodik siehe weiterführende Informationen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'http://www.statistik.bs.ch/zahlen/tabellen/8-energie.html' target = '_blank'>Energiestatistik Kanton Basel-Stadt</a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-06-0602' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoenergieverbrauch nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09000",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-09-21T08:09:41",
		"id": 9000
	},
	{
		"template": "template001",
		"data-id": 9006,
		"chart-id": 9006,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Elektrizitätsverbrauch nach Produktionsart",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der totale Elektrizitätsverbrauch hat zwischen 1995 und 2010 von 1 470 auf 1 628 Gigawattstunden zugenommen und sank danach bis 2018 kontinuierlich auf 1 344 Gigawattstunden.",
		"erlaeuterungen": "Jährlicher Elektrizitätsverbrauch nach Produktionsart.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'http://www.statistik.bs.ch/zahlen/tabellen/8-energie.html' target = '_blank'>Energiestatistik Kanton Basel-Stadt</a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-06-0613' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Elektrizitätsverbrauch nach Produktionsart",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09006",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-09-21T08:09:48",
		"id": 9006
	},
	{
		"template": "template001",
		"data-id": 9008,
		"chart-id": 9008,
		"filter": "",
		"parentId": null,
		"children": [
			5794,
			6160,
			6312,
			8915
		],
		"title": "Endenergieverbrauch nach Verbrauchergruppe",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch hat zwischen 2010 und 2018 um 22,9% auf 4 273 GWh abgenommen. Der Rückgang verteilt sich hauptsächlich auf die Verbrauchergruppen «Wohnen» und «Nichtwohnen (ohne Verkehr)».",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Primärenergie, welcher von den Energienutzern verbraucht wird. Bei den Energienutzern wird zwischen «Verkehr», «Wohnen» und «Nichtwohnen (ohne Verkehr)» unterschieden, wobei zum Wohnen die privaten Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen und Industrie gehören.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'https://www.statistik.bs.ch/analysen-berichte/raum-umwelt/energiestatistik.html' target = '_blank'>Energiestatistik Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09008",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "3.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:07",
		"id": 9008
	},
	{
		"template": "template001",
		"data-id": 9614,
		"chart-id": 9614,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttoenergieverbrauch Erneuerbare",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "<bitte Lesehilfe erfassen>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoenergieverbrauch Erneuerbare",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09614",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T09:52:50",
		"id": 9614
	},
	{
		"template": "template001",
		"data-id": 9615,
		"chart-id": 9615,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch nach Energieträger",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "<bitte Lesehilfe erfassen>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09615",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "1.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T10:01:09",
		"id": 9615
	},
	{
		"template": "template001",
		"data-id": 9617,
		"chart-id": 9617,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch von fossilen Energieträgern",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch von fossilen Energieträgern",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09617",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T10:26:36",
		"id": 9617
	},
	{
		"template": "template001",
		"data-id": 9618,
		"chart-id": 9618,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch Fernwärme nach Produktionsart",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "<bitte Lesehilfe erfassen>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch Fernwärme nach Produktionsart",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09618",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "2.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9618
	},
	{
		"template": "template001",
		"data-id": 9619,
		"chart-id": 9619,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Endenergieverbrauch nach Energieträger und Verbrauchergruppe",
		"subtitle": "in GWh, 2022, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Energieträger und Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09619",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "3.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9619
	},
	{
		"template": "template001",
		"data-id": 9620,
		"chart-id": 9620,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "CO<sub>2 </sub> Emissionen nach Energieträger",
		"subtitle": "in Tonen, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2 </sub> Emissionen nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09620",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "4.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:16:34",
		"id": 9620
	},
	{
		"template": "template001",
		"data-id": 9621,
		"chart-id": 9621,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "CO<sub>2 </sub> Emissionen nach Verbrauchergruppe",
		"subtitle": "in Tonen, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2 </sub> Emissionen nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.09621",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "4.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:35:00",
		"id": 9621
	},
	{
		"template": "stock001",
		"data-id": 9622,
		"chart-id": 9622,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Jahresmitteltemperatur und Heizgradtage",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jahresmitteltemperatur und Heizgradtage",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09622",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "5.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:35:00",
		"id": 9622
	},
	{
		"template": "line001",
		"data-id": 9623,
		"chart-id": 9623,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Energieproduktivität und Pro-Kopf-Verbrauch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Energieproduktivität und Pro-Kopf-Verbrauch",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09623",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "5.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:38:46",
		"id": 9623
	},
	{
		"template": "line001",
		"data-id": 9624,
		"chart-id": 9624,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veränderung der Energiebezugsfläche",
		"subtitle": "in Quadratmeter, Basel-Stadt",
		"lesehilfe": "Lesehilfe",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veränderung der Energiebezugsfläche",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09624",
		"kennzahlenset": "Energiestatistik",
		"kuerzelKunde": "5.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-02T11:38:46",
		"id": 9624
	}
];