var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 11168,
		"chart-id": 11168,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Spitex-Anbieter",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 gab es im Kanton Basel-Stadt 57 Organisationen, sowie 61 Einzelpersonen, welche eine Spitex-Dienstleistung angeboten haben.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Spitex-Anbieter",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11168
	},
	{
		"template": "line001",
		"data-id": 11169,
		"chart-id": 11169,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 gab es 618 spezielle Wohnformen (20,4% aller Plätze) in den Pflegeheimen des Kantons Basel-Stadt",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11169
	},
	{
		"template": "line001",
		"data-id": 11170,
		"chart-id": 11170,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 gab es 108 allgemeine und 49 spezialisierte Plätze in einer Tages- oder Nachtpflegeeinrichtung im Kanton Basel-Stadt",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11170
	},
	{
		"template": "line001",
		"data-id": 11171,
		"chart-id": 11171,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug die Auslastung in den Pflegeheimen 92,2%.",
		"erlaeuterungen": "Ohne Pflegetage in ausserkantonalen Pflegeheimen.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11171
	},
	{
		"template": "line001",
		"data-id": 11172,
		"chart-id": 11172,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Pflegetage nach Pflegestufen in Pflegeheimen und der Pflegestufen-Durchschnitt",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 entfielen 9,7% der Pflegetage auf die Pflegestufe 2. Der Durchschnitt lag in diesem Jahr bei 6,4.",
		"erlaeuterungen": "Pflegestufen gemäss Art. 7a Krankenpflege-Leistungsverordnung (KLV).",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"Link: <a href = ' https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Pflegetage nach Pflegestufen in Pflegeheimen und der Pflegestufen-Durchschnitt",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11172
	},
	{
		"template": "line001",
		"data-id": 11173,
		"chart-id": 11173,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug die Auslastung in den Tages- und Nachtpflegeeinrichtungen bei 65,2%. Die Anzahl Aufenthaltstage, inkl. ausserkantonale Tagesgäste, betrug in diesem Jahr 25 579.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11173
	},
	{
		"template": "line001",
		"data-id": 11174,
		"chart-id": 11174,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegestunden Spitex",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug die Anzahl Spitex-Pflegestunden  mit Leistungsauftrag 307 168.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegestunden Spitex",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11174
	},
	{
		"template": "line001",
		"data-id": 11175,
		"chart-id": 11175,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegebedürftige und erbrachte Pflegeleistungen",
		"subtitle": "durch Angehörige oder andere nahestehenden Personen",
		"lesehilfe": "Im Jahr 2022 betrug die Anzahl Pflegebedürftige 287.",
		"erlaeuterungen": "Nur Stadt Basel",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegebedürftige und erbrachte Pflegeleistungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11175",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11175
	},
	{
		"template": "line001",
		"data-id": 11176,
		"chart-id": 11176,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Pflegeheime",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "Im Jahr 2022  betrug der Betrag der Finanzierung aus Ergänzungsleistungen 59,2 Mio. CHF und derjenige der Krankenversicherer 61,2 Mio. CHF.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11176
	},
	{
		"template": "line001",
		"data-id": 11177,
		"chart-id": 11177,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "Im Jahr 2022 stammten 2 Mio. CHF der Finanzierung für die Tages- und Nachtpflegeeinrichtungen aus dem Kanton und der Gemeinde.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11177
	},
	{
		"template": "line001",
		"data-id": 11178,
		"chart-id": 11178,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Spitex-Leistungen",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "Im Jahr 2022 betrug der Eigenbetrag der Klienten an der Finanzierung der Spitex-Leistungen 3,1 Mio. CHF.",
		"erlaeuterungen": "Beispieltext",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Spitex-Leistungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11178
	},
	{
		"template": "line001",
		"data-id": 11179,
		"chart-id": 11179,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Beiträge an die Pflege zuhause",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug der Durchschnittsbeitrag pro Tag der Stadt Basel 21,1 CHF.",
		"erlaeuterungen": "Durchschnittabeitrag pro Tag der Stadt Basel",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Beiträge an die Pflege zuhause",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11179
	}
];