var indikatorensetData = [
	{
		"template": "map001",
		"data-id": 11165,
		"chart-id": 11165,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Pflegeheime",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11165",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.1",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11165
	},
	{
		"template": "map001",
		"data-id": 11167,
		"chart-id": 11167,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen im Service-Angebot",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen im Service-Angebot",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11167",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.3",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11167
	},
	{
		"template": "map001",
		"data-id": 11180,
		"chart-id": 11180,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Patientenströme von ausserkantonalen und ausländischen Patienten",
		"subtitle": "in Basler Spitäler nach Wohnort (Zustrom)",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Patientenströme von ausserkantonalen und ausländischen Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11180",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.1",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_021",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11180
	},
	{
		"template": "map001",
		"data-id": 11181,
		"chart-id": 11181,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Patientenströme von stationären Basler Patienten",
		"subtitle": "in ausserkantonale Spitäler (Abstrom)",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Patientenströme von stationären Basler Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11181",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.2",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_022",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11181
	}
];