var indikatorensetData = [
	{
		"template": "map001",
		"data-id": 11165,
		"chart-id": 11165,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Pflegeheime",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Ende 2022 hatte das Adullam Pflegezentrum Basel 150 Plätze.",
		"erlaeuterungen": "Zusätzliche 30 Pflegeplätze des Pflegezentrums Adullam Basel (Nr. 1) sind auf der Pflegeheimliste Basel-Landschaft aufgeführt.<br>Der Umzug des Dominikushauses (Nr. 17) in den Neubau an der Immenbachstrasse 17 in Riehen erfolgte im Sommer 2023.<br>Am eigentlichen Standort des Pflegezentrum irides (Nr. 22) an der Kohlenbergstrasse 20 in Basel entsteht ein Neubau.<br><br>Stand Ende 2022",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/pflegeheim/pflegeheime.html' target = '_blank'>Aktuelle Pflegeheimliste</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11165",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.1",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11165
	},
	{
		"template": "map001",
		"data-id": 11167,
		"chart-id": 11167,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen im Service-Angebot",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Ende 2022 hatte das Tertianum mit 107 mit meisten Wohnungen mit einer Leistungsvereinbarung aller Standorte.",
		"erlaeuterungen": "Wohnungen mit Leistungsvereinbarung mit dem Kanton oder im tieferen Preissegment.<br><br>Stand Ende 2022",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/wohnen-mit-unterstuetzung/wohnen-mit-service.html' target = '_blank'>Angebote von Wohnungen mit Service-Angebot</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen im Service-Angebot",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11167",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.3",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11167
	},
	{
		"template": "line001",
		"data-id": 11168,
		"chart-id": 11168,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Spitex-Anbieter",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 gab es im Kanton Basel-Stadt 57 Organisationen, sowie 61 Einzelpersonen, welche eine Spitex-Dienstleistung angeboten haben.",
		"erlaeuterungen": "Stand Ende 2022",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/wohnen-mit-unterstuetzung/Spitex.html' target = '_blank'>Liste der zugelassenen Spitex-Organisationen und -Einzelpersonen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Spitex-Anbieter",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.4",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11168
	},
	{
		"template": "line001",
		"data-id": 11169,
		"chart-id": 11169,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"subtitle": "in baselstädtischen Pflegeheimen",
		"lesehilfe": "Im Jahr 2022 gab es 618 spezielle Wohnformen (20,4% aller Plätze) in den Pflegeheimen und 2 228 (73,7%) allgemeine Pflegeheimplätze im Kanton Basel-Stadt.",
		"erlaeuterungen": "Spezielle Wohnformen sind beispielsweise Pflegewohngruppen, psychogeriatrische Spezialeinrichtungen, Demenzabteilungen oder besondere Pflegeeinrichtung für suchtkranke Menschen.<br><br>Stand Ende 2022",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/pflegeheim/pflegeheime.html' target = '_blank'>Aktuelle Pflegeheimliste</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.5",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11169
	},
	{
		"template": "line001",
		"data-id": 11170,
		"chart-id": 11170,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "Im Kanton Basel-Stadt",
		"lesehilfe": "Ende 2022 standen insgesamt 157 Plätze (davon waren 49 spezialisierte Plätze) zur Verfügung.",
		"erlaeuterungen": "Spezialisierte Tagesstrukturen dienen der Betreuung von an einer Demenz erkrankten oder psychisch beeinträchtigten Personen.<br><br>Stand Ende 2022",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/wohnen-mit-unterstuetzung/tagesstrukturen.html' target = '_blank'>Aktuelle List der Anbieter von Tagespflegeeinrichtungen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.6",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11170
	},
	{
		"template": "line001",
		"data-id": 11171,
		"chart-id": 11171,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"subtitle": "",
		"lesehilfe": "2022 ist die Auslastung im Vergleich zum Vorjahr gestiegen und beträgt in den Pflegeheimen 92,2%. Die Pension- und Pflegetage beliefen sich 2022 auf über 1 Mio.",
		"erlaeuterungen": "Auslastung ohne Pflegetage in ausserkantonalen Pflegeheimen.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11171",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.7",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11171
	},
	{
		"template": "line001",
		"data-id": 11172,
		"chart-id": 11172,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Pflegetage nach Pflegestufen in Pflegeheimen und der Pflegestufen-Durchschnitt",
		"subtitle": "",
		"lesehilfe": "Der grösste Anteil mit 20 % der  Pflegeheimbewohner sind in der Pflegestufe 6 zu finden. Seit 2017 stieg die Pflegestufe um 10.3% bis ins Jahr 2022 an.  Die durchschnittliche Pflegestufe lag im Jahr 2022 bei 6,4.",
		"erlaeuterungen": "Die Pflegestufe gibt an, wie viel Pflege eine Person pro Tag benötigt. <br>In der Schweiz gibt es zwölf Pflegebedarfsstufen. Pflegestufe 1 zeigt einen Pflegebedarf von bis zu 20 Minuten am Tag an und die Pflegestufe 12 von mehr als 220 Minuten. <br>Pflegestufen gemäss Art. 7a Krankenpflege-Leistungsverordnung (KLV).",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [
			"<a href = ' https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>",
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/finanzierung/pflegeheim.html' target = '_blank'>Pflegeheim Tagestaxen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Pflegetage nach Pflegestufen in Pflegeheimen und der Pflegestufen-Durchschnitt",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.8",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11172
	},
	{
		"template": "line001",
		"data-id": 11173,
		"chart-id": 11173,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug die Auslastung in den Tages- und Nachtpflegeeinrichtungen 65,2%. Ein leichter Rückgang der totalen Auslastung als im Vorjahr ist zu verzeichnen. Im Jahr 2022 betrug die Anzahl der Aufenthaltstage, inkl. ausserkantonale Tagesgästen 25 579.",
		"erlaeuterungen": "Die Auslastung ist mit den ausserkantonalen Tagesgästen berechnet.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.9",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11173
	},
	{
		"template": "line001",
		"data-id": 11174,
		"chart-id": 11174,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegestunden Spitex",
		"subtitle": "",
		"lesehilfe": "Die geleisteten Spitexstunden sind seit 2011 stetig gestiegen. Im Jahr 2022 betrug die Anzahl Spitex-Pflegestunden mit Leistungsauftrag 307 168. Alle geleisteten Pflegestunden (ohne und mit Leistungsauftrag) betrugen 2022 total 582 229 Stunden.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegestunden Spitex",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.10",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11174
	},
	{
		"template": "line001",
		"data-id": 11175,
		"chart-id": 11175,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegebedürftiger und die erbrachten Pflegeleistungen",
		"subtitle": "durch Angehörige oder andere nahestehende Personen",
		"lesehilfe": "Die Anzahl der Pflegenden Angehörigen in Basel-Stadt ist seit 2021 leicht gestiegen. 2022 betrug die Anzahl Pflegebedürftige 287 mit insgesamt 74 287 erbrachte Pflegetage.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.gesundheitsversorgung.bs.ch/alterspflege/finanzierung/Pflegebeitraege.html' target = '_blank'>Pflegebeiträge</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegebedürftiger und die erbrachten Pflegeleistungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11175",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.11",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11175
	},
	{
		"template": "line001",
		"data-id": 11176,
		"chart-id": 11176,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Pflegeheime",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "Im Jahr 2022 betrug der Betrag der Finanzierung aus Ergänzungsleistungen 59,2 Mio. Franken, derjenige der Krankenversicherer 61,2 Mio. Franken und der kantonalen Restfinanzierung 48,4 Mio. Franken.  Das Gesamtvolumen der Pflegeheime betrug im Jahr 2022 336.6 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.12",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11176
	},
	{
		"template": "line001",
		"data-id": 11177,
		"chart-id": 11177,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "2022 blieben die Beträge von total 3.9 Mio. Franken wie im Vorjahr unverändert. Davon finanzierte der Kanton/die Gemeinden mit 2 Mio. Franken, die Krankenversicherer mit 0,8 Mio. Franken  und die Tagesgäste mit 1,1 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.13",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11177
	},
	{
		"template": "line001",
		"data-id": 11178,
		"chart-id": 11178,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Spitex-Leistungen",
		"subtitle": "in Mio. CHF",
		"lesehilfe": "2022  sind die Spitex Kosten im Vergleich zum Vorjahr leicht zurückgegangen und zwar auf 60,2 Mio. Franken. Im Jahr 2022 lag der grösste Beitrag mit 33,6 Mio. Franken bei den Krankenversicherern, gefolgt mit 23,5 Mio. Franken beim Kanton/bei den Gemeinden und schliesslich durch den Eigenbetrag der KlientInen mit 3,1 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Spitex-Leistungen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.14",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11178
	},
	{
		"template": "line001",
		"data-id": 11179,
		"chart-id": 11179,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Beiträge an die Pflege zu Hause",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 betrug der Durchschnittsbeitrag pro Tag der Stadt Basel 21,10 Franken. Der Kanton zahlte im Jahr 2022 2,1 Mio. Franken an die Beiträge an die Pflege zu Hause, davon entfielen 1.6 Mio. auf die Stadt Basel.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Beiträge an die Pflege zu Hause",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11179",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.15",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11179
	},
	{
		"template": "line001",
		"data-id": 11182,
		"chart-id": 11182,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Durchschnittliche Dauer eines stationären Aufenthalts baselstädtischer Patientinnen und Patienten",
		"subtitle": "In Basler Spitälern im zeitlichen Verlauf",
		"lesehilfe": "Im Jahr 2022 dauerte im Kanton Basel-Stadt ein stationärer Aufenthalt einer baselstädtischen Patientin oder Patienten in der Akutsomatik durchschnittlich 7.0 Tage, in der Psychiatrie 32.2 Tage und in der Rehabilitation 22.9 Tage.",
		"erlaeuterungen": "Die durchschnittliche Dauer eines stationären Aufenthalts ist in Tagen angegeben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittliche Dauer eines stationären Aufenthalts baselstädtischer Patientinnen und Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11182",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.3",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_023",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11182
	},
	{
		"template": "line001",
		"data-id": 11183,
		"chart-id": 11183,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stationäre Spitalaustritte der baselstädtischen Wohnbevölkerung",
		"subtitle": "im zeitlichen Verlauf in Abhängigkeit vom Spitalstandort",
		"lesehilfe": "Im Jahr 2022 erfolgten 38 796 (88,5%) der der insgesamt 43 834 (100%) Austritte baselstädtischer Patientinnen und Patienten nach einer stationären Behandlung aus einem Basler Spital.",
		"erlaeuterungen": "Gezählt werden die Austritte aus einer stationären Behandlung, um Doppelzählungen zu vermeiden (ein Patient kann beispielsweise im Jahr 2021 in ein Spital eintreten und erst im Folgejahr 2022 austreten).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Stationäre Spitalaustritte der baselstädtischen Wohnbevölkerung",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11183",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.4",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_024",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11183
	},
	{
		"template": "line001",
		"data-id": 11184,
		"chart-id": 11184,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Prozentuale Verteilung der stationären Behandlungen und des Case-Mix nach Leistungsbereichen",
		"subtitle": "bei baselstädtischen Patientinnen und Patienten in Basler Akutspitälern im Jahr 2022.",
		"lesehilfe": "Im Jahr 2022 sind 44.8% der stationären, akutsomatischen, nach Swiss-DRG abgerechneten Behandlungen baselstädtischer Patientinnen und Patienten dem Leistungsbereich «Basispaket Chirurgie und Innere Medizin» zugeordnet. Bei der Abrechnung entsprechen diese Behandlungen 34.3% (Case-Mix) des gesamten SwissDRG-Abgeltungsvolumens.",
		"erlaeuterungen": "Der Case Mix beschreibt den gesamten Schweregrad der abgerechneten Behandlungsfälle. Er ergibt sich aus der Summe der Kostengewichte der Fälle. Er kann als Vergleichswert für die Fallschwere, also den Gesamtschweregrad der Fälle eines Spitals oder - wie in der Grafik - eines Leistungsbereichs dienen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Prozentuale Verteilung der stationären Behandlungen und des Case-Mix nach Leistungsbereichen",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11184",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.5",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_025",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11184
	},
	{
		"template": "line001",
		"data-id": 11185,
		"chart-id": 11185,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Schweregrad und Komplexität",
		"subtitle": "CMI und PCCL der Baselstädtischen-Spitäler 2022",
		"lesehilfe": "Im Jahr 2022 betrug der durchschnittliche ökonomische Schweregrad gemäss Case Mix Index (CMI) über alle akutsomatischen Spitäler des Kantons Basel-Stadt 1.26. Der durchschnittliche patientenbezogene Schweregrad nach PCCL betrug 0.93.",
		"erlaeuterungen": "Der Case Mix (CM) beschreibt in der Akutsomatik den gesamten Schweregrad der nach Swiss DRG abgerechneten Behandlungsfälle eines Spitals. Er ergibt sich aus der Summe der Kostengewichte der Fälle eines Spitals. <br>Dividiert man den Case Mix durch die Anzahl Fälle, erhält man den Case Mix Index (CMI), d.h. das durchschnittliche Kostengewicht der Fälle eines Spitals. Der CMI stellt einen Vergleichswert für die durchschnittliche Fallschwere und den damit verbundenen zeitlichen, personellen und materiellen Ressourcenverbrauch resp. Behandlungsaufwand dar (ökonomischer Schweregrad).<br>Der PCCL (Patient Complication and Comorbidity Level) oder auch patientenbezogener Schweregrad, errechnet sich in einem komplexen Verfahren aus Bewertungen von Nebendiagnosen und Komplikationen (CCL) und liegt zwischen 0 (keine) und 6 (schwerste Nebendiagnosen und/oder Komplikationen). Somit ist der PCCL ein Mass für die durchschnittliche Krankheitslast resp. Multimorbidität der stationär behandelten Patientinnen und Patienten eines Spitals.<br>Sowohl der berechnete ökonomische Schweregrad CMI wie auch der patientenbezogene Schweregrad PCCL bewegen sich im Rahmen der Werte, die für einen Stadtkanton zu erwarten sind. Beispielsweise werden im Universitätsspital Basel häufig überdurchschnittlich komplexe Fälle mit entsprechend hohem Ressourcenverbrauch behandelt. Dies resultiert in einem Case Mix Index (CMI) grösser als 1.0.  <br>Patientinnen und Patienten mit hoher Krankheitslast und damit ein hoher PCCL-Wert (grösser als 1) ist für Spitäler resp. Leistungsbereiche zu erwarten, die auf die Behandlung von Betagten (zum Beispiel die Universitäre Altersmedizin FELIX PLATTER) oder auf die Behandlung von Menschen mit unheilbaren, lebensbedrohlichen oder mit chronisch fortschreitenden Krankheiten ausgerichtet sind (z.B. das Palliativzentrum Hildegard)",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schweregrad und Komplexität",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "I.14.2.11185",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.6",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_026",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-26T10:35:50",
		"id": 11185
	}
];