var indikatorensetNames = [
	"Arbeitsmarkt",
	"Legislaturplan",
	"Nachhaltigkeit",
	"Wohnraumentwicklung",
	"Cercle-Indicateurs",
	"Umwelt",
	"Gesellschaftlicher-Zusammenhalt",
	"Wohnviertel",
	"Richtplan",
	"Wanderungen",
	"Integration",
	"Richtplan (Print)",
	"Legislaturplan (Print)",
	"PDF_Karten_cont",
	"PDF_Karten_cat",
	"Tourismus",
	"Wanderungen (Print)",
	"Test"
];