var indikatorensetNames = [
	"Arbeitsmarkt",
	"Legislaturplan",
	"Nachhaltigkeit",
	"Wohnraumentwicklung",
	"Cercle-Indicateurs",
	"Umwelt",
	"Gesellschaftlicher-Zusammenhalt",
	"Wohnviertel",
	"Richtplan",
	"CMS Kennzahlen Soziales (Print)",
	"Wanderungen",
	"Integration",
	"Richtplan (Print)",
	"Legislaturplan (Print)",
	"Gefragte Karten",
	"Tourismus",
	"Integration (Print)",
	"Wanderungen (Print)",
	"Steuern",
	"Arbeitsmarkt (Print)",
	"Monatsindikatoren",
	"Testset",
	"Bevoelkerungsszenarien",
	"CMS Kennzahlen Soziales",
	"Wirtschaftsbericht BS_BL_JU",
	"Test"
];