var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9575,
		"chart-id": 9575,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "Innenstadt und Stadt Basel",
		"lesehilfe": "In der Innenstadt befinden sich 4 479 Arbeitsstätten. Rund 21% gehören zur Branchengruppe Unternehmensdienstleistungen und Freiberufe, 16% zum Gesundheits- und Sozialwesen und 13% zum Detailhandel (gesamte Stadt Basel: 8%).",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09575",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.1-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T03:01:27",
		"id": 9575
	},
	{
		"template": "line001",
		"data-id": 9579,
		"chart-id": 9579,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Requisitionen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2021 wurden in der  Innenstadt 1 306 Requisitionen erfasst. In der Stadt Basel waren es 4 409 und im Kanton Basel-Stadt 4 636.",
		"erlaeuterungen": "Requisitionen sind Meldungen, die bei der Polizeieinsatzzentrale eingegangen sind. Die Requisitionen sind seit 2012 verfügbar.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Anzahl Requisitionen",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.09579",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.3-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9579
	},
	{
		"template": "template001",
		"data-id": 9580,
		"chart-id": 9580,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Requisitionen in der Innenstadt nach Kategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In der Innenstadt war im Jahr 2021 der häufigste Grund für Meldungen bei der Polizeieinsatzzentrale Lärm (408 Requisitionen). Am zweit- und dritthäufigsten waren Requisitionen wegen Körperverletzung (220) sowie wegen Bettelei und Obdachlosigkeit (188).",
		"erlaeuterungen": "Requisitionen sind Meldungen, die bei der Polizeieinsatzzentrale eingegangen sind. Die Requisitionen sind seit 2012 verfügbar.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Anzahl Requisitionen in der Innenstadt nach Kategorie",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.09580",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.3-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9580
	}
];