var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9575,
		"chart-id": 9575,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09575",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.1-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9575
	},
	{
		"template": "line001",
		"data-id": 9577,
		"chart-id": 9577,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Belegungsdauer der Allmend in der Innenstadt",
		"subtitle": "nach Veranstaltungsort, in Tagen, Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte Veranstaltungen stattfinden. Für jeden Platz existiert ein jährliches Kontingent der maximalen Veranstaltungstage sowie ein Kontingent für Veranstaltungstage mit besonders lärmintensiven Auswirkungen. <br>Als Veranstaltung im Sinne der Bespielungspläne gelten alle Anlässe auf Allmend, die nach 20:00 Uhr stattfinden oder Anlässe, die vor 20:00 Uhr Lautsprecher und/oder unverstärkte laute Musikinstrumente einsetzen. Tagsüber stattfindene Märkte gelten daher bspw. nicht als Veranstaltung im Sinne des Bespielungsplanes. Ausgenommen ist auch die Fasnacht. Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl.Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Belegungsdauer der Allmend in der Innenstadt",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.2-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9577
	},
	{
		"template": "line001",
		"data-id": 9578,
		"chart-id": 9578,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Lärmintensive Veranstaltungen auf der Allmend in der Innenstadt",
		"subtitle": "nach Veranstaltungsort, Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte Veranstaltungen stattfinden. Für jeden Platz existiert ein jährliches Kontingent der maximalen Veranstaltungstage sowie ein Kontingent für Veranstaltungstage mit besonders lärmintensiven Auswirkungen. <br>Als Veranstaltung im Sinne der Bespielungspläne gelten alle Anlässe auf Allmend, die nach 20:00 Uhr stattfinden oder Anlässe, die vor 20:00 Uhr Lautsprecher und/oder unverstärkte laute Musikinstrumente einsetzen. Tagsüber stattfindene Märkte gelten daher bspw. nicht als Veranstaltung im Sinne des Bespielungsplanes. Ausgenommen ist auch die Fasnacht. Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl.Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Lärmintensive Veranstaltungen auf der Allmend in der Innenstadt",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.2-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9578
	},
	{
		"template": "template001",
		"data-id": 9583,
		"chart-id": 9583,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettomietpreise Innenstadt",
		"subtitle": "in Franken pro m<sup>2</sup>, Basel-Stadt, 2016-2020",
		"lesehilfe": "Die Nettomiete pro m<sup>2</sup> von 3- und 4-Zimmer-Wohnungen liegt in der Innenstadt im Durchschnitt der Jahre 2016 bis 2020 bei 18,5 Franken.",
		"erlaeuterungen": "Der m²-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4- Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Nettomietpreise Innenstadt",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.09583",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.2-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9583
	},
	{
		"template": "line001",
		"data-id": 9587,
		"chart-id": 9587,
		"filter": "",
		"parentId": "6169",
		"children": [],
		"title": "Anzahl Besuche in Theater, Kinos und Museen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Kinobesuche haben im Lauf der Zeit deutlich abgenommen: von fast 1,1 Mio. im Jahr 2003 auf rund 594 000 im Jahr 2019. Bei den übrigen Institutionen blieben die Zahlen vergleichsweise konstant.",
		"erlaeuterungen": "In den Kategorien «Theater» und «Kleintheater» entsprechen die Zahlen jeweils der Saison von Mitte des Vorjahres bis Mitte des Datenjahres, also bspw. 2019 der Saison 2018/19.",
		"quellenangabe": [
			"Jeweilige Institutionen",
			"Bundesamt für Statistik (BFS), Film- und Kinostatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Besuche in Theater, Kinos und Museen",
		"thema": "16 Kultur und Sport",
		"unterthema": "Kultureinrichtungen",
		"kuerzel": "I.16.1.09587",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.1-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:25:45",
		"id": 9587
	},
	{
		"template": "line001",
		"data-id": 9590,
		"chart-id": 7588,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2020 und 2021 um von 120 500  m² auf 184 700 m² zugenommen (+ 53%). Dies ist hauptsächlich auf eine Zunahme im Bürobereich von 76 500  m² auf 122 400  m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09590",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.3-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:25:49",
		"id": 9590
	},
	{
		"template": "befragungen001",
		"data-id": 9591,
		"chart-id": 9591,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort in der Innenstadt Basels",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2019 gaben fast 90% der befragten Personen in Basel an, mit den Einkaufsmöglichzkeiten an ihrem Wohnort zufrieden zu sein. 85% bzw. 81% sind zufrieden mit den Grünanlagen bzw. der öffentlichen Sicherheit. Mit der Sauberkeit sind drei Viertel zufrieden (37,4% «sehr» und 38,7% «eher zufrieden») und mit der Lärmsituation sind es 67% (25,8% «sehr» und 41,5% «eher zufrieden»).",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort in der Innenstadt Basels",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.4-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-04-19T12:30:38",
		"id": 9591
	},
	{
		"template": "template001",
		"data-id": 9598,
		"chart-id": 6126,
		"filter": "",
		"parentId": "6126",
		"children": [],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2021",
		"lesehilfe": "Im Jahr 2021 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 97,9 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 7.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09598",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.1-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:10",
		"id": 9598
	},
	{
		"template": "template001",
		"data-id": 9599,
		"chart-id": 6011,
		"filter": "",
		"parentId": "6011",
		"children": [],
		"title": "Zu- und Weggezogene nach Zuzugsort und Wegzugsort",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2020 zogen 13 480 Personen neu in den Kanton Basel-Stadt. Dies ist der niedrigste Wert der letzten zehn Jahre. 12 524 Personen verliessen den Kanton im Jahr 2020. Letztmals weniger Weggezogene wurden 2012 - nämlich 12 441 - registriert. Der Wanderungssaldo fiel zwischen 2011 und 2020 stets positiv aus und ging jeweils einzig auf die Zuwanderung aus dem Ausland zurück. Im Vergleich zum Jahr 2019 hat die Zahl der Wanderungsbewegungen zwischen Basel-Stadt und der Nordwestschweiz sowie der übrigen Schweiz zugenommen, während die Zahl der Wanderungsbewegungen zwischen Basel-Stadt und dem Ausland zurückgegangen ist.",
		"erlaeuterungen": "Nordwestschweiz: Kanton Basel-Landschaft, Bezirke Dorneck und Thierstein des Kantons Solothurn sowie Bezirke Laufenburg und Rheinfelden einschliesslich der Gemeinden Bözen, Effingen und Elfingen des Kantons Aargau.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zu- und Weggezogene nach Zuzugsort und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.09599",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.2-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-05-20T08:05:26",
		"id": 9599
	},
	{
		"template": "line001",
		"data-id": 9600,
		"chart-id": 6546,
		"filter": "",
		"parentId": "6546",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach einem Höchststand von 1,42 Millionen Übernachtungen im Jahr 2019 brach die Anzahl Logiernächte 2020 auf 545 906 Übernachtungen ein. Das Jahr 2021 schloss bei 784 607 Logiernächten, das sind 238 701 bzw. 43,7% mehr als 2020. Gäste aus der Schweiz übernachteten im Berichtsjahr 401 814 Mal in einem baselstädtischen Hotel, 2020 waren es 279 513. Dies entspricht einem Plus von 122 301 Logiernächten oder 43,8%. Gäste aus dem Ausland logierten 2021 insgesamt 382 793 Mal in einem Hotel in Basel-Stadt, 2020 waren es 266 393. Hier beträgt der Zuwachs 116 400 Logiernächte bzw. 43,7%.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.09600",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.3-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-10T09:17:32",
		"id": 9600
	},
	{
		"template": "template001",
		"data-id": 9601,
		"chart-id": 7971,
		"filter": "",
		"parentId": "7971",
		"children": [],
		"title": "Hotelübernachtungen",
		"subtitle": "pro Einwohner, 2019",
		"lesehilfe": "Die Kernstädte weisen die höchste Übernachtungskonzentration in Hotelbetrieben auf. Am meisten Hotelübernachtungen pro Einwohner werden 2019 in der Stadt Genf (10,8) registriert, gefolgt von den Städten Zürich (8,7) und Basel (8,2). In der Agglomeration Basel zeigen auch die deutschen Gemeinden eine relativ hohe touristische Attraktivität (4,1 Hotelübernachtungen pro Einwohner).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Hotelübernachtungen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.09601",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.3-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-25T08:37:34",
		"id": 9601
	}
];