var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 7573,
		"chart-id": 9066,
		"filter": "",
		"parentId": "7573",
		"children": [],
		"title": "Leerwohnungsbestand und -quote",
		"subtitle": "Basel-Stadt und Basel-Landschaft",
		"lesehilfe": "Die Leerstandsquote beider Basel zusammen ist innert Jahresfrist auf 0,7% gesunken. Insgesamt standen 2024 in den beiden Halbkantonen 1 984 Wohnungen leer, 604 weniger als 2023.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsbestand und -quote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-1",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:28",
		"id": 9066
	},
	{
		"template": "template001_print",
		"data-id": 7574,
		"chart-id": 9067,
		"filter": "",
		"parentId": "7574",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Leerstandsquote im Stadtkanton sinkt 2024 auf 0,8%. Insgesamt stehen 897 Wohnungen leer, davon sind gut zwei Drittel Zwei- oder Dreizimmerwohnungen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-2",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:29",
		"id": 9067
	},
	{
		"template": "mappieGemeindenBSBL_print",
		"data-id": 9068,
		"chart-id": 9068,
		"filter": "",
		"parentId": "7575",
		"children": [],
		"title": "Leerwohnungsbestand nach Gemeinde",
		"subtitle": "Basel-Stadt und Basel-Landschaft, 2024",
		"lesehilfe": "Die Leerwohnungsquoten unterscheiden sich teilweise beträchtlich zwischen den Gemeinden. An der Spitze befinden sich Waldenburg mit 1,5% und Laufen mit 1,4%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Leerwohnungsbestand nach Gemeinde",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-4",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-13T12:10:28",
		"id": 9068
	},
	{
		"template": "template001_print",
		"data-id": 7576,
		"chart-id": 9069,
		"filter": "",
		"parentId": "7576",
		"children": [],
		"title": "Leerwohnungen und Leerwohnungsquoten nach Kantonsgebiet",
		"subtitle": "Basel-Stadt und Basel-Landschaft, 2024",
		"lesehilfe": "Im Kanton Basel-Landschaft weisen die Bezirke Liestal und Arlesheim (je 0,8%) die höchsten Quoten auf. In den Bezirken Sissach (0,4%) und Waldenburg (0,6%) liegen die Leerwohnungsquoten hingegen unter dem gesamtkantonalen Wert von 0,7%. Im Bezirk Laufen bewegt sie sich im Kantonsdurchschnitt. Im Stadtkanton (0,8%) liegen die Quoten von Kleinbasel (0,8%) sowie Riehen und Bettingen (0,8%) über jener von Grossbasel (0,7%).",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk",
			"Gemeinde",
			"Wahlkreis"
		],
		"description": "Leerwohnungen und Leerwohnungsquoten nach Kantonsgebiet",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-5",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:29",
		"id": 9069
	},
	{
		"template": "pie001_print",
		"data-id": 7577,
		"chart-id": 9070,
		"filter": "",
		"parentId": "7577",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "Die Leerstandsquote der Dreizimmerwohnungen entspricht mit 0,8% der kantonalen Leerstandsquote. Die höchste Quote weisen mit 1,0% die Einzimmerwohnungen auf. Bei den Wohnungen mit sechs und mehr Zimmern ist sie mit 0,2% am niedrigsten.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-1",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:30",
		"id": 9070
	},
	{
		"template": "pie001_print",
		"data-id": 7578,
		"chart-id": 9071,
		"filter": "",
		"parentId": "7578",
		"children": [],
		"title": "Leerwohnungen nach Bautätigkeit",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "Rund 80% der leerstehenden Wohnungen sind in den letzen zwei Jahren unverändert geblieben; 18% sind renoviert und knapp 3% neu erstellt worden.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Bautätigkeit",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-2",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:30",
		"id": 9071
	},
	{
		"template": "template001_print",
		"data-id": 7579,
		"chart-id": 9072,
		"filter": "",
		"parentId": "7579",
		"children": [],
		"title": "Nettoproduktion an Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettoproduktion von Wohnungen beträgt 2023 865 Einheiten. Davon stammen 778 aus Neu- und 140 aus Umbauten. Durch Abbrüche gehen 53 Wohnungen verloren. 2024 wird eine Nettoproduktion von rund 450 Wohnungen prognostiziert.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoproduktion an Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-3",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:31",
		"id": 9072
	},
	{
		"template": "template001_print",
		"data-id": 7580,
		"chart-id": 9073,
		"filter": "",
		"parentId": "7580",
		"children": [],
		"title": "Wohnungen und Wohnbevölkerung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Leerwohnungsbestände von meist mehr als 800 Einheiten ergaben sich mit rückläufiger Bevölkerungszahl Mitte der 1970er- und 1980er-Jahre sowie von 1997 bis 2008. Seit 2019 liegt die Leerwohnungszahl wieder über dieser Marke.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen und Wohnbevölkerung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-4",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:31",
		"id": 9073
	},
	{
		"template": "pie001_print",
		"data-id": 7581,
		"chart-id": 9074,
		"filter": "",
		"parentId": "7581",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Landschaft, 2024",
		"lesehilfe": "Dreizimmerwohnungen machen rund 42% des Gesamtbestandes der leeren Wohnungen aus. Sie weisen mit einer Quote von 1,1% den höchsten Leerstand auf.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-1",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:31",
		"id": 9074
	},
	{
		"template": "pie001_print",
		"data-id": 7582,
		"chart-id": 9075,
		"filter": "",
		"parentId": "7582",
		"children": [],
		"title": "Leerwohnungen nach Bautätigkeit",
		"subtitle": "Basel-Landschaft, 2024",
		"lesehilfe": "88% der Leerwohnungen sind in den zwei letzten Jahren unverändert geblieben; knapp 3% sind neu erstellt und gut 9% renoviert worden.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Bautätigkeit",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-2",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:32",
		"id": 9075
	},
	{
		"template": "template001_print",
		"data-id": 7583,
		"chart-id": 9076,
		"filter": "",
		"parentId": "7583",
		"children": [],
		"title": "Nettoproduktion an Wohnungen",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Die Nettoproduktion von Wohnungen stieg seit dem Rückgang zwischen 2015 und 2018 bis 2022. 2023 nahm sie wieder ab. Bei den Werten von 2024 handelt es sich um eine Prognose.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoproduktion an Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-3",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:32",
		"id": 9076
	},
	{
		"template": "template001_print",
		"data-id": 7584,
		"chart-id": 9077,
		"filter": "",
		"parentId": "7584",
		"children": [],
		"title": "Wohnungen und Wohnbevölkerung",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Der Leerwohungsbestand ist 2023 geringfügig höher als 2022. Dies bei weiterhin steigender Bevölkerung und einer Zunahme bei den belegten Wohnungen.",
		"erlaeuterungen": "Seit 1994 mit Bezirk Laufen. Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen und Wohnbevölkerung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-4",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:32",
		"id": 9077
	},
	{
		"template": "template001_print",
		"data-id": 7585,
		"chart-id": 9078,
		"filter": "",
		"parentId": "7585",
		"children": [],
		"title": "Leerwohnungsquote nach Kanton",
		"subtitle": "",
		"lesehilfe": "Die Leerstandsquoten in den Kantonen Basel-Stadt und Basel-Landschaft lagen in den letzten Jahren unter dem schweizerischen Durchschnitt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsquote nach Kanton",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-5-1",
		"stufe1": "Wohnungsleerstand im nationalen Kontext",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:33",
		"id": 9078
	},
	{
		"template": "line001_print",
		"data-id": 7586,
		"chart-id": 9079,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"subtitle": "",
		"lesehilfe": "Mit dem vor gut zehn Jahren einsetzenden Anstieg der Wohnbevölkerung ging auch die Basler Leerwohnungsquote bis 2017 auf Werte im Bereich der anderen grösseren Schweizer Städte zurück. Seit 2019 hat die Stadt Basel die anderen Grossstädte bezüglich der Leerwohnungsziffer deutlich überholt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde",
			"Schweiz"
		],
		"description": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-5-2",
		"stufe1": "Wohnungsleerstand im nationalen Kontext",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-08-17T10:03:07",
		"id": 9079
	},
	{
		"template": "line001_print",
		"data-id": 7587,
		"chart-id": 9080,
		"filter": "",
		"parentId": "7587",
		"children": [],
		"title": "Geschäftsleerstandsfläche",
		"subtitle": "in m², Basel-Stadt und Basel-Landschaft",
		"lesehilfe": "Das Angebot an Geschäftsflächen ist 2024 im Kanton Basel-Landschaft um 10,6% gesunken, im Stadtkanton dagegen um 30,8% gestiegen. In den beiden Basel zusammen ist das Angebot gegenüber dem Vorjahr um 11,2% auf 402 127 m² gestiegen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-1",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:33",
		"id": 9080
	},
	{
		"template": "line001_print",
		"data-id": 7588,
		"chart-id": 9081,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2023 und 2024 von 190 600 m² auf 249 200 m² zugenommen. Dies ist hauptsächlich auf eine Zunahme im Bürobereich von 134 300 m² auf 175 100 m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-2",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:34",
		"id": 9081
	},
	{
		"template": "line001_print",
		"data-id": 7589,
		"chart-id": 9082,
		"filter": "",
		"parentId": "7589",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Landschaft",
		"lesehilfe": "Im Landkanton hat die Bürofläche zwischen 2023 und 2024 um rund 15 500 m² auf gut 71 000 m² abgenommen. Die Büroflächen sind mit einem Anteil von gut 46% immer noch der grösste Bereich. Danach folgt die Gewerbefläche mit 33%.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-3",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:34",
		"id": 9082
	},
	{
		"template": "pie001_print",
		"data-id": 7590,
		"chart-id": 9083,
		"filter": "",
		"parentId": "7590",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "Basel-Stadt, Anteile 2024",
		"lesehilfe": "Rund 70% des Geschäftsleerstandes entfallen auf den Bürobereich. Auf Gewerbe- und Lagerflächen entfallen jeweils knapp 13% und auf Ladenflächen gut 4%.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-4",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:34",
		"id": 9083
	},
	{
		"template": "pie001_print",
		"data-id": 9064,
		"chart-id": 9084,
		"filter": "",
		"parentId": "9064",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "Basel-Landschaft, Anteile 2024",
		"lesehilfe": "Der Bürobereich erreicht nach der aktuellen Abnahme noch einen Anteil von gut 46% der leerstehenden Geschäftsflächen. Danach folgt die Gewerbefläche mit 33%.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-5",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:35",
		"id": 9084
	},
	{
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Landschaft",
		"kuerzel": "I.09.2.09144",
		"kuerzelKunde": "LEB-2-3",
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kennzahlenset": "Leerstand (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-12-24T09:50:49.4949",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Landkanton machen Drei- und Vierzimmerwohnungen gut drei Viertel des Leerwohnungsbestandes aus. Die Leerwohnungsquote bleibt 2020 bei 1,1%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"parentId": 9137,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9137,
		"chart-id": 9144,
		"filter": "",
		"id": 9144
	},
	{
		"template": "template001_print",
		"data-id": 9336,
		"chart-id": 9336,
		"filter": "",
		"parentId": "9137",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Im Landkanton ist die Leerstandsquote 2024 auf 0,7% gesunken. 1 087 Wohnungen stehen leer. Davon sind knapp drei Viertel Drei- oder Vierzimmerwohnungen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-3",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-15T08:12:29",
		"id": 9336
	}
];