var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 2956,
		"chart-id": 2956,
		"filter": "",
		"parentId": null,
		"children": [
			6276
		],
		"title": "Zufriedenheit mit der Gesundheitsversorgung, nach Altersgruppe",
		"subtitle": "«Wie zufrieden sind Sie mit der Gesundheitsversorgung?», Anteil sehr oder eher Zufriedene, Basel-Stadt",
		"lesehilfe": "93,2% der im Jahr 2019 Befragten sind sehr oder eher zufrieden mit der Gesundheitsversorgung. Befragte mit Schweizer Pass bewerten die Gesundheitsversorgung mit 93,9% höher als ausländische Befragte (90,7%). Bei den Altersgruppen ab 60 Jahren liegt die Zufriedenheit bei über 95%. Zwischen den Geschlechtern ist 2019 kein signifikanter Unterschied feststellbar.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) statt wie zuvor telefonisch durchgeführt. Dieser Methodenwechsel kann einen Einfluss auf die Vergleichbarkeit der Ergebnisse haben (weitere Informationen: <a href='https://www.statistik.bs.ch/befragungen' target='_blank'>www.statistik.bs.ch/befragungen</a>).<br>«Zufriedenheit» fasst die Antwortkategorien «Sehr zufrieden» und «Eher zufrieden» zusammen. Um die Daten über die Jahre vergleichen zu können bleiben befragte Personen, welche die Frage mit «Weiss nicht» oder gar nicht beantwortet haben, unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit der Gesundheitsversorgung, nach Altersgruppe",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.2956",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.11",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-12-18T02:52:36",
		"id": 2956
	},
	{
		"template": "line001",
		"data-id": 3104,
		"chart-id": 3104,
		"filter": "",
		"parentId": null,
		"children": [
			6278
		],
		"title": "Globale und kontinentale Erreichbarkeit",
		"subtitle": "Stadt Basel im Vergleich mit ausgewählten Schweizer Städten",
		"lesehilfe": "Die kontinentale Erreichbarkeit der Städte Basel, Zürich und Genf blieb in den letzten zehn Jahren eher unverändert, während sich diejenige der Stadt Bern seit 2012 verschlechtert hat. Die Stadt Zürich bewegt sich auf einem höheren Niveau als Basel und Genf, die Erreichbarkeit der Stadt Bern liegt etwas darunter. Die Entwicklung bei der globalen Erreichbarkeit verläuft bei allen Städten parallel und mit wenig Veränderungen über die Jahre. Basel liegt bei diesem Indikator zusammen mit Genf und Bern unterhalb des Niveaus von Zürich.",
		"erlaeuterungen": "Bei der Kennzahl handelt es sich um einen indexierten Wert: 100 = Mittel aller einbezogenen Ursprungsregionen im Jahr 2002; globale Erreichbarkeit = Erreichbarkeit von Regionen ausserhalb Europas; kontinentale Erreichbarkeit = Erreichbarkeit aller Regionen Europas. Erreichbarkeit ist kein klares, lineares Konzept. Vielmehr beruht es auf einer Vielzahl von Faktoren, die unter dem Themenbereich Erreichbarkeit subsumiert werden können. Die Erreichbarkeitsmodelle von BAK Economics basieren auf dem Ansatz aktivitätsbasierter Gravitationsindikatoren. Ihnen liegen Strassenerreichbarkeit, Bahnfahr- und Flugpläne zugrunde. Zudem folgen sie dem Konzept der Erreichbarkeit «aus der Region» (outbound accessibility), d. h. es werden Reisezeit und Frequenz herangezogen, die benötigt werden, um aus der Region andere Regionen zu erreichen. Der resultierende Indikator reflektiert das gesamte Potenzial aller Regionen ohne jegliche Limitierung der Reisezeit. Jedoch werden die Reisedestinationen über die Reisezeit und das Bruttoinlandprodukt der Region gewichtet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [
			"Weiterführende Informationen: <a href = 'https://www.bak-economics.com/en/solutions/regional-analysis/region-international/location-factors/erreichbarkeit/' target = '_blank'>BAK Economics</a> und",
			"<a href = 'http://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/erreichbarkeit.html' target = '_blank'>Amt für Mobilität</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Globale und kontinentale Erreichbarkeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.3104",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.12",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-03-04T05:14:05",
		"id": 3104
	},
	{
		"template": "befragungen001",
		"data-id": 5033,
		"chart-id": 5033,
		"filter": "",
		"parentId": null,
		"children": [
			6279
		],
		"title": "Transnationale Patentanmeldungen pro 1000 Beschäftigte",
		"subtitle": "nach ausgewählten Wirtschaftsbranchen, Jahresdurchschnitte",
		"lesehilfe": "In Basel-Stadt wurden in beiden betrachteten Perioden mehr Patente pro 1000 Einwohner und Jahr angemeldet als in den Kantonen Basel-Landschaft und Zürich. Der grösste Teil davon wurde im Bereich der Pharmazeutischen Industrie angemeldet. Im Kanton Zürich wurden vor allem in der Branche Elektronik, Optik und Maschinenbau Patente angemeldet.",
		"erlaeuterungen": "Die transnationalen Patentanmeldungen bestehen aus Patenten, die von Forschenden am European Patent Office (EPO) oder über das Patent Cooperation Treaty (PCT)-Verfahren (gleichzeitige Patentanmeldung bei einer Vielzahl von nationalen Patentämtern) angemeldet wurden. Die über das PCT-Verfahren zum EPO gelangenden Patentanmeldungen werden nur einmal gezählt. Die Regionalisierung der Patentdaten erfolgt nach der Wohnadresse der beteiligten Forscher und wird von der OECD durchgeführt (REGPAT database). Die Patentanmeldungen sind pro 1000 Einwohner im Mittel über mehrere Jahre abgebildet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Transnationale Patentanmeldungen pro 1000 Beschäftigte",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Volkseinkommen",
		"kuerzel": "I.04.1.05033",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.5",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-06-07T08:33:19",
		"id": 5033
	},
	{
		"template": "template001",
		"data-id": 5041,
		"chart-id": 5041,
		"filter": "",
		"parentId": null,
		"children": [
			6369
		],
		"title": "Anzahl Neugründungen in Basel-Stadt",
		"subtitle": "in ausgewählten Branchen",
		"lesehilfe": "Im Jahr 2018 wurden in Basel-Stadt 989 neue Unternehmen gegründet, 72 bzw. 6,8% weniger als im Jahr 2017. Um 11,8% zugenommen haben 2018 die Neugründungen im Bereich der freiberuflichen, wissenschaftlichen und technischen Dienstleistungen, wo rund 30% aller neugegründeten Unternehmen tätig sind.",
		"erlaeuterungen": "Unter Neugründungen werden Unternehmen mit marktwirtschaftlicher Tätigkeit verstanden, die tatsächlich neu entstanden sind, also nicht aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen hervorgegangen sind. Die Statistik der Unternehmensdemografie (UDEMO) basiert auf der Statistik der Unternehmensstruktur (STATENT).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Neugründungen in Basel-Stadt",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Neugründungen",
		"kuerzel": "I.06.2.5041",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.4",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-04T04:49:13",
		"id": 5041
	},
	{
		"template": "befragungen001",
		"data-id": 5192,
		"chart-id": 5192,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Besuchte Weiterbildungen und Kurse im letzten Jahr",
		"subtitle": "«Haben Sie in den letzten 12 Monaten eine Veranstaltung oder einen Kurs besucht oder machen Sie zurzeit eine Weiterbildung?», Basel-Stadt, 2015",
		"lesehilfe": "22,0% der Befragten gaben 2019 an, innerhalb der letzten zwölf Monate einen Weiterbildungskurs besucht zu haben, 17,4% haben mehrere Kurse besucht. 57,7% gaben an, keinen Kurs besucht zu haben.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Besuchte Weiterbildungen und Kurse im letzten Jahr",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.5192",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.7",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-06-15T03:26:51",
		"id": 5192
	},
	{
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2019",
		"kuerzel": "I.04.2.6126",
		"kuerzelKunde": "1.1",
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kennzahlenset": "Legislaturplan",
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"aktualisierungsdatum": "2020-08-31T12:32:21.2121",
		"stufe1": "Ziel 1: Der Kanton Basel-Stadt ist als starkes Zentrum anerkannt.",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Jahr 2019 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 90,6 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 9. Die nächste Aktualisierung des KWI durch die UBS wird voraussichtlich 2021 stattfinden.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"template": "template001",
		"darstellungsart": "Grafik",
		"printformat": "",
		"orderKey": "01_00_00_00_00_001",
		"parentId": null,
		"children": [
			"6283"
		],
		"renderLink": [],
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 6126,
		"chart-id": 6126,
		"filter": "",
		"id": 6126
	},
	{
		"template": "template001",
		"data-id": 6127,
		"chart-id": 6127,
		"filter": "",
		"parentId": null,
		"children": [
			6050,
			6284,
			8939
		],
		"title": "Kantonales Wettbewerbsprofil",
		"subtitle": "Basel-Stadt im Vergleich zum Mediankanton, 2021",
		"lesehilfe": "Basel-Stadt liegt im Jahr 2021 in den Bereichen Humankapital und Erreichbarkeit an der Spitze aller Kantone. Die Werte des hier dargestellten Mediankantons entsprechen dem Medianwert aller Kantone der jeweiligen Säule.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt. Der Mediankanton ist ein Referenzkanton, der aus den Medianwerten der jeweiligen Wettbewerbssäulen zusammengesetzt ist. Der Medianwert der jeweiligen Säule unterteilt die Rangliste der Kantone in eine obere und eine untere Hälfte mit je 13 Kantonen. Für die Interpretation der kantonalen Wettbewerbsprofile gilt: Je höher der Wert für einen Kanton in einer Säule ist, desto besser ist seine relative Bewertung.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonales Wettbewerbsprofil",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.06127",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.2",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-20T08:40:01",
		"id": 6127
	},
	{
		"template": "line001",
		"data-id": 6147,
		"chart-id": 6037,
		"filter": "",
		"parentId": "6037",
		"children": [],
		"title": "Verhältnis der Löhne von Frauen und Männern",
		"subtitle": "im privaten Sektor in der Nordwestschweiz",
		"lesehilfe": "Im Jahr 2018 erreicht der Medianlohn der Frauen in der Nordwestschweiz 5 884 Franken. Dies entspricht 86,4% des Medianlohns der Männer (6 814 Fr.). Der Lohnunterschied hat sich gegenüber 2016 nicht verändert, ist jedoch geringer als zehn Jahre zuvor (2008 betrug das Lohnverhältnis 81,5%).",
		"erlaeuterungen": "Grundlage ist der Median des monatlichen Bruttolohns, standardisiert (Vollzeitäquivalent basierend auf 4,33 Wochen à 40 Arbeitsstunden), im privaten Sektor (ohne Landwirtschaft), im Monat Oktober, einschliesslich u. a. 1/12 des 13. Monatslohns und 1/12 der jährlichen Boni.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Lohnstrukturerhebung (LSE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verhältnis der Löhne von Frauen und Männern",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Löhne",
		"kuerzel": "I.03.3.06147",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.12",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-12-14T07:44:23",
		"id": 6147
	},
	{
		"template": "line001",
		"data-id": 6150,
		"chart-id": 6150,
		"filter": "",
		"parentId": null,
		"children": [
			6054,
			6303,
			8943
		],
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Mittelwert des Reineinkommens des obersten Quintils ist seit 1991 am deutlichsten gestiegen. Die übrigen Werte verlaufen relativ konstant. Über den Betrachtungszeitraum gab es zahlreiche Veränderungen in der Steuergesetzgebung, die einen Einfluss auf die Berechnung des Reineinkommens haben können, etwa durch erhöhte Abzugsmöglichkeiten (z. B. für Berufskosten).",
		"erlaeuterungen": "Mittelwert und Median werden pro Veranlagung berechnet. Die Quintile ergeben sich, wenn man alle Veranlagungen nach Höhe des Reineinkommens sortiert und fünf gleich grosse Gruppen bildet. Der Mittelwert des obersten respektive untersten Quintils ist der Durchschnitt des Reineinkommens derjenigen 20% der Veranlagungen mit den jeweils höchsten respektive niedrigsten Reineinkommen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.6150",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.1",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-03T08:04:56",
		"id": 6150
	},
	{
		"template": "line001",
		"data-id": 6154,
		"chart-id": 6154,
		"filter": "",
		"parentId": null,
		"children": [
			6007,
			6258,
			6306,
			8454,
			8957
		],
		"title": "Verkehrsleistungsindex",
		"subtitle": "indexiert (Basis 2010 = 100), Basel-Stadt",
		"lesehilfe": "Die COVID-19-Pandemie führte im Jahr 2020 zu einem Rückgang des Verkehrsaufkommens in Basel-Stadt: Bei sämtlichen Verkehrsmitteln ist im Jahr 2020 ein Rückgang zu beobachten. Am stärksten ist der Rückgang beim öffentlichen Verkehr mit 35,4 Prozentpunkten. Einzig der Veloverkehr blieb mehr oder weniger stabil (-3,1 Prozentpunkte), allerdings zeigte dort der Trend in den Jahren vor der Pandemie stark nach oben.",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Es wird die Veränderung gegenüber dem Referenzjahr 2010 dargestellt (indexiert, 2010 = 100). Bei den Fussgängerdaten ist das Referenzjahr 2013, da diese erst seit dann erhoben werden. <br/><br/>Der Verkehrsleistungsindex basiert auf den an automatischen Zählstellen erfassten Verkehrsaufkommen der einzelnen Kategorien, aus welchen mit Modellen die Verkehrsleistungen für den gesamten Kanton abgeleitet werden. Für den Auto- und Veloverkehr wird jede Zählstelle auf Basis des Gesamtverkehrsmodells der Region Basel gewichtet. Die Zählstellen des Fussverkehrs werden über den «Mikrozensus Verkehr» gewichtet.<br/><br/>Autoverkehr:<br/>Der Index für den motorisierten Individualverkehr (MIV) berechnet sich anhand von rund 40 Dauerzählstellen des Kantons Basel-Stadt, des Kantons Basel-Landschaft und des Bundesamtes für Strassen. Er umfasst die Verkehrsleistung aller Motorfahrzeuge auf baselstädtischem Kantonsgebiet (inkl. Lastwagen, Lieferwagen und Motorräder), aber ohne Linienbusse, Motorfahrräder und E-Bikes. Der MIV Total entspricht der Verkehrsleistung auf allen Strassen des Kantonsgebiets, der MIV Stadtstrassennetz derjenigen ohne Autobahnen.<br/><br/>Veloverkehr:<br/>Der Index für den Veloverkehr wird auf Basis von rund 20 Zählstellen des Kantons Basel-Stadt berechnet. Der Einfluss des Wetters auf den Veloverkehr wird mittels eines Modells herausgerechnet.<br/><br/>Fussverkehr:<br/>Der Index für den Fussverkehr basiert auf rund 18 Zählstellen. Die Daten werden erst seit dem Jahr 2013 erhoben.<br/><br/>Öffentlicher Verkehr:<br/>Der Index des öffentlichen Verkehrs basiert auf den Verkehrsleistungen der Tram-, Bus- und S-Bahn-Linien auf dem Gebiet des Kantons Basel-Stadt.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.06154",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.8",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-07-07T08:30:42",
		"id": 6154
	},
	{
		"template": "template001",
		"data-id": 6160,
		"chart-id": 9008,
		"filter": "",
		"parentId": "9008",
		"children": [
			4953
		],
		"title": "Endenergieverbrauch nach Verbrauchergruppe",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch hat zwischen 2010 und 2018 um 19,4% auf 4 645 GWh abgenommen. Der Rückgang verteilt sich hauptsächlich auf die Verbrauchergruppen Wohnen und Nichtwohnen.",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Primärenergie, welcher von den Energienutzern verbraucht wird. Bei den Energienutzern wird zwischen «Wohnen» und «Nichtwohnen» unterschieden, wobei zum Wohnen die privaten Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen, Industrie und Verkehr gehören.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'https://www.statistik.bs.ch/analysen-berichte/raum-umwelt/energiestatistik.html' target = '_blank'>Energiestatistik Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.06160",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.6",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-12-09T11:10:57",
		"id": 6160
	},
	{
		"template": "template001",
		"data-id": 6161,
		"chart-id": 9007,
		"filter": "",
		"parentId": "9007",
		"children": [],
		"title": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil erneuerbarer Energien am Bruttoverbrauch ist von 34,5% im Jahr 2010 auf 39,9% im Jahr 2018 gestiegen.",
		"erlaeuterungen": "Folgende Energieträger werden als erneuerbar berücksichtigt: Wasserkraft, Holz, Umweltwärme, thermische und fotovoltaische Sonnenenergie, Klärschlamm, Biogas, erneuerbare Elektrizität (in Basel-Stadt stammen 100% des importierten Strommixes aus erneuerbaren Quellen) und Kehricht (zu 50% als erneuerbar taxiert).<br><br>Die Summe der Verbräuche der erneuerbaren Energien wird durch den Gesamtenergieverbrauch dividiert.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"thema": "08 Energie",
		"unterthema": "Erneuerbare",
		"kuerzel": "I.08.3.06161",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.7",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-09-22T03:52:26",
		"id": 6161
	},
	{
		"title": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"subtitle": "Siedlungsabfälle und Wertstoffsammlungen in kg pro Kopf, Basel-Stadt",
		"kuerzel": "I.02.6.6163",
		"kuerzelKunde": "7.3",
		"description": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Entsorgung",
		"kennzahlenset": "Legislaturplan",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-11-19T08:59:37.3737",
		"stufe1": "Ziel 7: Der Kanton Basel-Stadt löst seine Umweltaufgaben.",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Siedlungsabfälle reduzierten sich zwischen dem Jahr 2000 und 2018 von ca. 194 auf 163 kg pro Kopf. Die Recyclingquote liegt aktuell bei 40,6%.",
		"erlaeuterungen": "Die Berechnungsmethode für die Recyclingquote wurde vom Amt für Umwelt und Energie im Jahr 2016 rückwirkend für alle abgebildeten Jahre revidiert (dezentrale Kompostierung nicht mehr eingerechnet). Dies führt zu einem tieferen Recyclinganteil im Vergleich zu früheren Berechnungen.",
		"template": "template001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_003",
		"parentId": null,
		"children": [
			"5796",
			"6314",
			"8917"
		],
		"renderLink": [],
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 6163,
		"chart-id": 6163,
		"filter": "",
		"id": 6163
	},
	{
		"template": "template001",
		"data-id": 6165,
		"chart-id": 6165,
		"filter": "",
		"parentId": null,
		"children": [
			6031,
			6316,
			8923
		],
		"title": "CO<sub>2</sub>-Emissionen",
		"subtitle": "in Tonnen, Basel-Stadt",
		"lesehilfe": "Die aus dem Bruttoenergieverbrauch abgeleiteten CO<sub>2</sub>-Emissionen nahmen zwischen 2010 und 2018 von 910 740 Tonnen auf 69 507 Tonnen ab. Das entspricht einer Reduktion um 24% bzw. einem Rückgang von 4,7 Tonnen auf 3,5 Tonnen CO<sub>2</sub> pro Kopf.",
		"erlaeuterungen": "Die CO<sub>2</sub>-Emission berechnet sich aus der Summe der Verbräuche aller fossilen Brennstoffe sowie Abfall multipliziert mit den jeweiligen Emissionskoeffizienten von CO<sub>2</sub>. Zur Berechnung des Pro-Kopf-Verbrauchs wird der CO<sub>2</sub>-Verbrauch durch die mittlere Bevölkerung dividiert. Erneuerbare Brennstoffe wie Holz oder Biogas sind nicht in den Emissionen eingeschlossen. Der in der Kehrichtverwertungsanlage (KVA) verbrannte Hauskehricht wird als 50% erneuerbar gezählt und ist somit nur zur Hälfte in die CO<sub>2</sub>-Emissionen eingerechnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2</sub>-Emissionen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luftschadstoffe",
		"kuerzel": "I.02.5.6165",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.1",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-12-02T08:26:30",
		"id": 6165
	},
	{
		"template": "befragungen001",
		"data-id": 6186,
		"chart-id": 6186,
		"filter": "",
		"parentId": "4859",
		"children": [],
		"title": "Beurteilung der kantonalen Verwaltung",
		"subtitle": "«Wie ist der letzte Kontakt mit der kantonalen Verwaltung verlaufen?», Basel-Stadt",
		"lesehilfe": "20,7% der im Jahr 2019 Befragten empfanden den letzten Kontakt mit der kantonalen Verwaltung als sehr positiv und 44,7% als eher positiv. 12,3% der Befragten empfanden den Kontakt als eher oder sehr negativ",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) statt wie zuvor telefonisch durchgeführt. Dieser Methodenwechsel kann einen Einfluss auf die Vergleichbarkeit der Ergebnisse haben (weitere Informationen: <a href='https://www.statistik.bs.ch/befragungen' target='_blank'>www.statistik.bs.ch/befragungen</a>).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung der kantonalen Verwaltung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.06186",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.3",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-12-18T03:00:17",
		"id": 6186
	},
	{
		"title": "Schulabgängerinnen und -abgänger ohne Anschlusslösung",
		"subtitle": "nach Schultyp, Basel-Stadt",
		"kuerzel": "I.15.7.6206",
		"kuerzelKunde": "3.1a",
		"description": "Schulabgängerinnen und -abgänger ohne Anschlusslösung",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kennzahlenset": "Legislaturplan",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-09-21T09:20:05.055",
		"stufe1": "Ziel 3: Der Kanton Basel-Stadt ist der Kern einer innovativen Wissensregion.",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Bei der Sekundarschule (und davor bei der Weiterbildungsschule) ist die Zahl der Schulabgängerinnen und -abgänger ohne Anschlusslösung konstant tief. Bei den übrigen Schultypen führen die geringe Zahl an Beobachtungen und die damit verbundenen grossen jährlichen Abweichungen zu einem unruhigen Kurvenverlauf.",
		"erlaeuterungen": "Datengrundlage bildet die jährliche Befragung der Schulabgängerinnen und Schulabgänger durch die Bildungsstatistikstelle des Bereichs Mittelschulen und Berufsbildung im Basler Erziehungsdepartement. Allgemeine Gewerbeschule: nur Link zum Beruf und Vorkurse; Berufsfachschule: nur Vorkurse und Vorlehren. Seit 2018 ersetzen die Werte der Sekundarschule diejenigen der Weiterbildungsschule.",
		"template": "line001",
		"darstellungsart": "Grafik",
		"printformat": "",
		"orderKey": "03_00_00_00_00_001",
		"parentId": null,
		"children": [
			"6336"
		],
		"renderLink": [],
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Berufs- und Schulwahlerhebung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 6206,
		"chart-id": 6206,
		"filter": "",
		"id": 6206
	},
	{
		"template": "template001",
		"data-id": 6996,
		"chart-id": 6996,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stationär behandelte Patienten",
		"subtitle": "in baselstädtischen Spitälern, nach Wohnkanton",
		"lesehilfe": "Im Jahr 2020 wurden insgesamt 62&nbsp;306 Patienten in baselstädtischen Spitälern stationär behandelt. Davon wohnten 27&nbsp;905 Personen im Kanton Basel-Stadt und 20&nbsp;614 in Basel-Landschaft.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr mindestens einmal aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden nur einmal gezählt).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Stationär behandelte Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06996",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.2",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-25T08:16:14",
		"id": 6996
	},
	{
		"template": "line001",
		"data-id": 9361,
		"chart-id": 8355,
		"filter": "",
		"parentId": "8355",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Die reale Wertschöpfung in der Pharmaindustrie in Basel-Stadt hat sich zwischen 2014 und 2019 mehr als verdoppelt. Die Wertschöpfung im Gesundheits- und Sozialwesen ist um 18% gestiegen. Genauso hoch war das Wertschöpfungswachstum im Maschinenbau; allerdings ist diese Branche, ebenso wie der Bereich Elektronik/Optik (-31%), sehr klein.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahres gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09361",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.3",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:23",
		"id": 9361
	},
	{
		"template": "template001",
		"data-id": 9363,
		"chart-id": 6460,
		"filter": "",
		"parentId": "6460",
		"children": [],
		"title": "Arbeitslosenquote nach Branche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die mittlere Arbeitslosenquote ist 2020 auf 3,8% gestiegen (2019: 3,0%). In allen Branchen ausser in der Chemie/Pharma hat die Quote gegenüber 2019 zugenommen. Die Arbeitslosenquote ist im Baugewerbe (12,6%), im Gastgewerbe (9,0%), in der Industrie  (7,0%, exkl. Chemie und Pharma) und in der Dienstleistungsgruppe Gebäudebetreuung, Sicherheit und sonstige wirtschaftliche Dienstleistungen (7,0%), in der z. B. auch das Reinigungsgewerbe enthalten ist, am höchsten.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl Arbeitslosen (SECO), geteilt durch die Erwerbstätigen aus der Sturkturerhebung (Pooling 2015-2017), da die Erwerbspersonen nach Branche nicht vorhanden sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.09363",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.8",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-03-23T08:36:41",
		"id": 9363
	},
	{
		"template": "line001",
		"data-id": 9365,
		"chart-id": 7588,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2020 und 2021 um 53% von 120 500  m² auf 184 700 m² zugenommen. Dies ist hauptsächlich auf eine Zunahme im Bürobereich von 76 500  m² auf 122 400  m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09365",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.10",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-25T08:16:19",
		"id": 9365
	},
	{
		"template": "template001",
		"data-id": 9368,
		"chart-id": 9368,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigte in der Branche Kultur",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Erwerbstätige in der Branche Kultur",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.09368",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.14",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-20T04:29:59",
		"id": 9368
	},
	{
		"template": "befragungen001",
		"data-id": 9369,
		"chart-id": 6499,
		"filter": "",
		"parentId": "6499",
		"children": [],
		"title": "Zufriedenheit mit dem Kulturangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Kulturangebot?», Basel-Stadt",
		"lesehilfe": "39,6% der im Jahr 2019 Befragten sind mit dem Kulturangebot sehr zufrieden und 40,8% eher zufrieden. Insgesamt 7,6% sind damit eher oder sehr unzufrieden. Nach Staatsangehörigkeit lässt sich 2019 kein signifikanter Unterschied in der Beurteilung beobachten.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.<br>Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Kulturangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09369",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.15",
		"stufe1": "Legislaturziel 1:  Attraktivität des Standorts langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-11-16T08:48:06",
		"id": 9369
	},
	{
		"template": "line001",
		"data-id": 9370,
		"chart-id": 8459,
		"filter": "",
		"parentId": "8459",
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Median des Reinvermögens ist im Zeitverlauf überwiegend gestiegen, seit 2007 insgesamt um 68,1%, von rund 11 400 auf 19 200 Franken. Der Anstieg des Medians ist ein Indikator dafür, dass sich die tieferen Vermögen im Allgemeinen insgesamt positiv entwickelt haben. Allerdings sind die Werte des Medians im Vergleich zum Mittelwert des Reinvermögens auf einem deutlich niedrigeren Niveau.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09370",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.2",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-26T08:26:05",
		"id": 9370
	},
	{
		"template": "line001",
		"data-id": 9371,
		"chart-id": 6036,
		"filter": "",
		"parentId": "6036",
		"children": [],
		"title": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Gini-Koeffizient des Reineinkommens nimmt im Zeitverlauf insgesamt leicht zu. Derjenige des Reinvermögens zeigt sich auf höherem Niveau etwas konstanter. Für das Reinvermögen liegt für das Jahr 2000 aufgrund von Gesetzesänderungen kein Wert vor.",
		"erlaeuterungen": "Der Gini-Koeffizient ist ein Mass für die Gleichmässigkeit einer Verteilung (hier des Reineinkommens und des Reinvermögens). Er kann Werte zwischen 0 (alle besitzen gleich viel) und 1 (einer besitzt alles) annehmen. Er wird aus der sogenannten Lorenzkurve abgeleitet.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09371",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.3",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-03T08:04:57",
		"id": 9371
	},
	{
		"template": "befragungen001",
		"data-id": 9374,
		"chart-id": 4862,
		"filter": "",
		"parentId": "4862",
		"children": [],
		"title": "Beurteilung der Bildungschancen",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Alle Kinder erhalten die gleichen Bildungschancen.», Basel-Stadt",
		"lesehilfe": "10,1% der im Jahr 2019 Befragten sind sehr und 23,5% eher mit der Aussage einverstanden, dass alle Kinder die gleichen Bildungschancen erhalten. Der Anteil Befragter, welcher diese Aussage nicht beurteilt hat, ist im Vergleich zu den Vorjahren gestiegen.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung der Bildungschancen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09374",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.6",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-22T06:01:12",
		"id": 9374
	},
	{
		"template": "befragungen001",
		"data-id": 9376,
		"chart-id": 8461,
		"filter": "",
		"parentId": "8461",
		"children": [],
		"title": "Zufriedenheit mit dem Angebot der Kinderbetreuung",
		"subtitle": "«Wie zufrieden sind Sie mit dem Angebot zur Kinderbetreuung?», Basel-Stadt",
		"lesehilfe": "Insgesamt 39,5% zeigen sich 2019 sehr oder eher zufrieden mit dem Angebot der Kinderbetreuung. 10,3% sind damit unzufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Angebot der Kinderbetreuung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09376",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.8",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-04-12T07:59:10",
		"id": 9376
	},
	{
		"template": "befragungen001",
		"data-id": 9377,
		"chart-id": 9377,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit der Seniorenfreundlichkeit im Kanton Basel-Stadt",
		"subtitle": "«Wie seniorenfreundlich empfinden Sie den Kanton Basel-Stadt?», Basel-Stadt",
		"lesehilfe": "13,0% der 2019 befragten Personen empfinden den Kanton Basel-Stadt als sehr seniorenfreundlich, 56,5% als eher seniorenfreundlich. Mit 18,2% liegt der Anteil der Befragten, die den Kanton als nicht seniorenfreundlich empfinden, bei weniger als einem Fünftel. Gegenüber 2015 blieb dieser Anteil konstant.",
		"erlaeuterungen": "Seit 2011 wird alle vier Jahre im Kanton Basel-Stadt eine Bevölkerungsbefragung 55plus durchgeführt. Die Befragung richtet sich an Personen im Alter von mindestens 55 Jahren mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Befragung 55plus"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit der Seniorenfreundlichkeit im Kanton Basel-Stadt",
		"thema": "50 Befragungen",
		"unterthema": "Befragung 55 plus",
		"kuerzel": "I.50.4.09377",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.9",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-20T05:49:42",
		"id": 9377
	},
	{
		"template": "befragungen001",
		"data-id": 9378,
		"chart-id": 9029,
		"filter": "",
		"parentId": "9029",
		"children": [],
		"title": "Seniorinnen und Senioren werden von den jüngeren Generationen akzeptiert und integriert",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Seniorinnen und Senioren werden von den jüngeren Generationen akzeptiert und integriert.», Basel-Stadt",
		"lesehilfe": "51,1% der 2019 befragten Personen stimmen der Aussage zu, dass Seniorinnen und Senioren von der jüngeren Generation akzeptiert und integriert werden. 31,6% stimmen dieser Aussage nicht zu.",
		"erlaeuterungen": "Seit 2011 wird alle vier Jahre im Kanton Basel-Stadt eine Bevölkerungsbefragung 55plus durchgeführt. Die Befragung richtet sich an Personen im Alter von mindestens 55 Jahren mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Befragung 55plus"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Seniorinnen und Senioren werden von den jüngeren Generationen akzeptiert und integriert",
		"thema": "50 Befragungen",
		"unterthema": "Befragung 55 plus",
		"kuerzel": "I.50.4.09378",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.10",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-22T06:01:10",
		"id": 9378
	},
	{
		"template": "template001",
		"data-id": 9380,
		"chart-id": 9380,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zupendelnde Fachkräfte in Bildung, Gesundheit, Kultur aus der schweizerischen Agglomeration",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zupendelnde Fachkräfte in Bildung, Gesundheit, Kultur aus der schweizerischen Agglomeration",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.09380",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.3",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-20T06:09:53",
		"id": 9380
	},
	{
		"template": "template001",
		"data-id": 9383,
		"chart-id": 4133,
		"filter": "",
		"parentId": "4133",
		"children": [],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2009 ist der gesamte Wohnungsbestand leicht und stetig gestiegen. Am stärksten war das Wachstum bei den Fünf- bzw. Vierzimmerwohnungen (+11,8% bzw. +9,4% seit 2009). Am geringsten war die Zunahme bei den Einzimmerwohnungen (3,1%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09383",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.2",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-29T09:16:01",
		"id": 9383
	},
	{
		"template": "template001",
		"data-id": 9384,
		"chart-id": 4135,
		"filter": "",
		"parentId": "4135",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2020 wurde wiederum eine hohe Neubauproduktion verzeichnet. Auffallend ist insbesondere auch der stark positive Umbausaldo.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09384",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.3",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-29T09:16:02",
		"id": 9384
	},
	{
		"template": "befragungen001",
		"data-id": 9385,
		"chart-id": 4127,
		"filter": "",
		"parentId": "4127",
		"children": [],
		"title": "Zufriedenheit mit dem Wohnungsangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Wohnungsangebot?», Basel-Stadt",
		"lesehilfe": "17,9% der Befragten sind mit dem Wohnungsangebot sehr zufrieden und 34,8% eher zufrieden. Seit der ersten Bevölkerungsbefragung 2003 ist der Anteil der Zufriedenen bis 2011 stetig gewachsen, bevor 2015 ein Rückgang erfolgte. Gegenüber 2015 ist die Zufriedenheit der Befragten wieder gestiegen.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Wohnungsangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09385",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.4",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-06-22T06:08:21",
		"id": 9385
	},
	{
		"template": "template001",
		"data-id": 9386,
		"chart-id": 4149,
		"filter": "",
		"parentId": "4149",
		"children": [],
		"title": "Freiraumfläche und Anteil an der Gesamtfläche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2020 betrug der Anteil der Freiraumflächen an der gesamten Fläche des Kantons 2,42%. Die Freiraumflächen reduzierten sich aufgrund von Schulhauserweiterungen auf Kosten von Sportanlagen sowie der Umgestaltung der Voltamatte vorübergehend bis auf rund 83,9 Hektar im Jahr 2013. Die Öffnung des Schwarzparks für die Bevölkerung sorgte 2014 für einen Sprung auf rund 88,5 Hektar.",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden (Öffentliche Pärke und Rabatten im Strassenbereich werden detaillierter erfasst). Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Freiraumfläche und Anteil an der Gesamtfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.09386",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.5",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-01-13T01:34:42",
		"id": 9386
	},
	{
		"template": "befragungen001",
		"data-id": 9388,
		"chart-id": 4150,
		"filter": "",
		"parentId": "4150",
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2019",
		"lesehilfe": "85,9% der 2019 Befragten sind mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden. 2015 lag dieser Anteil bei 91,3%.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09388",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.7",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-09T11:52:36",
		"id": 9388
	},
	{
		"template": "line001",
		"data-id": 9389,
		"chart-id": 5793,
		"filter": "",
		"parentId": "5793",
		"children": [],
		"title": "Ökologischer Fussabdruck der Schweiz",
		"subtitle": "in globalen Hektaren pro Kopf",
		"lesehilfe": "Der ökologische Fussabdruck der Schweiz mass 2017 4,5 globale Hektaren pro Kopf, während die Biokapazität der Schweiz nur 1,0 globale Hektare betrug.",
		"erlaeuterungen": "Der ökologische Fussabdruck misst den Verbrauch natürlicher Ressourcen und drückt in globalen Hektaren die Fläche aus, die für die Produktion dieser Ressourcen notwendig wäre. Er zeigt auf, ob und in welchem Ausmass die Nutzung der Natur die regenerative Fähigkeit der Biosphäre (Biokapazität) übersteigt. Eine globale Hektare ist eine Hektare produktiver Fläche, welche eine Produktivität aufweist, die dem weltweiten Durchschnitt entspricht. Der ökologische Fussabdruck und die Biokapazität werden durch die Non-Profit Organisation \"Global Footprint Network\" für alle Länder weltweit berechnet. Aufgrund von Verbesserungen der Methodik und der berücksichtigten Eingangsgrössen für die Berechnung kann bei Aktualisierungen die gesamte Zeitreihe rückwirkend angepasst werden.",
		"quellenangabe": [
			"Global Footprint Network"
		],
		"externalLinks": [
			"<a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/nachhaltige-entwicklung/weitere-indikatoren-achhaltige-entwicklung/oekologischer-fussabdruck.html' target = '_blank'>Bundesamt für Statistik: Der ökologische Fussabdruck der Schweiz</a>",
			"Aktuelle Daten des <a href = 'http://data.footprintnetwork.org/#/countryTrends?cn=211&type=BCpc,EFCpc' target = '_blank'>Global Footprint Network</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Ökologischer Fussabdruck der Schweiz",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "I.02.1.09389",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.2",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-11-26T12:16:49",
		"id": 9389
	}
];