var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 9663,
		"chart-id": 5160,
		"filter": "",
		"parentId": "5160",
		"children": [],
		"title": "Nettoschuldenquote und Nettoschulden pro Kopf",
		"subtitle": "in Promille des BIP der Schweiz resp. in Franken, Basel-Stadt",
		"lesehilfe": "Die Nettoschuldenquote und die Nettoschulden pro Kopf sind seit dem Jahr 2000 zurückgegangen. 2021 liegen die Werte erstmals im negativen Bereich. Die Nettoschuldenquote beträgt -0,1 Promille des Schweizer Bruttoinlandprodukts. Die Nettoschulden pro Kopf betragen -295 Franken. Hauptverantwortlich dafür sind das Ausbleiben der erwarteten, pandemiebedingten Steuerausfälle, eine höhere Ausschüttung der Schweizerischen Nationalbank sowie weiterhin hohe Grundstückgewinn- und Handänderungssteuern. Der Kanton baute seine Nettoschulden 2021 vollständig ab und verfügt nun über ein Nettovermögen.",
		"erlaeuterungen": "Die Nettoschuldenquote des Kantons Basel-Stadt wird in Bezug auf das Schweizer Bruttoinlandprodukt berechnet.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoschuldenquote und Nettoschulden pro Kopf",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Volkseinkommen",
		"kuerzel": "I.04.1.09663",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "2",
		"stufe1": "Staatliches Handeln",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-09-03T08:04:58",
		"id": 9663
	},
	{
		"template": "line001",
		"data-id": 9672,
		"chart-id": 6900,
		"filter": "",
		"parentId": "6900",
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Mittelwert und Median des Reineinkommens pro Veranlagung bewegen sich relativ konstant. Im Jahr 2019 beträgt der Mittelwert rund 72 400 Franken (+10,1% seit 2010, +3,8% gegenüber 2018), der Median ca. 49 900 Franken (+3,8% seit 2010, +0,4% gegenüber 2018). Der Ertrag aus Einkommenssteuer 2019 beträgt 1,223 Mrd. Franken (+12,4% gegenüber 2010 und +6,2% gegenüber 2018).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09672",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "3",
		"stufe1": "Staatliches Handeln",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T08:20:15",
		"id": 9672
	},
	{
		"template": "stock001",
		"data-id": 9673,
		"chart-id": 4132,
		"filter": "",
		"parentId": "4132",
		"children": [],
		"title": "Bevölkerungsbestand am Jahresende",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Zwischen dem 31.12.2011 und dem 31.12.2021 nahm die Bevölkerung im Kanton Basel-Stadt von 192 304 auf 201 805 Personen zu.",
		"erlaeuterungen": "Angaben zur Erhebung der Bevölkerungszahlen: 1774-1847: Kantonale Volkszählungen; 1850-1900: Eidgenössische Volkszählungen; 1901-2011: Fortschreibung der kantonalen Bevölkerungsstatistik; ab 2012: Auswertungen aus dem kantonalen Einwohnerregister.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsbestand am Jahresende",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09673",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "1",
		"stufe1": "Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-27T08:46:05",
		"id": 9673
	},
	{
		"template": "template001",
		"data-id": 9674,
		"chart-id": 4299,
		"filter": "",
		"parentId": "4299",
		"children": [],
		"title": "CO<sub>2</sub>-Emissionen",
		"subtitle": "in Tonnen; Tonnen pro Einwohner (rechte Skala)",
		"lesehilfe": "Die aus dem Bruttoenergieverbrauch abgeleiteten CO<sub>2</sub>-Emissionen nahmen zwischen 2010 und 2018 von 910&nbsp;740 Tonnen auf 694&nbsp;507 Tonnen ab. Das entspricht einer Reduktion um 24% bzw. einem Rückgang von 4,7 Tonnen auf 3,5 Tonnen CO<sub>2</sub> pro Kopf.",
		"erlaeuterungen": "Der Indikator zeigt die Summe der aus den kantonalen Energieverbräuchen resultierenden CO<sub>2</sub>-Emissionen in die Atmosphäre. <br><br>Die CO<sub>2</sub>-Emissionen werden ausgehend vom Bruttoenergieverbrauch gemäss den kantonalen Energiestatistiken ermittelt. Zur Berechnung der Emissionen wird pro Energieträger der jährliche Bruttoenergieverbrauch mit dem entsprechenden CO<sub>2</sub>-Emissionsfaktor (gemäss Schweizerischem Treibhausgasinventar) multipliziert.<br><br>Es sind zur Hauptsache CO<sub>2</sub>-Emissionen berücksichtigt, welche bei der Verbrennung von fossilen Energieträgern (Brenn- und Treibstoffe) entstehen. Die Emissionen aus der energetischen Nutzung von Holz werden nicht ausgewiesen, da Holz als CO<sub>2</sub>-neutral gilt. Die Verbrennung von biogenem Material wird ebenso als CO<sub>2</sub>-neutral betrachtet, weshalb nur 50% des in der Kehrichtverwertungsanlage verbrannten Abfalls berücksichtigt wird. Auch der Klärschlamm wird als biogen taxiert; demzufolge bleiben die entsprechenden CO<sub>2</sub>-Emissionen ebenfalls unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'CO<sub>2</sub>-Emissionen pro Kopf' target = '_blank'><a href=https://www.bafu.admin.ch/bafu/de/home/themen/thema-klima/klima--daten--indikatoren-und-karten/klima--indikatoren/indikator-klima.pt.html/aHR0cHM6Ly93d3cuaW5kaWthdG9yZW4uYWRtaW4uY2gvUHVibG/ljL0FlbURldGFpbD9pbmQ9S0wwMDImbG5nPWRlJlN1Ymo9Tg%3d%3d.html target=_blank rel=nofollow>https://ww</a>",
			"<a href = 'Bundesamt für Umwelt' target = '_blank'><a href=https://www.bafu.admin.ch/bafu/de/home/themen/klima.html target=_blank rel=nofollow>https://www.bafu.admin.ch/bafu/de/home/themen/klima.html</a></a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-05-0501' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2</sub>-Emissionen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luftschadstoffe",
		"kuerzel": "I.02.5.09674",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "4",
		"stufe1": "Natürliche Lebensgrundlagen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": true,
		"aktualisierungsdatum": "2022-07-29T08:49:25",
		"id": 9674
	},
	{
		"template": "template001",
		"data-id": 9675,
		"chart-id": 6126,
		"filter": "",
		"parentId": "6126",
		"children": [],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2021",
		"lesehilfe": "Im Jahr 2021 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 97,9 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 7.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09675",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "5",
		"stufe1": "Wirtschaftliche Entfaltung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:10",
		"id": 9675
	},
	{
		"template": "line001",
		"data-id": 9676,
		"chart-id": 5901,
		"filter": "",
		"parentId": "5901",
		"children": [],
		"title": "Bevölkerungs- und Beschäftigtenentwicklung",
		"subtitle": "indexiert (Basis 2011 = 100), Basel-Stadt",
		"lesehilfe": "Die Wohnbevölkerung ist im Kanton Basel-Stadt zwischen 2011 und 2019 von 192 076 auf 200 407 gestiegen, was einem Anstieg von etwa 4,3% entspricht. Die Zahl der Beschäftigten stieg im gleichen Zeitraum um 5,1% von 183 183 auf 192 450.",
		"erlaeuterungen": "Es ist jeweils der Bevölkerungsbestand Ende Jahr abgebildet. Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungs- und Beschäftigtenentwicklung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09676",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "6",
		"stufe1": "Wirtschaftliche Entfaltung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-27T08:46:10",
		"id": 9676
	},
	{
		"template": "line001",
		"data-id": 9677,
		"chart-id": 6137,
		"filter": "",
		"parentId": "6137",
		"children": [],
		"title": "Arbeitslosenquote im Jahresmittel nach Altersgruppe",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Arbeitslosenquote in Basel-Stadt ist von 3,0% im Jahresdurchschnitt 2019 auf 3,8% im Jahr 2020 gestiegen. Die Jugendarbeitslosenquote (Personen zwischen 15 und 24 Jahren) erhöhte sich von 3,2% 2019 auf 4,1% 2020. Die Arbeitslosenquote der Personen über 50 Jahre nahm 2020 auf 3,1% zu und lag damit weiterhin unterhalb der Durchschnittsquote.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl Arbeitsloser geteilt durch die Anzahl Erwerbspersonen mal 100.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote im Jahresmittel nach Altersgruppe",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.09677",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "7",
		"stufe1": "Wirtschaftliche Entfaltung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:25:03",
		"id": 9677
	},
	{
		"template": "line001",
		"data-id": 9678,
		"chart-id": 6036,
		"filter": "",
		"parentId": "9371",
		"children": [],
		"title": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Gini-Koeffizient des Reineinkommens nimmt im Zeitverlauf insgesamt leicht zu, jener des Reinvermögens zeigt sich auf höherem Niveau etwas konstanter. Für das Reinvermögen liegt für das Jahr 2000 aufgrund von Gesetzesänderungen kein Wert vor.",
		"erlaeuterungen": "Der Gini-Koeffizient ist ein Mass für die Gleichmässigkeit einer Verteilung (hier des Reineinkommens und des Reinvermögens). Er kann Werte zwischen 0 (alle besitzen gleich viel) und 1 (einer besitzt alles) annehmen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09678",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "8",
		"stufe1": "Gesellschaftlicher Zusammenhalt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-26T08:26:33",
		"id": 9678
	},
	{
		"template": "line001",
		"data-id": 9679,
		"chart-id": 7710,
		"filter": "",
		"parentId": "7710",
		"children": [],
		"title": "Verlorene potentielle Lebensjahre",
		"subtitle": "je 100 000 Einwohner, Basel-Stadt",
		"lesehilfe": "Seit 1995 sinken die verlorenen potentiellen Lebensjahre (VPL) im Kanton Basel-Stadt. 2019 waren es bei den Männern 4&nbsp;245 VPL und bei den Frauen 2&nbsp;663.",
		"erlaeuterungen": "Anzahl verlorene potentielle Lebensjahre (VPL) je 100&nbsp;000 Einwohner (ständige Wohnbevölkerung) für Todesfälle zwischen der Geburt und 75 Jahren. Zur Berechnung der VPL werden die bis zu einer festgelegten Altersgrenze verbleibenden Lebensjahre pro Altersgruppe addiert und gemäss der Altersstruktur gewichtet. Als Altersgrenze wurde hier 75 Jahre gewählt, aus Gründen der Vergleichbarkeit beispielsweise mit dem Indikator des Schweizerischen Gesundheitsobservatoriums (Obsan). Ein Todesfall im Alter von 65 Jahren entspricht damit 10 potentiell verlorenen Lebensjahren. Todesfälle nach der Vollendung des 75. Lebensjahres fliessen nicht in die Berechnung ein. Damit die VPL zwischen Männern und Frauen sowie den verschiedenen Jahren vergleichbar sind, wurden sie nach der Altersstruktur der Basler Bevölkerung im Jahr 2010 standardisiert.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Verlorene potentielle Lebensjahre",
		"thema": "14 Gesundheit",
		"unterthema": "Sterblichkeit",
		"kuerzel": "I.14.3.09679",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "9",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-11-24T08:43:32",
		"id": 9679
	},
	{
		"template": "line001",
		"data-id": 9680,
		"chart-id": 9375,
		"filter": "",
		"parentId": "9375",
		"children": [],
		"title": "Entwicklung von Krankenkassenprämien und Einkommen",
		"subtitle": "indexiert (2010 = 100), Basel-Stadt",
		"lesehilfe": "Im Jahr 2018 lag der Index (Basis 2010) der Medianprämien bei 135,2. Der Index für den Median des Reinkommens bei 103,3.",
		"erlaeuterungen": "Medianprämie: Medianwert der Standardprämien aller Versicherer. Standardprämie: Monatsprämie der Obligatorischen Krankenpflegeversicherung gemäss dem Bundesgesetz über die Krankenversicherung (KVG) für Erwachsene, Franchise Fr. 300, mit Unfalldeckung, ohne besondere Versicherungsmodelle mit eingeschränkter Arztwahl gemäss Art. 62 KVG. <br>Median Reineinkommen: Medianwert des Reineinkommens aller Steuerveranlagungen im Kanton Basel-Stadt.",
		"quellenangabe": [
			"Bundesamt für Gesundheit (BAG)",
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung von Krankenkassenprämien und Einkommen",
		"thema": "14 Gesundheit",
		"unterthema": "Prävention, Praxen, Rettung",
		"kuerzel": "I.14.4.09680",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "10",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:48",
		"id": 9680
	},
	{
		"template": "line001",
		"data-id": 9681,
		"chart-id": 9372,
		"filter": "",
		"parentId": "9372",
		"children": [],
		"title": "Anzahl Fälle in der Sozialhilfe und Sozialhilfequote",
		"subtitle": "Kanton Basel-Stadt",
		"lesehilfe": "Die kantonale Sozialhilfequote sinkt seit dem Jahr 2017 kontinuierlich. 2020 liegt sie bei 6,3%. Im Verlaufe des Jahres 2020 wurden insgesamt 12 793 Personen finanziell durch die Sozialhilfe unterstützt.",
		"erlaeuterungen": "Die Sozialhilfequote wird als Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Bevölkerungsstand Ende Jahr berechnet. Bei der Berechnung der Soziahilfequote ab 2015 wird auch die Bevölkerung an administrativen Meldeadressen (Personen in Kollektivhaushalten ohne eigene Wohnadresse) berücksichtigt. Unter Sozialhilfebeziehenden sind alle Personen erfasst, die im Verlauf eines Jahres mindestens eine bedarfsabhängige Sozialhilfeleistung erhalten haben. Die Dossiertypen Asyl und Flüchtling sind ebenfalls berücksichtigt. Asylsuchende mit Nichteintretens- oder Negativentscheid (NEE-NE-Dossiers) werden aus den Auswertungen ausgeschlossen, weil diese Personen nicht Sozialhilfe, sondern nur Nothilfe erhalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Fälle in der Sozialhilfe und Sozialhilfequote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.09681",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "11",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:24:49",
		"id": 9681
	},
	{
		"template": "template001",
		"data-id": 9682,
		"chart-id": 4866,
		"filter": "",
		"parentId": "4866",
		"children": [],
		"title": "Angezeigte Straftaten betreffend Strafgesetzbuch",
		"subtitle": "pro 1000 Einwohner, Basel-Stadt",
		"lesehilfe": "Im Jahr 2021 wurden pro 1000 Einwohner 111,9 Anzeigen gemäss Strafgesetzbuch (StGB) erstattet.",
		"erlaeuterungen": "Anzeigen gemäss Strafgesetzbuch (StGB), bezogen auf die Basler Wohnbevölkerung am Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bundesamt für Statistik (BFS), Polizeiliche Kriminalstatistik (PKS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angezeigte Straftaten betreffend Strafgesetzbuch",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.09682",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "12",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-10T02:29:55",
		"id": 9682
	},
	{
		"template": "line001",
		"data-id": 9683,
		"chart-id": 6055,
		"filter": "",
		"parentId": "6055",
		"children": [],
		"title": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl angebotener Plätze für die Tagesbetreuung hat in den vergangenen Jahren ein stetiges Wachstum erfahren. Im Oktober 2021 liegt die Platzzahl bei 4 409. Auch die Tagesstrukturen wurden stetig ausgebaut. 2021 bieten die Frühhorte Platz für 568 Kinder, die Mittagsmodule  3 625 und die Nachmittagsmodule 3 227 Plätze.",
		"erlaeuterungen": "Tagesstrukturen: Stichwoche im September.  Frühhorte werden an einigen Primarschulstandorten angeboten. Die Mittags- und Nachmittagsmodule werden einerseits von schuleigenen und andererseits schulexternen Tagesstrukturen bereitgestellt. In den Sekundarschulen bestehen ebenfalls Verpflegungsangebote und die Möglichkeit, sich nachmittags beaufsichtigt in den Schulräumlichkeiten aufzuhalten. Da bei den Sekundarschulen keine Anmeldepflicht besteht, existiert keine eindeutige Platzzahl. Die Anzahl Tagesstrukturplätze berücksichtigt dieses Angebot daher nicht.<br>Tagesbetreuung: Plätze in Tagesheimen und Tagesfamilien. Stichwoche im Oktober.",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesbetreuung",
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09683",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "14",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-05-23T07:58:50",
		"id": 9683
	},
	{
		"template": "template001",
		"data-id": 9684,
		"chart-id": 7579,
		"filter": "",
		"parentId": "7579",
		"children": [],
		"title": "Nettoproduktion an Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettoproduktion von Wohnungen beträgt 2021 977 Einheiten. Davon  stammen 851 aus Neu- und 222 aus Umbauten. Durch Abbrüche gehen 96 Wohnungen verloren. 2022 wird eine Nettoproduktion von rund 800 Wohnungen prognostiziert.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoproduktion an Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09684",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "15",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-25T08:16:17",
		"id": 9684
	},
	{
		"template": "line001",
		"data-id": 9685,
		"chart-id": 5813,
		"filter": "",
		"parentId": "5813",
		"children": [],
		"title": "Leerwohnungsquote",
		"subtitle": "in Prozent, Basel-Stadt",
		"lesehilfe": "Die Leerwohnungsquote sank seit 2006 kontinuierlich und erreichte 2014 mit 0,2% den tiefsten Wert. Danach stieg sie und erreichte 2022 eine Quote von 1,2%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09685",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "16",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-13T05:19:49",
		"id": 9685
	},
	{
		"template": "line001",
		"data-id": 9686,
		"chart-id": 5196,
		"filter": "",
		"parentId": "5196",
		"children": [],
		"title": "Mietpreisindex Basel-Stadt",
		"subtitle": "Indexwert (Basis 2000 = 100)",
		"lesehilfe": "Der Mietpreisindex zeigt insgesamt eine steigende Entwicklung von 97,2 Punkten im Jahr 1995 auf den aktuellen Wert von 129,8 im November 2021.",
		"erlaeuterungen": "Mietpreisindex: Geschichtete Zufallsstichprobe, die 5% der Miet- und Genossenschaftswohnungen mit 1 bis 6 Zimmern umfasst, welche dauerhaft zu Wohnzwecken vermietet werden. Es wird der Wert im November des jeweiligen Jahres ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisindex Basel-Stadt",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.09686",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "17",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_017",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-02-04T03:05:48",
		"id": 9686
	},
	{
		"template": "template001",
		"data-id": 9687,
		"chart-id": 4319,
		"filter": "",
		"parentId": "4319",
		"children": [],
		"title": "Verkehrsleistungsindex",
		"subtitle": "in Indexwert (Basis 2010 = 100)",
		"lesehilfe": "Die Fahrleistung des motorisierten Individualverkehrs (MIV Total) auf Kantonsgebiet liegt 2018 um 1% tiefer, diejenige des Veloverkehrs um 28,7% höher als im Jahr 2010. Der Wert für Fussgänger stieg von 2013 bis 2014 um 7 Prozentpunkte, sank dann aber wieder und liegt 2018 bei einem Indexwert von 102,4.",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Die Veränderung gegenüber dem Referenzjahr 2010 wird in Prozent dargestellt (indexiert, 2010 = 100). <br><br>Der Verkehrsleistungsindex basiert auf den an automatischen Zählstellen erfassten Verkehrsaufkommen der einzelnen Kategorien, aus welchen mit Modellen die Verkehrsleistung für den gesamten Kanton abgeleitet werden. Für den Auto- und Veloverkehr wird jede Zählstelle auf Basis des Gesamtverkehrsmodells der Region Basel gewichtet. Die Zählstellen des Fussverkehrs werden über den «Mikrozensus Verkehr» gewichtet.<br><br>Autoverkehr:<br>Der Index für den motorisierten Individualverkehr (MIV) berechnet sich anhand von rund 40 Dauerzählstellen des Kantons Basel-Stadt, des Kantons Basel-Landschaft und des Bundesamts für Strassen. Er umfasst die Verkehrsleistung aller Motorfahrzeuge auf baselstädtischem Kantonsgebiet (inkl. Lastwagen, Lieferwagen, Motorrädern), aber ohne Linienbusse, Motorfahrräder und E-Bikes. Der MIV Total entspricht der Verkehrsleistung auf allen Strassen des Kantonsgebiets, der MIV Stadtstrassennetz derjenigen ohne die Autobahnen.<br><br>Veloverkehr:<br>Der Index für den Veloverkehr wird auf Basis von rund 20 Zählstellen des Kantons Basel-Stadt berechnet. Der Einfluss des Wetters auf den Veloverkehr wird mittels eines Modells herausgerechnet.<br><br>Fussverkehr:<br>Der Index für den Fussverkehr basiert auf rund 18 Zählstellen. Die Daten werden erst seit dem Jahr 2013 erhoben. <br><br>Öffentlicher Verkehr:<br>Der Index des öffentlichen Verkehrs basiert auf den Verkehrsleistungen der Tram-, Bus- und S-Bahn-Linien auf dem Gebiet des Kantons Basel-Stadt. <br><br>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'Verkehrspolitisches Leitbild Kanton Basel-Stadt' target = '_blank'><a href=https://www.mobilitaet.bs.ch/gesamtverkehr/mobilitaetsstrategie/verkehrspolitische-grunds-tze.html target=_blank rel=nofollow>https://www.mobilitaet.bs.ch/gesamtverkehr/mobilitaetsstrategie/verkehrspolitische-grunds-tze.html</a></a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-05-0501' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.09687",
		"kennzahlenset": "RR_KPI",
		"kuerzelKunde": "18",
		"stufe1": "Grundbedürfnisse und Wohlergehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_018",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": true,
		"aktualisierungsdatum": "2022-07-29T08:51:26",
		"id": 9687
	}
];