var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 12520,
		"chart-id": 12520,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Angebot und Nutzung des Mittagsmoduls der Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebot und Nutzung des Mittagsmoduls der Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.12520",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-05T02:24:12",
		"id": 12520
	},
	{
		"template": "template001",
		"data-id": 12521,
		"chart-id": 12521,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Angebot und Nutzung der Nachmittagsmodule der Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebot und Nutzung der Nachmittagsmodule der Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.12521",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-05T02:24:25",
		"id": 12521
	},
	{
		"template": "template001",
		"data-id": 4152,
		"chart-id": 4152,
		"filter": "",
		"parentId": null,
		"children": [
			9292
		],
		"title": "Haushalte mit Familienmietzinsbeiträgen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der mit Familienmietzinsbeiträgen unterstützten Haushalte geht seit 2019 nach zuvor kontinuierlichem Anstieg zurück. Ende 2022 beziehen 2 151 Haushalte Familienmietzinsbeiträge. Dies entspricht 2,1% aller Haushalte im Kanton Basel-Stadt.",
		"erlaeuterungen": "Die Familienmietzinsbeitragsquote errechnet sich als Quotient der Anzahl Haushalte mit Mietzinsbeiträgen an der Gesamtzahl Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per 31. Dezember.<br>Anspruch auf Familienmietzinsbeiträge können Familien in bescheidenen wirtschaftlichen Verhältnissen geltend machen. Es muss mindestens ein minderjähriges oder sich in Erstausbildung befindendes Kind unter 25 Jahren im gleichen Haushalt leben. Grundvoraussetzung für den Bezug ist der Wohnsitz im Kanton Basel-Stadt, wobei das Gesetz eine Wohnsitzdauer von 5 Jahren ohne Unterbruch verlangt. Es genügt, wenn eine Person bzw. ein Elternteil diese Bedingung erfüllt.<br>Die Höhe des Zuschusses ist abhängig von der Anzahl Personen, der Anzahl Zimmer, dem Mietzins sowie dem Jahreseinkommen und Vermögen der wirtschaftlichen Haushaltseinheit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Haushalte mit Familienmietzinsbeiträgen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.4152",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-07",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:12",
		"id": 4152
	},
	{
		"template": "line001",
		"data-id": 9289,
		"chart-id": 9289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote nach Gemeinde",
		"subtitle": "",
		"lesehilfe": "Die kantonale Sozialhilfequote liegt 2022 bei 5,0%. Sie sinkt seit dem Jahr 2017 kontinuierlich. Die Stadt Basel weist 2022 eine Quote von 5,3% aus, Riehen 2,7% und Bettingen 1,7%.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Bevölkerungsstand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt. <br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst. Bis 2017 galt für die Anzahl Beziehender folgende Definition: Alle Personen mit Dossiertyp «Sozialhilfefall», «Asyl» oder «Flüchtling» die im Verlauf eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Auf die Werte von Riehen und Bettingen hat diese Umstellung keinen Einfluss.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Sozialhilfequote nach Gemeinde",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-03",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-25T09:11:17",
		"id": 9289
	},
	{
		"template": "line001",
		"data-id": 9291,
		"chart-id": 9291,
		"filter": "",
		"parentId": "6055",
		"children": [],
		"title": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl angebotener Plätze für die Tagesbetreuung hat in den vergangenen Jahren ein stetiges Wachstum erfahren. Im Oktober 2022 liegt die Platzzahl bei 4 398. Auch die Tagesstrukturen wurden stetig ausgebaut. 2022 bieten die Frühhorte Platz für 656 Kinder, die Mittagsmodule  3 800 und die Nachmittagsmodule 3 450 Plätze.",
		"erlaeuterungen": "Tagesstrukturen: Stichwoche im September. Frühhorte werden an einigen Primarschulstandorten angeboten. Die Mittags- und Nachmittagsmodule werden einerseits von schuleigenen und andererseits schulexternen Tagesstrukturen bereitgestellt. In den Sekundarschulen bestehen ebenfalls Verpflegungsangebote und die Möglichkeit, sich nachmittags beaufsichtigt in den Schulräumlichkeiten aufzuhalten. Da bei den Sekundarschulen keine Anmeldepflicht besteht, existiert keine eindeutige Platzzahl. Die Anzahl Tagesstrukturplätze berücksichtigt dieses Angebot daher nicht.<br>Tagesbetreuung: Plätze in Kindertagesstätten und Tagesfamilien. Stichwoche im Oktober.",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesbetreuung",
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09291",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-08",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:12",
		"id": 9291
	},
	{
		"template": "line001",
		"data-id": 9294,
		"chart-id": 9294,
		"filter": "",
		"parentId": null,
		"children": [
			9934
		],
		"title": "Beziehende von Prämienverbilligung",
		"subtitle": "inkl. Beziehende von Sozialhilfe und Ergänzungsleistungen, Basel-Stadt",
		"lesehilfe": "Mit 51 711 Beziehenden erhält Ende 2022 ein Viertel aller in Basel-Stadt wohnhaften Personen Prämienverbilligung.",
		"erlaeuterungen": "Bestand per Ende des Jahres. PV: Prämienverbilligung, SH: Sozialhilfe, EL: Ergänzungsleistungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Prämienverbilligung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beziehende von Prämienverbilligung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09294",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-06",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-04T11:56:28",
		"id": 9294
	},
	{
		"template": "line001",
		"data-id": 9295,
		"chart-id": 9295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote nach Altersgruppe",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Minderjährige weisen 2022 mit 8,5% die höchste Sozialhilfequote im Kanton auf. Mit 4,8% ist die Sozialhilfequote der 26- bis 35-Jährigen die tiefste aller Altersgruppen im erwerbsfähigen Alter.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als 5 bzw. 7 Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialhilfequote nach Altersgruppe",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09295",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-04",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-25T07:08:40",
		"id": 9295
	},
	{
		"template": "line001",
		"data-id": 9298,
		"chart-id": 9298,
		"filter": "",
		"parentId": "8250",
		"children": [],
		"title": "Beziehende von Ergänzungsleistungen und Beihilfen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 liegt die Anzahl Personen mit Ergänzungsleistungen (EL) zur AHV bei 8 741, jene mit EL zur IV bei 6 754. Beihilfen werden an 5 357 (AHV) respektive 4 341 (IV) Personen ausbezahlt.",
		"erlaeuterungen": "Referenzperiode: Dezember.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beziehende von Ergänzungsleistungen und Beihilfen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.09298",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-05",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:11",
		"id": 9298
	},
	{
		"template": "template001",
		"data-id": 9915,
		"chart-id": 9915,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Stipendien nach Ausbildungstyp",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Verlauf des Jahres 2022 werden insgesamt 1 953 Stipendien vergeben. Davon gehen 29% an Personen in Gymnasien und anderen<br>Schulen für Allgemeinbildung. 37% der Begünstigten befinden sich<br>in der Beruflichen Grundbildung und 33% absolvieren eine Ausbildung auf Tertiärstufe. 8 Stipendien gehen an Personen in Weiterbildungen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Amt für Ausbildungsbeiträge Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Stipendien nach Ausbildungstyp",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09915",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:13:23",
		"id": 9915
	},
	{
		"template": "template001",
		"data-id": 9916,
		"chart-id": 9916,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl KÜG nach Leistung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von den insgesamt 3 316  KÜG per Ende 2023 entfallen 622 auf die Ambulante Wohnbegleitung.",
		"erlaeuterungen": "Eine Person kann mehrere Kostenübernahmegarantien (KÜG) erhalten, beispielsweise für Ambulante Wohnbegleitung und Begleitete Arbeit.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Behindertenhilfe"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl KÜG nach Leistung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09916",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:15:01",
		"id": 9916
	},
	{
		"template": "template001",
		"data-id": 9917,
		"chart-id": 9917,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Personen mit KÜG",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2 254  Personen werden per Ende 2023 mit mindestens einer KÜG unterstützt.",
		"erlaeuterungen": "Eine Person kann mehrere Kostenübernahmegarantien (KÜG) erhalten, beispielsweise für Ambulante Wohnbegleitung und Begleitete Arbeit.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Behindertenhilfe"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Personen mit KÜG",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09917",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:15:24",
		"id": 9917
	},
	{
		"parentId": 8250,
		"children": [],
		"template": "line001",
		"title": "Beziehende von Ergänzungsleistungen und Beihilfen",
		"subtitle": "Basel-Stadt",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.3.09918",
		"kuerzelKunde": "",
		"description": "Beziehende von Ergänzungsleistungen und Beihilfen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2023-05-22T14:05:10.1010",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "2022 liegt die Anzahl Personen mit Ergänzungsleistungen (EL) zur AHV bei 8 741, jene mit EL zur IV bei 6 754. Beihilfen werden an 5 357 (AHV) respektive 4 341 (IV) Personen ausbezahlt.",
		"erlaeuterungen": "Referenzperiode: Dezember.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9918,
		"chart-id": 8250,
		"filter": "",
		"id": 9918
	},
	{
		"template": "line001",
		"data-id": 9919,
		"chart-id": 9919,
		"filter": "",
		"parentId": null,
		"children": [
			10031
		],
		"title": "Anteil Beziehende von EL und Beihilfen an allen Beziehenden einer AHV- oder IV-Rente per Ende Jahr",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "69% der Personen mit IV erhielten zum Jahresende 2022 Ergänzungsleistungen (EL), 41% werden mittels Beihilfen zur IV unterstützt. Bei den Personen mit AHV<br>liegen diese Anteile bei 21% bzw. 13%.",
		"erlaeuterungen": "Anteil AHV-/IV-Beziehende mit Ergänzungsleistungen (EL) an allen AHV-/IV-Rentnern per Ende Jahr.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen",
			"Bundesamt für Sozialversicherungen (BSV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Beziehende von EL und Beihilfen an allen Beziehenden einer AHV- oder IV-Rente per Ende Jahr",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09919",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-11-13T09:13:27",
		"id": 9919
	},
	{
		"template": "line001",
		"data-id": 9920,
		"chart-id": 9920,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietverhältnisse mit Familienmietzinsbeiträgen und jährliche Durchschnittsbeiträge in Franken",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der Mietverhältnisse mit Familienmietzinsbeiträgen (FAMI) sinkt im zweiten Jahr in Folge. Per Ende des Jahres 2023 werden 2 190 Mietverhältnisse unterstützt. Der jährliche Durchschnittsbeitrag pro unterstütztem Haushalt liegt 2023 bei 5 435 Franken.",
		"erlaeuterungen": "Bestand per Ende des Jahres.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Prämienverbilligungen und Familienmietzinsbeiträge"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietverhältnisse mit Familienmietzinsbeiträgen und jährliche Durchschnittsbeiträge in Franken",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09920",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:16:51",
		"id": 9920
	},
	{
		"parentId": 4152,
		"children": [],
		"template": "template001",
		"title": "Haushalte mit Familienmietzinsbeiträgen",
		"subtitle": "Basel-Stadt",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.2.09921",
		"kuerzelKunde": "",
		"description": "Haushalte mit Familienmietzinsbeiträgen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2023-05-22T14:05:12.1212",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Anzahl der mit Familienmietzinsbeiträgen unterstützten Haushalte geht seit 2019 nach zuvor kontinuierlichem Anstieg zurück. Ende 2022 beziehen 2 151 Haushalte Familienmietzinsbeiträge. Dies entspricht 2,1% aller Haushalte im Kanton Basel-Stadt.",
		"erlaeuterungen": "Die Familienmietzinsbeitragsquote errechnet sich als Quotient der Anzahl Haushalte mit Mietzinsbeiträgen an der Gesamtzahl Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per 31. Dezember.<br>Anspruch auf Familienmietzinsbeiträge können Familien in bescheidenen wirtschaftlichen Verhältnissen geltend machen. Es muss mindestens ein minderjähriges oder sich in Erstausbildung befindendes Kind unter 25 Jahren im gleichen Haushalt leben. Grundvoraussetzung für den Bezug ist der Wohnsitz im Kanton Basel-Stadt, wobei das Gesetz eine Wohnsitzdauer von 5 Jahren ohne Unterbruch verlangt. Es genügt, wenn eine Person bzw. ein Elternteil diese Bedingung erfüllt.<br>Die Höhe des Zuschusses ist abhängig von der Anzahl Personen, der Anzahl Zimmer, dem Mietzins sowie dem Jahreseinkommen und Vermögen der wirtschaftlichen Haushaltseinheit.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Basler Informationssystem Sozialleistungen (BISS)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9921,
		"chart-id": 4152,
		"filter": "",
		"id": 9921
	},
	{
		"template": "template001",
		"data-id": 9922,
		"chart-id": 9922,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Übernachtungen in den Notschlafstellen nach Geschlecht",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2023 werden insgesamt 18 393 Übernachtungen in den Notschlafstellen gezählt. 4 254 entfallen auf Frauen, 14 139 auf Männer.",
		"erlaeuterungen": "Der Kanton Basel-Stadt betreibt zwei Notschlafstellen. Die Notschlafstelle für Frauen bot bis zum Jahr 2023 maximal 28 Betten an, diejenige für Männer maximal 75 Plätze. Während der COVID-19-Pandemie der Jahre 2020 bis 2022 war die Anzahl der Plätze teilweise eingeschränkt.",
		"quellenangabe": [
			"Sozialhilfe des Kantons Basel-Stadt, Wohnen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Übernachtungen in den Notschlafstellen nach Geschlecht",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Notwohnen",
		"kuerzel": "I.13.3.09922",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:23:32",
		"id": 9922
	},
	{
		"template": "line001",
		"data-id": 9923,
		"chart-id": 9923,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Auslastungsquote der Notschlafstellen nach Geschlecht",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Bei der Notschlafstelle für Frauen liegt die Auslastung im Jahr 2023 bei 42%, bei der Notschlafstelle für Männer bei 52%. Die Auslastung fällt gegenüber 2022 bei beiden Geschlechtern höher aus.",
		"erlaeuterungen": "Der Kanton Basel-Stadt betreibt zwei Notschlafstellen. Die Notschlafstelle für Frauen bot bis zum Jahr 2023 maximal 28 Betten an, diejenige für Männer maximal 75 Plätze. Während der COVID-19-Pandemie der Jahre 2020 bis 2022 war die Anzahl der Plätze teilweise eingeschränkt. Die jährliche Auslastungsquote beschreibt das Verhältnis des Totals an Übernachtungen während eines Jahres und der Anzahl der maximal möglichen Übernachtungen im entsprechenden Jahr.",
		"quellenangabe": [
			"Sozialhilfe des Kantons Basel-Stadt, Wohnen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Auslastungsquote der Notschlafstellen nach Geschlecht",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Notwohnen",
		"kuerzel": "I.13.3.09923",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:23:52",
		"id": 9923
	},
	{
		"template": "template001",
		"data-id": 9924,
		"chart-id": 4154,
		"filter": "",
		"parentId": "4154",
		"children": [],
		"title": "Bestand an Notwohnungen und ihre Belegung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die wenigen Notwohnungen – 2022 machten sie 0,17% des Wohnungsbestandes aus – waren immer zu mindestens 86% belegt. In den Jahren 2013, 2014 und 2021 betrug die Belegung sogar mehr als 95%. Durch Aufstockungen bestehender Blockrandsiedlungen und Erweiterung des Portfolios konnte das Angebot bis 2022 um knapp 100 Logis erhöht werden.",
		"erlaeuterungen": "Belegung Ende Jahr gemäss Mietverträgen der Sozialhilfe.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfe Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bestand an Notwohnungen und ihre Belegung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Notwohnen",
		"kuerzel": "I.13.3.09924",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-07T08:10:27",
		"id": 9924
	},
	{
		"parentId": 9289,
		"children": [],
		"template": "line001",
		"title": "Sozialhilfequote nach Gemeinde",
		"subtitle": "",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.3.09925",
		"kuerzelKunde": "",
		"description": "Sozialhilfequote nach Gemeinde",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"aktualisierungsdatum": "2023-05-25T09:11:17.1717",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die kantonale Sozialhilfequote liegt 2022 bei 5,0%. Sie sinkt seit dem Jahr 2017 kontinuierlich. Die Stadt Basel weist 2022 eine Quote von 5,3% aus, Riehen 2,7% und Bettingen 1,7%.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Bevölkerungsstand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt. <br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst. Bis 2017 galt für die Anzahl Beziehender folgende Definition: Alle Personen mit Dossiertyp «Sozialhilfefall», «Asyl» oder «Flüchtling» die im Verlauf eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Auf die Werte von Riehen und Bettingen hat diese Umstellung keinen Einfluss.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9925,
		"chart-id": 9289,
		"filter": "",
		"id": 9925
	},
	{
		"template": "template001",
		"data-id": 9926,
		"chart-id": 9926,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettounterstützung I der Sozialhilfe",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettounterstützung I liegt 2022 mit insgesamt 108,6 Mio. Franken so tief wie noch nie im Verlaufe der vergangenen 10 Jahre. Der Anteil von Riehen und  Bettingen liegt 2022 bei 4,5 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Sozialhilfe Stadt Basel",
			"Sozialhilfe Riehen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettounterstützung I der Sozialhilfe",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.09926",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:26:27",
		"id": 9926
	},
	{
		"template": "line001",
		"data-id": 9927,
		"chart-id": 9927,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Zahlfälle und Personen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Verlaufe des Jahres 2022 werden insgesamt 9 412 Personen in 6 380 Dossiers finanziell unterstützt. Davon fallen 619 Personen bzw. 385 Dossiers in den Aufgabenbereich der Sozialhilfe Riehen",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Zahlfälle und Personen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.09927",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:26:55",
		"id": 9927
	},
	{
		"parentId": 6055,
		"children": [],
		"template": "line001",
		"title": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.2.09929",
		"kuerzelKunde": "",
		"description": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2023-05-22T14:05:17.1717",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Anzahl angebotener Plätze für die Tagesbetreuung hat in den vergangenen Jahren ein stetiges Wachstum erfahren. Im Oktober 2022 liegt die Platzzahl bei 4 398. Auch die Tagesstrukturen wurden stetig ausgebaut. 2022 bieten die Frühhorte Platz für 656 Kinder, die Mittagsmodule  3 800 und die Nachmittagsmodule 3 450 Plätze.",
		"erlaeuterungen": "Tagesstrukturen: Stichwoche im September. Frühhorte werden an einigen Primarschulstandorten angeboten. Die Mittags- und Nachmittagsmodule werden einerseits von schuleigenen und andererseits schulexternen Tagesstrukturen bereitgestellt. In den Sekundarschulen bestehen ebenfalls Verpflegungsangebote und die Möglichkeit, sich nachmittags beaufsichtigt in den Schulräumlichkeiten aufzuhalten. Da bei den Sekundarschulen keine Anmeldepflicht besteht, existiert keine eindeutige Platzzahl. Die Anzahl Tagesstrukturplätze berücksichtigt dieses Angebot daher nicht.<br>Tagesbetreuung: Plätze in Kindertagesstätten und Tagesfamilien. Stichwoche im Oktober.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesbetreuung",
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9929,
		"chart-id": 6055,
		"filter": "",
		"id": 9929
	},
	{
		"parentId": null,
		"children": [],
		"template": "template001",
		"title": "Anzahl Tagesferien besuchende Schülerinnen und Schüler sowie gebuchte Ferientage für Ferienbetreuung an Schulen",
		"subtitle": "",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.2.09930",
		"kuerzelKunde": "",
		"description": "Anzahl Tagesferien besuchende Schülerinnen und Schüler sowie gebuchte Ferientage für Ferienbetreuung an Schulen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2023-09-08T09:28:23.2323",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Insgesamt 3 012 Schülerinnen und Schüler nutzen im Verlaufe des Jahres 2022 die Tagesferien. Dies entspricht durchschnittlich 290 Angemeldeten pro Ferienwoche. Das ist der höchste Wert im Beobachtungszeitraum. Die tageweise Ferienbetreuung an den Schulen wird im Berichtsjahr 897 mal gebucht, was durchschnittlich 57 Kindern pro Ferientag entspricht.",
		"erlaeuterungen": "Das Tagesferienangebot steht an 13 Wochen pro Jahr zur Verfügung. Im Jahr 2020 wurden die Tagesferien aufgrund der Schulschliessungen im Rahmen der Massnahmen zur Bekämpfung der COVID-19 Pandemie lediglich an 11 Wochen angeboten.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9930,
		"chart-id": 9930,
		"filter": "",
		"id": 9930
	},
	{
		"template": "template001",
		"data-id": 9932,
		"chart-id": 9932,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beziehende von Überbrückungsleistungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beziehende von Überbrückungsleistungen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09932",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:28:53",
		"id": 9932
	},
	{
		"template": "template001",
		"data-id": 9933,
		"chart-id": 9933,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fälle der Alimentenhilfe nach Fallart",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2023 werden 1 140 Fälle geführt. Davon werden in 591 Fällen Alimente bevorschusst, während in 549 Fällen nur das Inkasso durchgeführt wird. Die Gesamtzahl der Fälle der Alimentenhilfe ist im Beobachtungszeitraum rückläufig, steigt 2023 gegenüber dem Vorjahr jedoch an. Dies ist auf einen Ansteig bei den reinen Inkassofällen zurückzuführen.",
		"erlaeuterungen": "Bestand per Ende des Jahres. Ein Fall umfasst eine Mutter oder einen Vater mit einem oder mehreren Kindern mit Anrecht auf Alimentenbevorschussung. Bei reinen Inkassofällen führt die Alimentenhilfe das Inkasso durch, leistet aber keine Bevorschussung.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Alimentenhilfe"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fälle der Alimentenhilfe nach Fallart",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09933",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-09-08T09:29:41",
		"id": 9933
	},
	{
		"parentId": 9294,
		"children": [],
		"template": "line001",
		"title": "Beziehende von Prämienverbilligungen",
		"subtitle": "inkl. Beziehende von Sozialhilfe und Ergänzungsleistungen, Basel-Stadt",
		"kennzahlenset": "Soziales",
		"kuerzel": "I.13.2.09934",
		"kuerzelKunde": "",
		"description": "Beziehende von Prämienverbilligungen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2023-05-24T08:23:24.2424",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Mit 51 711 Beziehenden erhalten Ende 2022 ein Viertel aller in Basel-Stadt wohnhaften Personen Prämienverbilligungen.",
		"erlaeuterungen": "PV: Prämienverbilligungen, SH: Sozialhilfe, EL: Ergänzungsleistungen.",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Prämienverbilligungen"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9934,
		"chart-id": 9294,
		"filter": "",
		"id": 9934
	}
];