var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 22354,
		"chart-id": 22354,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bewertung der Lebensqualität",
		"subtitle": "«Wie bewerten Sie die Lebensqualität im Kanton Basel-Stadt insgesamt?»",
		"lesehilfe": "bla",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bewertung der Lebensqualität",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "1-1",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "1-1",
		"stufe1": "1 Allgemein",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-02T01:27:20",
		"id": 22354
	},
	{
		"template": "line001",
		"data-id": 22355,
		"chart-id": 22355,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Gestaltung und Erhaltung von Gebäuden und Strassenbild",
		"subtitle": "«Wie zufrieden sind Sie mit der Gestaltung und Erhaltung von Gebäuden und Strassenbild?», Anteil Zufriedene",
		"lesehilfe": "bla",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Gestaltung und Erhaltung von Gebäuden und Strassenbild",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "2-1",
		"stufe1": "2 Nutzungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_021",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-02T01:27:20",
		"id": 22355
	},
	{
		"template": "line001",
		"data-id": 22372,
		"chart-id": 22372,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Lebensraum Gundeldingen",
		"lesehilfe": "Am Jahresende 2024 zählte der Lebensraum Gundeldingen 22 250 Einwohnerinnen und Einwohner.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "1-2",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "1-2",
		"stufe1": "1 Allgemein",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22372
	},
	{
		"template": "template001",
		"data-id": 22373,
		"chart-id": 22373,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigte",
		"subtitle": "Lebensraum Gundeldingen",
		"lesehilfe": "Die Zahl der Beschäftigten im Lebensraum Gundeldingen sank zwischen 2013 und 2023 von 14 600 auf 14 416.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "1-3",
		"stufe1": "1 Allgemein",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22373
	},
	{
		"template": "line001",
		"data-id": 22374,
		"chart-id": 22374,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Durchschnittlicher Tagesverkehr Fussverkehr",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2024 passierten täglich durchschnittlich 6 123 Fussgänger die Zählstelle an der Güterstrasse 180/183.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als neun gezählten Monaten ausgewiesen.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Durchschnittlicher Tagesverkehr Fussverkehr",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "2-2",
		"stufe1": "2 Nutzungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_022",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22374
	},
	{
		"template": "template001",
		"data-id": 22375,
		"chart-id": 22375,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigung nach Branche",
		"subtitle": "in Vollzeitäquivalenten, Lebensraum Gundeldingen",
		"lesehilfe": "Die wichtigste Branche im Lebensraum Gundeldingen ist die Unternehmensverwaltung, -führung, -beratung\t mit 1605 Vollzeitäquivalenten im Jahr 2023, gefolgt von den Branchen Landverkehr (779), den Architektur- und Ingenieurbüros (729) sowie dem Detailhandel (711).",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Die Beschäftigung in Vollzeitäquivalenten (VZÄ) resultiert aus der Umrechnung des Arbeitsvolumens sämtlicher Voll- und Teilzeitbeschäftigten in Vollzeitbeschäftigte mittels Schätzmodell (basierend auf Lohnangaben der AHV und Informationen weiterer Erhebungen).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigung nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "2-3",
		"stufe1": "2 Nutzungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_023",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22375
	},
	{
		"template": "line001",
		"data-id": 22376,
		"chart-id": 22376,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Spielplätzen",
		"subtitle": "«Wenn Sie an Ihr Quartier denken, wie zufrieden sind Sie dann mit dem Angebot an Kinderspielplätzen?», Anteil Zufriedene",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Befragt werden Familien, die seit mindestens einem Jahr im Kanton Basel-Stadt wohnen. Als Familie wird ein Haushalt definiert, in welchem mindestens ein Elternteil mit mindestens einem Kind unter 18 Jahren gemeinsam lebt. Seit 2022 Gewichtung nach höchstem Bildungsabschluss der Eltern (ohne bzw. mit Tertiärabschluss) sowie der Familienform (Eineltern- bzw. Zweielternhaushalte). Die Daten der Befragungen 2013 und 2017 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser beiden Jahre weichen deshalb von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Familienbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Spielplätzen",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "3-1",
		"stufe1": "3 Freiräume",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_031",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22376
	},
	{
		"template": "line001",
		"data-id": 22377,
		"chart-id": 22377,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Grünflächen",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks am Wohnort?», Anteil Zufriedene",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünflächen",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "3-2",
		"stufe1": "3 Freiräume",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_032",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22377
	},
	{
		"template": "line001",
		"data-id": 22380,
		"chart-id": 22380,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit der Verkehrssicherheit",
		"subtitle": "«Wie zufrieden sind Sie mit der Verkehrssicherheit?», Anteil Zufriedene",
		"lesehilfe": "",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit der Verkehrssicherheit",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "4-1",
		"stufe1": "4 Mobilität",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_041",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22380
	},
	{
		"template": "line001",
		"data-id": 22381,
		"chart-id": 22381,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Durchschnittlicher Tagesverkehr Veloverkehr",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2024 passierten täglich durchschnittlich 2 692 Velos die Zählstelle am Peter-Merian Weg. Bei der Zählstelle beim Dorenbachviadukt waren es 3 819.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als neun gezählten Monaten ausgewiesen.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Durchschnittlicher Tagesverkehr Veloverkehr",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "4-2",
		"stufe1": "4 Mobilität",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_042",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22381
	},
	{
		"template": "line001",
		"data-id": 22382,
		"chart-id": 22382,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit dem öffentlichen Verkehr",
		"subtitle": "«Wie zufrieden sind Sie mit den öffentlichen Verkehrsmitteln?», Anteil Zufriedene",
		"lesehilfe": "",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem öffentlichen Verkehr",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "4-3",
		"stufe1": "4 Mobilität",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_043",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22382
	},
	{
		"template": "line001",
		"data-id": 22383,
		"chart-id": 22383,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Durchschnittlicher Tagesverkehr MIV",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2024 passierten täglich durchschnittlich 5 651 Motorfahrzeuge die Zählstelle an der Dornacherstrasse 49. Bei der Zählstelle an der Gundeldingerstrasse 107 waren es 7 418, an der Sempacherstrasse 68 waren es 1 054.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als neun gezählten Monaten ausgewiesen.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Durchschnittlicher Tagesverkehr MIV",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilrichtplan Gundeldingen",
		"kuerzelKunde": "4-4",
		"stufe1": "4 Mobilität",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_044",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:17:47",
		"id": 22383
	}
];