var indikatorensetData = [
	{
		"template": "spider001",
		"data-id": 12609,
		"chart-id": 6640,
		"filter": "",
		"parentId": "6640",
		"children": [],
		"title": "St. Johann - Quartierradar",
		"subtitle": "Ausgabe 2023",
		"lesehilfe": "Das Wohnviertel St. Johann verzeichnet einen relativ hohen Anteil Ausländer und Sozialhilfeempfänger. Der Altersquotient ist niedrig. Die Wohnfläche pro Kopf ist vergleichsweise gering. Die Anzahl Arbeitsplätze pro Kopf liegt im oberen Drittel, die Erwerbstätigenquote ist tief.",
		"erlaeuterungen": "Die Grafik fasst 16 Indikatoren zusammen. Die Indikatoren sind den drei Bereichen <font color=\"923F8D\">Gesellschaft und Soziales</font>, <font color=\"68AB2B\">Raum und Umwelt</font> sowie <font color=\"689199\">Wirtschaft und Arbeit</font> zugeordnet. Die Werte der Indikatoren sind als Ränge im Vergleich zu allen anderen Basler Wohnvierteln und Gemeinden ausgewiesen. Das Wohnviertel oder die Gemeinde mit dem niedrigsten Wert des Indikators erhält Rang 1, mit dem höchsten Wert Rang 21 zugewiesen. Je grösser die graue Fläche, desto öfter erreicht das Wohnviertel oder die Gemeinde hohe Ränge bei den Indikatoren. <a href =\" https://www.statistik.bs.ch/dam/jcr:2cb04e13-b746-4455-8735-029f0439dc73/Quartierradar.pdf \" target = '_blank'>Zur Definition der einzelnen Indikatoren </a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "St. Johann - Quartierradar",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12609",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "1.02",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T06:57:17",
		"id": 12609
	},
	{
		"template": "line001",
		"data-id": 12610,
		"chart-id": 8046,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.01",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12610
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 8047,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnviertel Klybeck, 2023",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02a",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12611
	},
	{
		"template": "line001",
		"data-id": 12612,
		"chart-id": 8048,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Jugendquotient",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.03",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12612
	},
	{
		"template": "line001",
		"data-id": 12613,
		"chart-id": 8049,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Altersquotient",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.04",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12613
	},
	{
		"template": "line001",
		"data-id": 12614,
		"chart-id": 8050,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausländeranteil",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12614",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.05",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12614
	},
	{
		"template": "template001",
		"data-id": 12615,
		"chart-id": 8051,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausländer nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Ausländer nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12615",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.07",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12615
	},
	{
		"template": "line001",
		"data-id": 12616,
		"chart-id": 8052,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen sowie Stadt Basel",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anteil Einwohner, die seit mindestens zehn Jahren an der gleichen Adresse wohnen. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12616",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.08",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12616
	},
	{
		"template": "template001",
		"data-id": 12617,
		"chart-id": 8053,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Haushalte nach Art des Haushalts",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Personen, die in der gleichen Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privathaushalte und Kollektivhaushalte. Hier werden nur Privathaushalte betrachtet. Die Gruppe «Andere Haushalte» umfasst Mehrpersonenhaushalte wie Wohngemeinschaften und unverheiratete Paare ohne ein gemeinsames Kind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Haushalte nach Art des Haushalts",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "I.01.TRKE.12617",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.01",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12617
	},
	{
		"template": "template001",
		"data-id": 12618,
		"chart-id": 8054,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Schweizerische ausserkantonale Agglomerationsgemeinden: Aesch, Allschwil, Arboldswil, Arisdorf, Arlesheim, Augst, Bärschwil, Bättwil, Bennwil, Biel-Benken, Binningen, Birsfelden, Blauen, Böckten, Bottmingen, Breitenbach, Bretzwil, Brislach, Bubendorf, Buckten, Büren, Burg im Leimental, Büsserach, Buus, Diepflingen, Dittingen, Dornach, Duggingen, Ettingen, Fehren, Frenkendorf, Füllinsdorf, Gelterkinden, Gempen, Giebenach, Grellingen, Hellikon, Hemmiken, Hersberg, Himmelried, Hochwald, Hofstetten-Flüh, Hölstein, Itingen, Kaiseraugst, Känerkinden, Kleinlützel, Lampenberg, Laufen, Lausen, Lauwil, Liestal, Lupsingen, Magden, Maisprach, Meltingen, Metzerlen-Mariastein, Möhlin, Mumpf, Münchenstein, Muttenz, Nenzlingen, Niederdorf, Nuglar-St. Pantaleon, Nunningen, Nusshof, Oberdorf, Obermumpf, Oberwil, Olsberg, Ormalingen, Pfeffingen, Pratteln, Ramlinsburg, Reigoldswil, Reinach, Rheinfelden, Rickenbach, Rodersdorf, Röschenz, Rümlingen, Rünenberg, Schönenbuch, Seltisberg, Seewen, Sissach, Tecknau, Tenniken, Therwil, Titterten, Thürnen, Wahlen, Wegenstetten, Wenslingen, Wintersingen, Witterswil, Wittinsburg, Zeiningen, Ziefen, Zullwil, Zunzgen, Zuzgen und Zwingen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.09",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12618
	},
	{
		"template": "line001",
		"data-id": 12619,
		"chart-id": 8055,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Segregationsindex nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Der Segregationsindex ist ein Mass zur Beschreibung räumlicher Ungleichverteilungen von Bevölkerungsgruppen. Er misst hier, wie stark die Verteilung einer Bevölkerungsgruppe über das Gebiet der Wohnviertel Klybeck und Kleinhüningen von einer Gleichverteilung abweicht, wobei 0 absolute Gleichverteilung und 100 maximale Segregation bedeutet. Der Wert des Segregationsindexes lässt sich auch als Prozentanteil der betrachteten Gruppe interpretieren, der in einen anderen statistischen Block umziehen müsste, um gleich über das Gebiet der Wohnviertel Klybeck und Kleinhüningen verteilt zu sein wie die übrige Bevölkerung. Ein Segregationsindex von 0 bedeutet, dass der Anteil Personen einer Gruppe am Total der Bevölkerung in jedem Teilgebiet gleich gross ist. Bei kleinräumigen Betrachtungen können die Werte infolge kleiner Gruppengrössen über die Jahre stark schwanken.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Segregationsindex nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.11",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12619
	},
	{
		"template": "template001",
		"data-id": 12620,
		"chart-id": 8056,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Religionszugehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Im Kanton Basel-Stadt sind folgende Religionsgemeinschaften öffentlich-rechtlich anerkannt: evangelisch-reformiert, römisch-katholisch, christkatholisch, israelitisch.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Religionszugehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "I.01.TRUN.12620",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.06",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12620
	},
	{
		"template": "line001",
		"data-id": 12621,
		"chart-id": 8057,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12621",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.06",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12621
	},
	{
		"template": "line001",
		"data-id": 12622,
		"chart-id": 8058,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12622",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.07",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:03",
		"id": 12622
	},
	{
		"template": "line001",
		"data-id": 12623,
		"chart-id": 8059,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Steuerertrag durch Zu- und Wegzüger",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Beim Steuerverfahren der ordentlichen Veranlagung ist für die kantonale Steuerpflicht der Wohnsitz am 31. Dezember massgebend. Es liegen daher im Wegzugskanton in der Regel keine Steuerdaten für das Jahr des Wegzugs vor. Deshalb ist für Wegziehende jeweils der Steuerertrag des Vorjahres abgebildet. Für die Zugezogenen und die ganzjährig Niedergelassenen werden die Steuerdaten des Berichtsjahres verwendet. <br>Aufgrund verschiedener methodischer Besonderheiten sind quellenbesteuerte Personen in dieser Auswertung zunächst nicht berücksichtig. Erst wenn sie nachträglich ordentlich veranlagt werden (zum Beispiel bei Einkünften von mehr als 120 000 Franken pro Jahr) oder die Niederlassungsbewilligung erhalten und deshalb ins ordentliche Verfahren wechseln, werden sie als Zuzug gezählt und in die Auswertung miteinbezogen – auch wenn sie schon länger im Kanton wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Steuerertrag durch Zu- und Wegzüger",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12623",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.08",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12623
	},
	{
		"template": "template001",
		"data-id": 12624,
		"chart-id": 8060,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Als Zimmer gelten Räume, welche als bauliche Einheit die Wohnung bilden. Küchen, Badezimmer, Toilettenräume, Reduits, Gänge, Veranden usw. gelten nicht als Zimmer. Ebensowenig werden halbe Zimmer gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12624",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.03",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12624
	},
	{
		"template": "template001",
		"data-id": 12625,
		"chart-id": 8061,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen nach Belegungsart",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Daten beziehen sich auf die belegten Wohnungen, Mansarden oder Einzelzimmer (Haushalte). Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Belegungsart",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12625",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.04",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12625
	},
	{
		"template": "line001",
		"data-id": 12626,
		"chart-id": 8062,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnfläche pro Person",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die durchschnittliche Wohnfläche pro Bewohner berechnet sich aus der Gesamtfläche der bewohnten Wohnungen, dividiert durch die Summe der zugeordneten Bewohner. Als Wohnungsfläche gelten sämtliche bewohnbaren Flächen einer Wohnung, also die Summe der Flächen sämtlicher Zimmer, Küchen, Kochnischen, Badezimmer, Toilettenräume, Abstellräume, Gänge, Veranden etc. einer Wohnung (ohne Terrassen oder offene Balkone). Für die Berechnung werden sämtliche einer Wohnung zugeordneten Bewohner berücksichtigt, unabhängig von ihrem Meldeverhältnis (Niedergelassene und Aufenthalter). Personen mit mehreren Wohnsitzen werden entsprechend mehrmals gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12626",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.02",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12626
	},
	{
		"template": "line001",
		"data-id": 12627,
		"chart-id": 8063,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerwohnungsquote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Stichtag ist der 1. Juni. Nur Wohnungen, die für den eigentlichen Wohnungsmarkt in Betracht kommen; also ohne leere Wohnungen, die für den Abbruch oder Umbau bestimmt sind. Die Prozentangaben beziehen sich auf den Leerwohnungsbestand am Gesamtwohnungsbestand.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12627",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.05",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12627
	},
	{
		"template": "line001",
		"data-id": 12628,
		"chart-id": 8064,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettomietpreise nach Wohnviertel",
		"subtitle": "in Franken pro m<sup>2</sup>, Basel-Stadt, 2017-2021",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Der Quadratmeter-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4- Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettomietpreise nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.12628",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.06",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12628
	},
	{
		"template": "line001",
		"data-id": 12629,
		"chart-id": 8065,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Einfamilienhäuser",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anteil der Einfamilienhäuser an allen bewohnbaren Gebäuden des Wohnviertels oder Bezirkes in Prozent. Die Werte von 2011 und 2012 beruhen auf der jährlichen Fortschreibung der Volkszählung 2000. Ab 2013 stammen die Daten aus dem kantonalen Gebäude- und Wohnungsregister GWR.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil Einfamilienhäuser",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12629",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.07",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12629
	},
	{
		"template": "template001",
		"data-id": 12630,
		"chart-id": 8066,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die prozentualen Anteile im Tooltip beziehen sich auf das Total der Zugänge resp. das Total der Abgänge.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12630",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.08",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12630
	},
	{
		"template": "template001",
		"data-id": 12631,
		"chart-id": 8067,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neu gebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12631",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.09",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:04",
		"id": 12631
	},
	{
		"template": "template001",
		"data-id": 12632,
		"chart-id": 8068,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Genossenschaftswohnungen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche am Stichtag (31.12.) durch mindestens eine Person belegt waren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Genossenschaftswohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12632",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.10",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12632
	},
	{
		"template": "line001",
		"data-id": 12633,
		"chart-id": 8069,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben, und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.12633",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.01",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12633
	},
	{
		"template": "line001",
		"data-id": 12634,
		"chart-id": 8070,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigung nach ausgewählten Branchen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben, und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handeln kann, und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte (oder Adresse) tätig sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Beschäftigung nach ausgewählten Branchen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.12634",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.03",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12634
	},
	{
		"template": "template001",
		"data-id": 12635,
		"chart-id": 8071,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Rotlichtsalons",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Für die Jahre 2008 und 2012 liegen keine Daten vor.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Rotlichtsalons",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12635",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.09",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12635
	},
	{
		"template": "line001",
		"data-id": 12636,
		"chart-id": 8072,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettoerwerbstätigenquote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Nettoerwerbstätigenquote ist definiert als die Anzahl der Erwerbstätigen, geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettoerwerbstätigenquote",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12636",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.04",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12636
	},
	{
		"template": "line001",
		"data-id": 12637,
		"chart-id": 8073,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttogeschossfläche Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet. Die Daten sind damit nicht direkt vergleichbar mit den Vorjahren. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bruttogeschossfläche Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12637",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.02",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12637
	},
	{
		"template": "line001",
		"data-id": 12638,
		"chart-id": 8074,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettoerwerbsquote der Frauen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Nettoerwerbsquote ist definiert als die Summe der Erwerbspersonen (Erwerbstätige plus Erwerbslose), geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2015 bis 2019 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese 5 Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettoerwerbsquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12638",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.05",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12638
	},
	{
		"template": "line001",
		"data-id": 12639,
		"chart-id": 8075,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfebezüger und -quote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Sozialhilfebezüger und -quote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.12639",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.04",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12639
	},
	{
		"template": "line001",
		"data-id": 12640,
		"chart-id": 8076,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sek P-Quote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Seit 2017/18 Anteil der Sek-Schülerinnen und Schüler im Leistungszug P mit hohen Anforderungen an allen Sek-Schülerinnen und Schülern der 10. und 11. Schulstufe (einschliesslich zweier obligatorischer Kindergartenstufen gezählt) an öffentlichen Schulen und mit Wohnort Basel-Stadt. Bis Schuljahr 2015/16 Anteil der Gymnasiastinnen und Gymnasiasten an allen Schülerinnen und Schülern der 10. und 11. Schulstufe. Im Übergangsjahr 2016/17 wurde als Hilfskonstrukt für Stufe 10 der Sek P-Anteil und für Stufe 11 der Gym-Anteil herangezogen. Stichtag der Bildungsstatistik ist jeweils im September; das Jahr 2022 in der Grafik entspricht Schuljahr 2022/23.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sek P-Quote",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.12640",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.02",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:05",
		"id": 12640
	},
	{
		"template": "line001",
		"data-id": 12641,
		"chart-id": 8077,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Der Indikator zeigt den Anteil der Schülerinnen und Schüler mit Erstsprache Deutsch an allen Schülerinnen und Schülern der öffentlichen Kindergärten und Primarschulen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.12641",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.01",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12641
	},
	{
		"template": "line001",
		"data-id": 12642,
		"chart-id": 8078,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2018-2022",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anteil der Personen mit höchstem Bildungsabschluss «Tertiärstufe» an der über 14-jährigen Wohnbevölkerung. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft, sowie Ausbildungen an Hochschulen wie z. B. ein Bachelor- oder Masterstudium. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Die Frage zur höchsten abgeschlossenen Ausbildung wurde im Fragebogen der Strukturerhebung 2020 verändert. Somit liegt ein methodischer Bruch innerhalb des Poolingzeitraums vor.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.12642",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.03",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12642
	},
	{
		"template": "line001",
		"data-id": 12643,
		"chart-id": 8079,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Quote der Haushalte mit Familienmietzinsbeiträgen und reiner Prämienverbilligung",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Quote der Haushalte mit Familienmietzinsbeiträgen (FAMI) entspricht dem Verhältnis der Anzahl Haushalte mit Mietzinsbeiträgen zur Gesamtzahl der Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per Ende des Jahres. Die Quote der Haushalte mit Prämienverbilligung (PV) entspricht dem Verhältnis der Anzahl Haushalte mit PV zur Gesamtzahl der Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per Ende des Jahres. Es werden alle Haushalte mit mindestens einer Person mit reiner PV gezählt. Beziehende von Sozialhilfe und Ergänzungsleistungen, die die PV im Rahmen jener Leistungen ausbezahlt erhalten, sind nicht einberechnet. Stichtag ist jeweils der 4. Januar des Folgejahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Quote der Haushalte mit Familienmietzinsbeiträgen und reiner Prämienverbilligung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.12643",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.05",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12643
	},
	{
		"template": "template001",
		"data-id": 12644,
		"chart-id": 8080,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bodenbedeckung nach Nutzungsart",
		"subtitle": "Anteil an der Gesamtfläche, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Grünfläche: alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten Flächen (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige). Gewässer: stehende und fliessende Gewässer. Verkehrsfläche: Befestigte Flächen wie Strassen, Wege, Trottoirs (inkl. Rabatten) und Verkehrsinseln sowie Bahn- und Tramareale. Übrige befestigte Flächen: Hafen- und Fabrikareale; Tankanlagen; Wasserbecken und befestigtes Gewässervorland; befestigte Sportanlagen; alle weiteren befestigten Flächen. Als befestigt gelten künstlich hergerichtete Flächen, insbesondere asphaltierte, betonierte, bekieste, gemergelte oder mit Steinen oder Platten belegte Flächen. <br>Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bodenbedeckung nach Nutzungsart",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12644",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.01",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12644
	},
	{
		"template": "template001",
		"data-id": 12645,
		"chart-id": 8081,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Grünflächen nach Kategorie",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Als Grünfläche gelten alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige) Flächen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Grünflächen nach Kategorie",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12645",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.02",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12645
	},
	{
		"template": "map002",
		"data-id": 12646,
		"chart-id": 7701,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Tropennächte",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2018",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Heissere Flächen sind in der Regel stark bebaute, versiegelte und vegetationsarme Gebiete (z. B.Innenstädte, Industrie- und Bahnareale). Kühlere Flächen finden sich dort, wo genügend Vegetation (z. B. Parks) oder grössere Gewässer (Rhein) vorhanden sind oder wo Kaltluftzufuhr, z. B. aus umliegenden kühleren Gebieten, erfolgen kann. Die Daten basieren auf Modellrechnungen (200 x 200 m-Raster, räumlich gemittelt über das jeweilige Wohnviertel) der Universität Basel für das Jahr 2018 und berücksichtigen neben Temperaturmessungen (an zehn Standorten) auch Topografie, Gebäude, Bäume und die Oberflächenbeschaffenheit des Bodens.",
		"quellenangabe": [
			"MCR-Lab, Universität Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.12646",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.04",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12646
	},
	{
		"template": "template001",
		"data-id": 12648,
		"chart-id": 8085,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Gebäude nach Energieträger der Hauptheizung",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Anzahl Gebäude nach Energieträger der Hauptheizung stammt aus der kantonalen Gebäude- und Wohnungsstatistik, welche jährlich per 31. Dezember aus dem kantonalen Gebäude- und Wohnungsregister (GWR) erzeugt wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Gebäude nach Energieträger der Hauptheizung",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.12648",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.07",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12648
	},
	{
		"template": "line001",
		"data-id": 12649,
		"chart-id": 8086,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stromverbrauch",
		"subtitle": "in Gigawattstunden (GWh), Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Daten stammen aus der kantonalen Energiestatistik, welche seit dem Jahr 2012 im Zweijahresrhythmus erscheint. Ausgewiesen werden hier ausschliesslich Endverbräuche in Gigawattstunden (GWh).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Stromverbrauch",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.12649",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.06",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:06",
		"id": 12649
	},
	{
		"template": "line001",
		"data-id": 12650,
		"chart-id": 8087,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anzahl der auf Privatpersonen zugelassenen Personenwagen geteilt durch die Anzahl Haushalte sowie pro 1 000 Einwohner (Motorisierungsgrad). Zur Berechnung wird jeweils der Jahresendbestand der Personenwagen und Einwohner (exkl. Personen an administrativen Meldeadressen) verwendet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Kantonspolizei Basel-Stadt, Motorfahrzeugkontrolle"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.12650",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.08",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12650
	},
	{
		"template": "mappie001",
		"data-id": 12651,
		"chart-id": 7707,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Feinstaubbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2015",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Feinstaub-Belastungen (PM10) von über 20&nbsp;µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionskarten 10x10 m für 2015). Unter PM10 versteht man Partikel, die kleiner sind als 10 Mikrometer. Dieser Staub ist ein physikalisch-chemisch komplexes Gemisch. Er entsteht bei industriellen und gewerblichen Produktionsprozessen, Verbrennungsprozessen, mechanischen Prozessen (Abrieb, Aufwirbelung) sowie durch sekundäre Bildung (aus SO<sub>2</sub>, NO<sub>x</sub>, NH<sub>3</sub>, VOC). PM10 ist in seiner Zusammensetzung sehr vielfältig und kann Russ, Schwermetalle, Sulfat, Nitrat, Ammonium, organischen Kohlenstoff, polyzyklische aromatische Kohlenwasserstoffe oder Dioxine/Furane enthalten. Feinstaub führt zu Erkrankungen der Atemwege, des Herz-Kreislaufsystems, zu einer Zunahme des Krebsrisikos und der Sterberate.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Feinstaubbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kuerzel": "I.02.15.12651",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.09",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_009",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12651
	},
	{
		"template": "mappie001",
		"data-id": 12652,
		"chart-id": 7708,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stickoxidbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2015",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Stickstoffdioxid-Belastungen (NO<sub>2</sub>) von über 30 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionen modelliert auf Basis eines 10 x 10 m-Rasters). Stickoxide (NO<sub>x</sub>) entstehen beim Verbrennen von Brenn- und Treibstoffen, insbesondere bei hohen Verbrennungstemperaturen. Hauptquelle ist der Strassenverkehr. Stickoxide sind wichtige Vorläufersubstanzen für die Bildung von sauren Niederschlägen, sekundärem Feinstaub und – zusammen mit flüchtigen organischen Verbindungen – von Ozon/Sommersmog. Stickstoffdioxid (NO<sub>2</sub>) und andere Reizgase begünstigen Erkrankungen der Atemwege.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Stickoxidbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kuerzel": "I.02.15.12652",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.10",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12652
	},
	{
		"template": "line001",
		"data-id": 12653,
		"chart-id": 8090,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Freiraumfläche",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Bezirk Friedmatt waren 2023 7,4% der Bezirksfläche Freiraumflächen, in den Bezirken Kannenfeld und Landskron gab es keine Freiraumflächen (Stadt Basel: 3,1%).",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Freiraumfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12653",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.03",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12653
	},
	{
		"template": "line001",
		"data-id": 12655,
		"chart-id": 8092,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Delikte",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Berücksichtigt sind folgende Deliktkategorien: Entreissdiebstahl, Raub, Einbruch- und Einschleichdiebstähle, Nötigung sowie Sexualdelikte (Vergewaltigung, sexuelle Nötigung).",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Delikte",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.12655",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "6.01",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12655
	},
	{
		"template": "line001",
		"data-id": 12656,
		"chart-id": 8093,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Einbruch- und Einschleichdiebstähle",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Anzahl Einbruch- und Einschleichdiebstähle.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Einbruch- und Einschleichdiebstähle",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.12656",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "6.02",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12656
	},
	{
		"template": "template001",
		"data-id": 12657,
		"chart-id": 8094,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Umzugssaldo",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Umzüge sind räumliche Bevölkerungsbewegungen innerhalb des Kantons Basel-Stadt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umzugssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.10",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:07",
		"id": 12657
	},
	{
		"template": "populationPyramid001",
		"data-id": 12659,
		"chart-id": 8614,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnviertel Kleinhüningen, 2023",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12659",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02b",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:08",
		"id": 12659
	}
];