var indikatorensetData = [
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12611,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnbezirk Friedmatt, 2023",
		"lesehilfe": "In den Bezirken von St. Johann sind bis auf wenige Ausnahmen die grössten Fünfjahresklassen diejenigen der 25- bis 44-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02a",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:02",
		"id": 12611
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12659,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnbezirk Kannenfeld, 2023",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12659",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02b",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-10T08:47:08",
		"id": 12659
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12719,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnbezirk Landskron, 0",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02c",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-06T01:52:40",
		"id": 12719
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12720,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnbezirk Lysbüchel, 0",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02d",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-06T01:56:09",
		"id": 12720
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12721,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnbezirk Pestalozzi, 0",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02e",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-06T01:56:35",
		"id": 12721
	}
];