var indikatorensetData = [
	{
		"template": "befragungen001",
		"data-id": 22408,
		"chart-id": 22408,
		"filter": "",
		"parentId": "4150",
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "85,8% der Bevölkerung sind 2023 mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppe gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22408
	},
	{
		"template": "befragungen001",
		"data-id": 22409,
		"chart-id": 22409,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Wohnumfeld",
		"subtitle": "«Wie zufrieden sind Sie insgesamt mit Ihrem Wohnumfeld?», Basel-Stadt",
		"lesehilfe": "Mit 48,1% ist beinahe die Hälfte der befragten Familien sehr zufrieden mit dem Wohnumfeld. 2,2% zeigen sich sehr unzufrieden.",
		"erlaeuterungen": "Befragt werden Familien, die seit mindestens einem Jahr im Kanton Basel-Stadt wohnen. Als Familie wird ein Haushalt definiert, in welchem mindestens ein Elternteil mit mindestens einem Kind unter 18 Jahren gemeinsam lebt. Seit 2022 Gewichtung nach höchstem Bildungsabschluss der Eltern (ohne bzw. mit Tertiärabschluss) sowie der Familienform (Eineltern- bzw. Zweielternhaushalte). Die Daten der Befragungen 2013 und 2017 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser beiden Jahre weichen deshalb von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Familienbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Zufriedenheit mit Wohnumfeld",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22409
	},
	{
		"template": "befragungen001",
		"data-id": 22410,
		"chart-id": 22410,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Empfinden Hitzetage Sommer",
		"subtitle": "«Wie empfinden Sie die Hitzetage (Temperatur 30 Grad und mehr) in den Sommermonaten an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "22,8% der Bevölkerung empfinden Hitzetage als unangenehm und 26,0% als eher unangenehm.Demgegenüber finden 9,8% Hitzetage als angenehm und 22,4% als eher angenehm.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Die Ergebnisse sind gewichtet nach Geschlecht, Staatsangehörigkeit und Altersgruppen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Empfinden Hitzetage Sommer",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22410
	},
	{
		"template": "template001",
		"data-id": 22411,
		"chart-id": 22411,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Freiraumfläche und Anteil im Siedlungsgebiet",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Freiraumfläche und Anteil im Siedlungsgebiet",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.2.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22411
	},
	{
		"template": "template001",
		"data-id": 22412,
		"chart-id": 22412,
		"filter": "",
		"parentId": "6574",
		"children": [],
		"title": "Baumkronenbedeckung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Kronenbedeckung (durch Bäume beschattete Fläche) 24,4% der gesamten Kantonsfläche und 17,2% der Stadt Basel. Schliesst man die reinen Waldflächen von der Betrachtung aus, so reduzieren sich die Anteile auf 16,5% respektive 15,1%.",
		"erlaeuterungen": "Durch flugzeuggestützte Laserabtastung der Oberfläche (LiDAR - Light Detecting And Ranging) werden Daten zur Kronenbedeckung abgeleitet. Seit 2021 finden alle drei Jahre Befliegungen statt, um die Entwicklung der Kronenbedeckung verfolgen zu können. <br>Berücksichtigt werden bei der Auswertung nur Kronen mit einer Höhe über 3 m. Die LiDAR-Methodologie wurde in den letzten Jahren verbessert. Änderungen unter 1% (zwischen 2012 und 2021) sollten nicht als reale Veränderungen betrachtet und mit Vorsicht interpretiert werden. Es gibt eine gewisse Variabilität bei Flugmethode, Flugzeitpunkt und Klassifizierungsmethode; diese befindet sich im Prozentbereich.",
		"quellenangabe": [
			"Stadtgärtnerei Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://data.bs.ch/explore/dataset/100357' target = '_blank'>OGD-Datensatz</a>",
			"<a href = 'https://tiefbauamt-bs.ch/geoviewer/kronenbedeckung' target = '_blank'>Baumkronenbedeckung als Karte</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Baumkronenbedeckung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.2.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22412
	},
	{
		"template": "template001",
		"data-id": 22413,
		"chart-id": 22413,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bevölkerung in Stadtklimakonzept-Fokusgebieten",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bevölkerung in Stadtklimakonzept-Fokusgebieten",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.3.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22413
	},
	{
		"template": "template001",
		"data-id": 22414,
		"chart-id": 11910,
		"filter": "",
		"parentId": "11910",
		"children": [],
		"title": "Revitalisierungsrate Oberflächengewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2015 wurden 1,6 km der bis 2035 geplanten 9,6 km revitalisiert.",
		"erlaeuterungen": "Länge der jährlich revitalisierten Gewässerabschnitte im Vergleich zur Gesamtlänge der gemäss Revitalisierungsplanung prioritär zu revitalisierenden Gewässerstrecken. Laut Gewässerschutzgesetz sind die Kantone verpflichtet, Revitalisierungen an Gewässern durchzuführen. Im Kanton Basel-Stadt ist der Nutzen von Revitalisierungsmassnahmen an Wiese und Riehenteich (Abschnitte Neuer Teich und Mühleteich) unter Berücksichtigung des zu erwartenden Aufwands am grössten. Bis 2035 sollen 9,6 km revitalisiert werden. In den Jahren 2015 bis 2095 sollen gesamthaft rund 4 000 km der Fliessgewässer in der Schweiz revitalisiert werden.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Revitalisierungsrate Oberflächengewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.4.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22414
	},
	{
		"template": "template001",
		"data-id": 22415,
		"chart-id": 11909,
		"filter": "",
		"parentId": "11909",
		"children": [],
		"title": "Strukturen der Fliessgewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von 47 km Fliessstrecke werden 2025 nur knapp 2 km (4,2%)  als natürlich oder naturnah bezeichnet.",
		"erlaeuterungen": "Die Beurteilung der Struktur der Fliessgewässer erfolgt über die ökomorphologische Bewertung nach dem Modul-Stufen-Konzept, Stufe F des Bundesamtes für Umwelt. Im Kanton Basel-Stadt wird eine Fliesstrecke von insgesamt 47 km bewertet.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'http://www.modul-stufen-konzept.ch' target = '_blank'>Modul-Stufen-Konzept des Bundesamtes für Umwelt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Strukturen der Fliessgewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.4.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22415
	},
	{
		"template": "template001",
		"data-id": 22416,
		"chart-id": 22416,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Trockenheitsindex",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Trockenheitsindex",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.4.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22416
	},
	{
		"template": "template001",
		"data-id": 22417,
		"chart-id": 22417,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bodenversiegelung",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bodenversiegelung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22417
	},
	{
		"template": "template001",
		"data-id": 22418,
		"chart-id": 22418,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Gebäudeflächen an der Siedlungsfläche",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Gebäudeflächen an der Siedlungsfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22418
	},
	{
		"template": "template001",
		"data-id": 22418,
		"chart-id": 22419,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Verkehrsflächen an der Siedlungsfläche",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Verkehrsflächen an der Siedlungsfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22419
	},
	{
		"template": "template001",
		"data-id": 22420,
		"chart-id": 22420,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Freiflächen an den Arealentwicklungsflächen",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Freiflächen an den Arealentwicklungsflächen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.6.1.",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-04T04:41:12",
		"id": 22420
	}
];