var indikatorensetData = [
	{
		"template": "line001_print",
		"data-id": 9315,
		"chart-id": 9315,
		"filter": "",
		"parentId": "6896",
		"children": [],
		"title": "Zusammensetzung der Gesamteinnahmen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die Gesamteinnahmen des Kantons betragen über die Jahre gesehen zwischen knapp 4 Mrd. und 5 Mrd. Franken. Seit dem Jahr 2012 sind die Werte nach dem neuen Rechnungslegungsmodell HRM2 dargestellt. Dies erschwert einen Vergleich mit den Vorjahren. Im Kalenderjahr 2018 beträgt der Ertrag aus Einkommens- und Vermögenssteuern rund 1,8 Mrd. Franken (+4,6% gegenüber dem Vorjahr), der Anteil am Gesamtertrag beträgt 41,2%. Die Gewinn- und Kapitalsteuern belaufen sich 2018 auf rund 748 Mio. Franken (-8,4% gegenüber 2017), der Anteil liegt bei 17,6%. Zusammen beträgt der Anteil der aufgeführten Steuerarten im Jahr 2018 58,8% des gesamten Ertrags des Kantons. Der Ertrag aus Quellensteuer ist zum Teil in der Kategorie Übriges und zum Teil in der Kategorie Einkommens- und Vermögenssteuern enthalten.",
		"erlaeuterungen": "Der Jahresbericht des Kantons Basel-Stadt weist Erträge aus, die während eines Kalenderjahres verbucht wurden. Dies unterscheidet sich somit von der Steuerstatistik Basel-Stadt, der Veranlagungsdaten zugrunde liegen, die auf ein bestimmtes Steuerjahr bezogen sind – in welchem Jahr die Steuer verbucht oder bezahlt worden ist. NP = Natürliche Personen; JP = Juristische Personen.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zusammensetzung der Gesamteinnahmen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09315",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "1-1",
		"stufe1": "Ertrag des Kantons",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:31",
		"id": 9315
	},
	{
		"template": "line001_print",
		"data-id": 9316,
		"chart-id": 9316,
		"filter": "",
		"parentId": "6897",
		"children": [],
		"title": "Entwicklung des Ertrags aus Steuern",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die einzelnen Steuerertragsarten haben sich seit 2009 unterschiedlich entwickelt. Grössere Schwankungen liegen vor allem bei der Gewinnsteuer vor, zwischen 2009 und 2017 ist dieser Wert nominal um 39,4% zurückgegangen – allerdings ist der Ausgangswert des Jahres 2009 mit 626 Mio. Franken auch vergleichsweise hoch. Bei den juristischen Personen zeigen sich beispielsweise auch die Auswirkungen der wirtschaftlichen Entwicklung nach Beginn der Finanz- und Wirtschaftskrise 2009 deutlicher. Bei den natürlichen Personen ist der Ertrag aus Einkommenssteuern von 2009 bis 2018 um 8,8%, aus Vermögenssteuern um 9,1% gestiegen. Der Ertrag aus Quellenbesteuerung (2019) stieg um 68,0%.",
		"erlaeuterungen": "Der Jahresbericht des Kantons Basel-Stadt weist Erträge aus, die während eines Kalenderjahres verbucht wurden. Dies unterscheidet sich somit von der Steuerstatistik Basel-Stadt, der Veranlagungsdaten zugrunde liegen, die auf ein bestimmtes Steuerjahr bezogen sind – unabhängig davon, in welchem Jahr die Steuer verbucht oder bezahlt worden ist.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung des Ertrags aus Steuern",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09316",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "1-2",
		"stufe1": "Ertrag des Kantons",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:32",
		"id": 9316
	},
	{
		"template": "line001_print",
		"data-id": 9317,
		"chart-id": 9317,
		"filter": "",
		"parentId": "6898",
		"children": [],
		"title": "Veranlagungen natürlicher Personen und Bevölkerung",
		"subtitle": "nach Tarif und Alter, Basel-Stadt, 2018",
		"lesehilfe": "Im Jahr 2018 gibt es insgesamt 116 404 Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen und wohnhaften Personen. Nicht berücksichtigt sind Veranlagungen von Auswärtigen (insgesamt rund 8 400 Veranlagungen) und von Unterjährigen (ca. 5 000 Veranlagungen). Nach Tarif betrachtet stammen rund 79 000 Veranlagungen von Alleinstehenden (Anteil 67,8%), 31 100 von Verheirateten (26,7%) und ca. 6 400 von Alleinstehenden mit Kind oder einer anderen unterstützten Person (5,5%).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen natürlicher Personen und Bevölkerung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09317",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-1",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:33",
		"id": 9317
	},
	{
		"template": "line001_print",
		"data-id": 9318,
		"chart-id": 9318,
		"filter": "",
		"parentId": "6899",
		"children": [],
		"title": "Veranlagungen, Bevölkerung und Summe von Reineinkommen, -vermögen und Steuerertrag",
		"subtitle": "indexiert (2009 = 100), Basel-Stadt",
		"lesehilfe": "Die indexierten Linien für die Wohnbevölkerung in Basel-Stadt und die Anzahl der Veranlagungen verlaufen relativ gleichmässig. Die grössten Schwankungen seit 2009 zeigt das Reinvermögen, das seitdem nominal 16,3% gewachsen ist. Das Reineinkommen stieg um 12,2%. Der Ertrag aus Einkommens- und Vermögenssteuer lag 2018 um 8,9% über dem Wert von 2009. Der grössere Anstieg des Reinvermögens zwischen 2011 und 2014 sowie im Jahr 2016 lag unter anderem am steigenden Wert von Kapitalanlagen bzw. Wertschriften.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen, Bevölkerung und Summe von Reineinkommen, -vermögen und Steuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09318",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-2",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:35",
		"id": 9318
	},
	{
		"template": "line001_print",
		"data-id": 9319,
		"chart-id": 9319,
		"filter": "",
		"parentId": "6900",
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Mittelwert und Median des Reineinkommens pro Veranlagung bewegen sich relativ konstant. Im Jahr 2018 beträgt der Mittelwert rund 69 800 Franken (+7,1% seit 2009, +0,6% gegenüber 2017), der Median ca. 49 700 Franken (+3,5% seit 2009, +0,2% gegenüber 2017). Der Ertrag aus Einkommenssteuer 2018 beträgt 1,152 Mrd. Franken (+2,1% gegenüber dem Vorjahr und +8,8% gegenüber dem Jahr 2009).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09319",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-3",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:36",
		"id": 9319
	},
	{
		"template": "line001_print",
		"data-id": 9320,
		"chart-id": 9320,
		"filter": "",
		"parentId": "6901",
		"children": [],
		"title": "Mittelwert des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "In den meisten Wohnvierteln ist ein Anstieg des Mittelwertes pro Veranlagung im Vergleich zum Steuerjahr 2009 zu verzeichnen. Am relativ stärksten fällt er in den Wohnvierteln Rosental und Wettstein mit jeweils über 18% aus; in der Gemeinde Bettingen beträgt die Steigerung 43,2%. Der Mittelwert aller Veranlagungen im Kanton stieg um 7,1%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09320",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-4",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:37",
		"id": 9320
	},
	{
		"template": "line001_print",
		"data-id": 9321,
		"chart-id": 9321,
		"filter": "",
		"parentId": "6902",
		"children": [],
		"title": "Median des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "Der Median des Reineinkommens pro Veranlagung ist zwischen 2009 und 2018 in den meisten Wohnvierteln gewachsen. Den stärksten relativen Zuwachs gibt es im Wohnviertel Vorstädte (+12,8%) und in Bettingen (+16,2%). Den grössten Rückgang verzeichnet das Wohnviertel Klybeck (-7,5%). Der Median aller Veranlagungen im gesamten Kanton stieg um 3,5%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09321",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-5",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:37",
		"id": 9321
	},
	{
		"template": "line001_print",
		"data-id": 9322,
		"chart-id": 9322,
		"filter": "",
		"parentId": "6903",
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens, Summe des Ertrags aus Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Median des Reinvermögens ist seit 2009 relativ stetig gestiegen, insgesamt um 53,6%, von rund 12 500 auf 19 200 Franken. Der Mittelwert und der Ertrag aus Vermögenssteuer zeigen im Zeitverlauf etwas grössere Schwankungen. Im Vergleich zum Vorjahr sind die Werte zurückgegangen, der Mittelwert um 3,6%, der Ertrag um 2,3% und der Median um 4,2%. Der Anstieg des Medians über die Jahre ist ein Indikator dafür, dass sich die tieferen Vermögen allgemein insgesamt positiv entwickelt haben. Allerdings sind die Werte des Medians im Vergleich zum Mittelwert des Reinvermögens auf einem deutlich niedrigeren Niveau.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reinvermögens, Summe des Ertrags aus Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09322",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-6",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:38",
		"id": 9322
	},
	{
		"template": "line001_print",
		"data-id": 9323,
		"chart-id": 9323,
		"filter": "",
		"parentId": "6904",
		"children": [],
		"title": "Mittelwert des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "Den höchsten Mittelwert des Reinvermögens pro Veranlagung weist im Jahr 2018 mit ca. 2,3 Mio. Franken die Gemeinde Bettingen auf, gefolgt vom Wohnviertel Vorstädte mit rund 1,5 Mio. Franken. 2009 lag der höchste Wert im Wohnviertel Bruderholz",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09323",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-7",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:38",
		"id": 9323
	},
	{
		"template": "line001_print",
		"data-id": 9324,
		"chart-id": 9324,
		"filter": "",
		"parentId": "6905",
		"children": [],
		"title": "Median des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "Der höchste Median des Reinvermögens 2018 wird mit rund 92 000 Franken in der Einwohnergemeinde Bettingen verzeichnet. Auch 2009 wurde der höchste Wert dort registriert.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09324",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-8",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:38",
		"id": 9324
	},
	{
		"template": "line001_print",
		"data-id": 9325,
		"chart-id": 9325,
		"filter": "",
		"parentId": "6906",
		"children": [],
		"title": "Ertrag aus  Einkommens- und Vermögensssteuer",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "Die einzelnen Wohnviertel und Gemeinden tragen unterschiedlich zum Steuerertrag des Kantons bei. Dies liegt einerseits an der grösseren Anzahl an Steuerpflichtigen (zum Beispiel Gundeldingen, St. Johann, Riehen), andererseits am höheren durchschnittlichen Ertrag pro Veranlagung (zum Beispiel Bruderholz oder St. Alban). In den meisten Wohnvierteln bzw. Gemeinden fällt der Steuerertrag beider Steuerarten 2018 höher aus als 2009. Der höchste Betrag an Einkommenssteuer liegt 2018 in Riehen vor (einschliesslich Gemeindesteuer), er beträgt rund 150 Mio. Franken. Der höchste Wert für die Vermögenssteuer liegt mit ca. 49 Mio. Franken im Wohnviertel Bruderholz vor.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ertrag aus  Einkommens- und Vermögensssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09325",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-9",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-25T08:16:13",
		"id": 9325
	},
	{
		"template": "befragungen001_print",
		"data-id": 9326,
		"chart-id": 9326,
		"filter": "",
		"parentId": "6907",
		"children": [],
		"title": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"subtitle": "in Franken, Basel-Stadt, 2018",
		"lesehilfe": "Bei 25,2% aller Veranlagungen (ca. 29 000) beträgt das steuerbare Einkommen 0 Franken, somit muss keine Einkommenssteuer bezahlt werden. Fast gleich viele Veranlagungen (24,6%) liegen in der Gruppe mit einem steuerbaren Einkommen von 1 bis 24 999 Franken vor. Der Einkommenssteuerertrag beträgt zusammen rund 78 Mio. Franken. Dies sind 6,8% des gesamten Einkommenssteuerertrags. Von Veranlagungen mit einem steuerbaren Einkommen von 200 000 Franken und mehr (ca. 3 600 oder 3,1% aller Veranlagungen) stammt ein Einkommenssteuerertrag von rund 319 Mio. Franken (27,7% des Einkommenssteuertrags). Insgesamt stammen aus 10,7% der Veranlagungen 49,4% der Einkommenssteuer.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09326",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-10",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:33",
		"id": 9326
	},
	{
		"template": "befragungen001_print",
		"data-id": 9327,
		"chart-id": 9327,
		"filter": "",
		"parentId": "6908",
		"children": [],
		"title": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"subtitle": "in Franken, Basel-Stadt, 2018",
		"lesehilfe": "Bei der Vermögenssteuer sind die Anteile der Vermögensklassen weniger gleichmässig verteilt als bei der Einkommenssteuer. Bei 69,8% aller Veranlagungen (ca. 81 000) betrug das steuerbare Vermögen 0 Franken, somit musste keine Vermögenssteuer bezahlt werden. Bei rund 3 100 Veranlagungen (2,7%) mit einem steuerbaren Vermögen von 2 Mio. Franken und mehr betrug die Vermögenssteuer insgesamt rund 195 Mio. Franken (76,8% des gesamten Vermögenssteuerertrags). Von knapp 90% aller Veranlagungen (Vermögenssklassen von 0 bis 499 999 Franken) stammen insgesamt rund 6% des Vermögenssteuerertrags des Steuerjahres 2018. Aus ca. 10% der Veranlagungen stammen insgesamt rund 94% der Vermögenssteuer.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09327",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-11",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:34",
		"id": 9327
	},
	{
		"template": "line001_print",
		"data-id": 9328,
		"chart-id": 9328,
		"filter": "",
		"parentId": "6909",
		"children": [],
		"title": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt, 2009 und 2018",
		"lesehilfe": "Den höchsten Ertrag aus Einkommens- und Vermögenssteuer 2018 verzeichnet die Gemeinde Riehen mit rund 190 Mio. Franken (+7,8% gegenüber 2009), gefolgt vom Wohnviertel St. Alban mit ca. 147 Mio. Franken (+20,0%). Den kleinsten Ertrag steuert Kleinhüningen mit 8,1 Mio. Franken bei (+12,7%). Im Jahr 2018 beträgt der Wert für den gesamten Kanton rund 1,4 Mrd. Franken, 8,9% mehr als 2009.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09328",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-12",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:34",
		"id": 9328
	},
	{
		"template": "line001_print",
		"data-id": 9329,
		"chart-id": 9329,
		"filter": "",
		"parentId": "6910",
		"children": [],
		"title": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Seit dem Jahr 2009 liegt jedes Jahr ein positiver Saldo des Steuerertrags von Zuzügern und Wegzügern vor. 2018 betrug dieser 12,3 Mio. Franken. Sowohl bei der Einkommenssteuer (rund 11,8 Mio. Franken) als auch bei der Vermögenssteuer (600 000 Franken) wurde ein Plus verzeichnet. Von Zuzügern lagen für das Steuerjahr 2018 rund 5 300 Veranlagungen vor, von Wegzügern des Vorjahres 4 200 Veranlagungen. Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen.",
		"erlaeuterungen": "Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen. Die Analyse der Effekte auf den Ertrag aus Einkommens- und Vermögenssteuer durch Zu- und Abwanderung im Kanton Basel-Stadt wird durch verschiedene methodische Aspekte erschwert. Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Für die Zugezogenen und die ganzjährig Niedergelassenen sind die Steuerdaten des Berichtsjahres vorhanden und wurden für die Analyse verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09329",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "3-1",
		"stufe1": "Wanderung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:39",
		"id": 9329
	},
	{
		"template": "template001_print",
		"data-id": 9330,
		"chart-id": 9330,
		"filter": "",
		"parentId": "6911",
		"children": [],
		"title": "Quellensteuerertrag",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Bei der Quellensteuer liegen die Daten bereits für das Jahr 2019 vor. Im Vergleich mit dem Jahr 2010 hat sowohl die Anzahl Veranlagungen als auch der Ertrag aus Quellensteuer von in Basel-Stadt wohnhaften Personen stark zugenommen. 2019 beträgt der Quellensteuerertrag rund 496 Mio. Franken (einschliesslich Auswärtige). Die meisten Veranlagungen liegen 2019 im Wohnviertel Matthäus vor (von ca. 2 300 Personen; bei mehreren Quellensteuerveranlagungen pro Person wurden diese zu einer zusammgefasst). Der höchste Ertrag wird im Wohnviertel St. Alban mit 34,3 Mio. Franken verzeichnet. Von Personen, die nicht im Kanton Basel-Stadt wohnen, stammen rund 197 Mio. Franken Quellensteuern.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Daten aus der Quellenbesteuerung in Basel-Stadt.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quellensteuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09330",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "4-1",
		"stufe1": "Quellensteuer",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:40",
		"id": 9330
	},
	{
		"template": "template001_print",
		"data-id": 9331,
		"chart-id": 9331,
		"filter": "",
		"parentId": "6912",
		"children": [],
		"title": "Quellensteuerertrag nach Status",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Die bedeutendsten Erträge aus Quellenbesteuerung stammen aus Erwerbseinkommen, 2019 sind dies rund 345 Mio. Franken (+69,3% gegenüber 2010). Der Ertrag der Grenzgänger aus Deutschland u. a. (einschliesslich einige wenige aus anderen Staaten) beträgt 2019 insgesamt 90,4 Mio. Franken (+31,7% gegenüber 2010). Die meisten Grenzgänger aus Frankreich zahlen keine direkte Quellensteuer in Basel-Stadt – der Fiskalausgleich, den es aus Frankreich für sie gibt, ist der Vollständigkeit halber aufgeführt (74,0 Mio. Franken, +14,9% gegenüber 2010). Eine gewisse Bedeutung haben auch die Quellensteuererträge, die aufgrund von Kapitalleistungen anfallen. 2019 betragen sie insgesamt 31,9 Mio. Franken. In den meisten Kategorien hat auch die Anzahl der Veranlagungen seit 2010 stark zugenommen, beispielsweise beim Erwerb von rund 21 200 auf fast 34 300 (+61,7%). Insgesamt beträgt der Quellensteuerertrag 2019 rund 496 Mio. Franken, 65,4% mehr als 2010 und 12,1% mehr als im Jahr 2018.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Daten aus der Quellenbesteuerung in Basel-Stadt.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quellensteuerertrag nach Status",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09331",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "4-2",
		"stufe1": "Quellensteuer",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:40",
		"id": 9331
	},
	{
		"template": "mappie002_print",
		"data-id": 9332,
		"chart-id": 9332,
		"filter": "",
		"parentId": "6980",
		"children": [],
		"title": "Mittelwert des Gesamtsteuerertrags sowie Anteil von Einkommens- und Vermögenssteuerertrag",
		"subtitle": "in Franken, Basel-Stadt, 2018",
		"lesehilfe": "Der Mittelwert des Gesamtsteuerertrags pro Veranlagung im Jahr 2018 fällt in den hell gefärbten Wohnvierteln eher niedrig aus, in den dunkleren eher hoch. St. Alban, Bruderholz und Riehen tragen die höchsten Summen zum Gesamtertrag des Kantons bei. Die Grösse der Kreise symbolisiert jeweils die Höhe des Steuerertrags. Eher klein fällt der Gesamtertrag in den Wohnvierteln Kleinhüningen, Clara oder Altstadt Kleinbasel aus. Der Anteil an Vermögenssteuer ist zum Beispiel im Wohnviertel Bruderholz besonders ausgeprägt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen, ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert des Gesamtsteuerertrags sowie Anteil von Einkommens- und Vermögenssteuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09332",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2-13",
		"stufe1": "Ordentliche Veranlagung natürlicher Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_013",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:35",
		"id": 9332
	},
	{
		"template": "template001_print",
		"data-id": 9333,
		"chart-id": 9333,
		"filter": "",
		"parentId": "6981",
		"children": [],
		"title": "Gewinn-, Kapital- und Grundstücksteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Für die juristischen Personen liegen die neuesten Daten für das Steuerjahr 2017 vor. Zuletzt beträgt dieser Steuerertrag von ihnen bei insgesamt rund 11 700 Veranlagungen zusammen 520 Mio. Franken. Die bedeutendste Steuerart, die Gewinnsteuer, trug 379 Mio. dazu bei. Kapitalsteuer wurden rund 123 Mio. Franken entrichtet, Grundstücksteuer 17,1 Mio. Franken. Der Gesamtertrag schwankt teilweise von Jahr zu Jahr – insgesamt ging er um 30,7% zurück (im Jahr 2008 war die Gewinnsteuer vergleichsweise hoch). Im Vergleich zum Vorjahr ging der Ertrag im Steuerjahr 2017 um 26,9% zurück. Auch im Steuerjahr 2016 war die Gewinnsteuer relativ hoch ausgefallen.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gewinn-, Kapital- und Grundstücksteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09333",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "5-1",
		"stufe1": "Juristische Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:41",
		"id": 9333
	},
	{
		"template": "befragungen001_print",
		"data-id": 9334,
		"chart-id": 9334,
		"filter": "",
		"parentId": "6982",
		"children": [],
		"title": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"subtitle": "in Franken, Basel-Stadt, 2017",
		"lesehilfe": "Im Jahr 2017 gibt es insgesamt 11 697 Veranlagungen von juristischen Personen im Kanton Basel-Stadt. 1 292 (11,0%) von ihnen müssen keine Gewinn-, Kapital- oder Grundstücksteuer bezahlen. Bei der grossen Mehrheit ( rund 7 300 Veranlagungen bzw. 62,6%) liegt der Steuerbetrag zwischen 1 und 4 999 Franken, der Ertrag beläuft sich insgesamt auf 7,2 Mio. Franken. In der obersten Kategorie – mit einem Steuerbetrag von über 1 Mio. Franken pro Veranlagung – gibt es 68 Veranlagungen (0,6% von allen), deren Steuerbetrag ca. 349 Mio. Franken (67,2% des gesamten Steuerertrags der juristischen Personen) beträgt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09334",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "5.2",
		"stufe1": "Juristische Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:40",
		"id": 9334
	},
	{
		"template": "befragungen001_print",
		"data-id": 9335,
		"chart-id": 9335,
		"filter": "",
		"parentId": "6983",
		"children": [],
		"title": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"subtitle": "in Franken, Basel-Stadt, 2017",
		"lesehilfe": "Mehr als die Hälfte (57,6%) der juristischen Personen weisen 2017 einen steuersatzbestimmenden Gewinn von 0 Franken auf. Juristische Personen, die keine Gewinnsteuer entrichten müssen, zahlen in der Regel als Alternativsteuer die Grundstücksteuer. Von diesen stammen insgesamt 41,4 Mio. Franken, dies sind 8,0% des Gesamtertrags. Am anderen Ende tragen insgesamt 559 Veranlagungen von juristischen Personen (4,8%) mit einem satzbestimmenden Gewinn von über 1 Mio. Franken einen Steuerbetrag von zusammen 413 Mio. Franken bei (79,4% der gesamten Steuer der juristischen Personen).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09335",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "5-3",
		"stufe1": "Juristische Personen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-10T09:47:41",
		"id": 9335
	}
];