var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 11187,
		"chart-id": 11187,
		"filter": "",
		"parentId": "8458",
		"children": [],
		"title": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"subtitle": "in Stunden pro Woche, Basel-Stadt",
		"lesehilfe": "Im Jahr 2020 wendete eine Person im Kanton Basel-Stadt durchschnittlich 23,4 Stunden pro Woche für Haus- und Familienarbeit auf. Frauen investierten mit 28,3 Stunden mehr Zeit in die Haus- und Familienarbeit als Männer mit 18,8 Stunden.",
		"erlaeuterungen": "Die vorliegenden Ergebnisse beruhen auf Hochrechnungen auf Basis eines Stichprobenumfangs von etwa 500 Personen für den Kanton Basel-Stadt und sind folglich mit einer gewissen Ungenauigkeit verbunden. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik, Schweizerische Arbeitskräfteerhebung (SAKE), Modul 'Unbezahlte Arbeit'"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Unbezahlte Arbeit",
		"kuerzel": "I.03.6.10027",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.4.1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.4 Unbezahlte Arbeit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-31T11:27:07",
		"id": 11187
	},
	{
		"template": "template001_print",
		"data-id": 11188,
		"chart-id": 11188,
		"filter": "",
		"parentId": "10028",
		"children": [],
		"title": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"subtitle": "in Stunden pro Woche, Basel-Landschaft",
		"lesehilfe": "Im Jahr 2020 wendete eine Person im Kanton Basel-Landschaft durchschnittlich 25,8 Stunden pro Woche für Haus- und Familienarbeit auf. Frauen investierten mit 31,1 Stunden mehr Zeit in die Haus- und Familienarbeit als Männer mit 19,8 Stunden.",
		"erlaeuterungen": "Die vorliegenden Ergebnisse beruhen auf Hochrechnungen auf Basis eines Stichprobenumfangs von etwa 700 Personen für den Kanton Basel-Landschaft und sind folglich mit einer gewissen Ungenauigkeit verbunden. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik, Schweizerische Arbeitskräfteerhebung (SAKE), Modul 'Unbezahlte Arbeit'"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Unbezahlte Arbeit",
		"kuerzel": "I.03.6.10028",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.4.2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.4 Unbezahlte Arbeit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-31T11:27:07",
		"id": 11188
	},
	{
		"template": "template001_print",
		"data-id": 11189,
		"chart-id": 11189,
		"filter": "",
		"parentId": "10029",
		"children": [],
		"title": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"subtitle": "in Stunden pro Woche, Jura",
		"lesehilfe": "Im Jahr 2020 wendete eine Person im Kanton Jura durchschnittlich 24,9 Stunden pro Woche für Haus- und Familienarbeit auf. Frauen investierten mit 29,2 Stunden mehr Zeit in die Haus- und Familienarbeit als Männer mit 20,2 Stunden. Allerdings sind die Werte im Jahr 2020 und 2007 nicht statistisch signifikant verschieden voneinander.",
		"erlaeuterungen": "Die vorliegenden Ergebnisse beruhen auf Hochrechnungen auf Basis eines Stichprobenumfangs von etwa 200 Personen für den Kanton Jura und sind folglich mit einer gewissen Ungenauigkeit verbunden. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik, Schweizerische Arbeitskräfteerhebung (SAKE), Modul 'Unbezahlte Arbeit'"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Unbezahlte Arbeit",
		"kuerzel": "I.03.6.10029",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.4.3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.4 Unbezahlte Arbeit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-31T11:27:07",
		"id": 11189
	},
	{
		"template": "template001_print",
		"data-id": 11190,
		"chart-id": 11190,
		"filter": "",
		"parentId": "10030",
		"children": [],
		"title": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"subtitle": "in Stunden pro Woche, BS/BL/JU",
		"lesehilfe": "Im Jahr 2020 wendete eine Person in den Kantonen Basel-Stadt, Basel-Landschaft und Kanton Jura durchschnittlich 24,8 Stunden pro Woche für Haus- und Familienarbeit auf. Frauen investierten mit 29,9 Stunden mehr Zeit in die Haus- und Familienarbeit als Männer mit 19,4 Stunden.",
		"erlaeuterungen": "Die vorliegenden Ergebnisse beruhen auf Hochrechnungen auf Basis eines Stichprobenumfangs von etwa 1400 Personen für die Kantone Basel-Stadt, Basel-Landschaft und Jura zusammen und sind folglich mit einer gewissen Ungenauigkeit verbunden. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik, Schweizerische Arbeitskräfteerhebung (SAKE), Modul 'Unbezahlte Arbeit'"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittlicher Zeitaufwand für Haus- und Familienarbeit",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Unbezahlte Arbeit",
		"kuerzel": "I.03.6.10030",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.4.4",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.4 Unbezahlte Arbeit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-31T11:27:07",
		"id": 11190
	},
	{
		"template": "template001_print",
		"data-id": 8467,
		"chart-id": 8467,
		"filter": "",
		"parentId": "8350",
		"children": [],
		"title": "Bruttoinlandprodukt",
		"subtitle": "total in Mrd. Franken, 2021",
		"lesehilfe": "Das grösste nominale Bruttoinlandprodukt (BIP) der betrachteten Kantone erwirtschaftete im Jahr 2021 Basel-Stadt mit 41,0 Mrd. Franken, gefolgt von Basel-Landschaft mit 22,4 und Jura mit 5,2 Mrd. Franken.",
		"erlaeuterungen": "Werte für 2021 provisorisch.<br>Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Es wird das nominale BIP ausgewiesen (zu laufenden Preisen). <br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoinlandprodukt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.1.1",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-08-22T08:24:06",
		"id": 8467
	},
	{
		"template": "template001_print",
		"data-id": 8468,
		"chart-id": 8468,
		"filter": "",
		"parentId": "8351",
		"children": [],
		"title": "Bruttoinlandprodukt pro Kopf",
		"subtitle": "in Franken, 2021",
		"lesehilfe": "Mit über 210 000 Franken pro Kopf im Jahr 2021 weist der Kanton Basel-Stadt das höchste nominale Bruttoinlandprodukt pro Kopf der Schweiz auf. Basel-Landschaft kommt auf rund 77 200 Franken, Jura auf 70 200 Franken. Der Durchschnittswert für die gesamte Schweiz liegt bei rund 85 700 Franken.",
		"erlaeuterungen": "Werte für 2021 provisorisch.<br>Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Es wird das nominale BIP ausgewiesen (zu laufenden Preisen).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoinlandprodukt pro Kopf",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.1.2",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-14T08:05:26",
		"id": 8468
	},
	{
		"template": "line001_print",
		"data-id": 8469,
		"chart-id": 8469,
		"filter": "",
		"parentId": "8352",
		"children": [],
		"title": "Entwicklung Bruttoinlandprodukt",
		"subtitle": "real; indexiert (2014 = 100)",
		"lesehilfe": "Die grösste Steigerung des realen Bruttoinlandprodukts zwischen 2014 und 2021 weist Basel-Stadt mit 34,7% auf, gefolgt vom Kanton Jura mit 7,3% und Basel-Landschaft mit 5,2%. In der gesamten Schweiz stieg der Wert um 5,9%.",
		"erlaeuterungen": "Werte für 2021 provisorisch.<br>Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Grundlage für die Indexierung sind die Werte des realen BIP (zu Preisen des Vorjahres).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Bruttoinlandprodukt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.1.3",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:22",
		"id": 8469
	},
	{
		"template": "line001_print",
		"data-id": 8470,
		"chart-id": 8470,
		"filter": "",
		"parentId": "8353",
		"children": [],
		"title": "Entwicklung Bruttoinlandprodukt pro Kopf",
		"subtitle": "real; indexiert (2014 = 100)",
		"lesehilfe": "Die grösste Steigerung des realen Bruttoinlandprodukts pro Kopf zwischen 2014 und 2021 weist Basel-Stadt mit 40,0% auf. Im Kanton Jura beträgt der Zuwachs 10,2% und im Kanton Basel-Landschaft 9,8%. In der gesamten Schweiz stieg der Wert um 12,8%.",
		"erlaeuterungen": "Werte für 2021 provisorisch.<br>Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Grundlage für die Indexierung sind die Werte des realen BIP (zu Preisen des Vorjahres).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Bruttoinlandprodukt pro Kopf",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.1.4",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:23",
		"id": 8470
	},
	{
		"template": "template001_print",
		"data-id": 8471,
		"chart-id": 8471,
		"filter": "",
		"parentId": "8354",
		"children": [],
		"title": "Anteile Wertschöpfung nach Branche",
		"subtitle": "Anteile an der Gesamtwertschöpfung, 2021",
		"lesehilfe": "In Basel-Stadt erwirtschaften 2021 die Branchen Chemie und Pharma 39% der kantonalen Wertschöpfung. In Basel-Landschaft hat der Bereich Handel und Reparatur mit rund 20% den grössten Anteil. Im Kanton Jura sind wiederum die Hersteller von Investitionsgütern am stärksten vertreten (36% der Wertschöpfung). Diese Branche ist in Basel-Stadt fast bedeutungslos, in Basel-Landschaft erwirtschaftet sie rund 9%. In der gesamten Region (BS, BL, JU) trägt die chemisch-pharmazeutische Industrie am meisten zur Gesamtwertschöpfung bei (27%). An zweiter Stelle folgt der Handel (12%).",
		"erlaeuterungen": "Die Anteile errechnen sich aus der jeweiligen nominalen Bruttowertschöpfung der Branche geteilt durch die Gesamtwertschöpfung in der jeweiligen Region.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteile Wertschöpfung nach Branche",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08471",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.1",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-20T07:36:46",
		"id": 8471
	},
	{
		"template": "line001_print",
		"data-id": 8472,
		"chart-id": 8472,
		"filter": "",
		"parentId": "8355",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Die reale Wertschöpfung in der Pharmaindustrie in Basel-Stadt hat sich seit 2014 mehr als verdoppelt. Die Wertschöpfung im Gesundheits- und Sozialwesen ist im gleichen Zeitraum um rund 16% gestiegen. Das Gastgewerbe sowie der Bereich Verkehr und Lagerei haben im ersten Pandemiejahr 2020 die deutlichsten Wertschöpfungseinbussen erlitten. Im Jahr 2021 konnten sie sich leicht erholen.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahres gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08472",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.2",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-13T09:15:55",
		"id": 8472
	},
	{
		"template": "line001_print",
		"data-id": 8473,
		"chart-id": 8473,
		"filter": "",
		"parentId": "8356",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Landschaft",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Seit 2014 hat sich auch in Basel-Landschaft die Wertschöpfung der Pharmaindustrie mehr als verdoppelt und die Wertschöpfung in der Chemischen Industrie hat um fast 60% zugenommen. Im ersten Pandemiejahr 2020 ist die Wertschöpfung vor allem im Gastgewerbe und im Bereich Verkehr und Lagerei eingebrochen.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Landschaft",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08473",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.3",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:56",
		"id": 8473
	},
	{
		"template": "line001_print",
		"data-id": 8474,
		"chart-id": 8474,
		"filter": "",
		"parentId": "8357",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Jura",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Im Pandemiejahr 2020 ist die Wertschöpfung in vielen Branchen im Kanton Jura gesunken. Am stärksten war auch hier das Gastgewerbe betroffen.Die Mehrheit der Branchen konnten im Jahr 2021 wieder eine Zunahme der realen Wertschöpfung verzeichnen.",
		"erlaeuterungen": "Das Wachstum de realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100). Aufgrund der sehr niedrigen Beschäftigtenzahlen sind für den Kanton Jura keine Wertschöpfungszahlen für die chemischen Industrie und für Pharma vorhanden.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Jura",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08474",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.4",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-30T08:51:10",
		"id": 8474
	},
	{
		"template": "line001_print",
		"data-id": 8475,
		"chart-id": 8475,
		"filter": "",
		"parentId": "8358",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, BS/BL/JU",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "In der Gesamtregion BS/BL/JU hat sich die reale Wertschöpfung in der Pharmaindustrie zwischen 2014 und 2021 mehr als verdoppelt. Deutlich zugenommen hat sie auch in der Chemischen Industrie (+48%), in Bereich der Finanz- und Versicherungsdienstleistungen (+19%) und im Gesundheits- und Sozialwesen (+17%). Stark rückläufig war die Wertschöpfung vor allem im Gastgewerbe, was auf den Einbruch 2020 zurückzuführen ist.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, BS/BL/JU",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08475",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.5",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-13T10:06:15",
		"id": 8475
	},
	{
		"template": "line001_print",
		"data-id": 8476,
		"chart-id": 8476,
		"filter": "",
		"parentId": "8359",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Schweiz",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "In der Schweiz hat sich reale Wertschöpfung in der Pharmabranche 2021 im Vergleich zum Jahr 2014 mehr als verdoppelt. In der Chemischen Industrie ist im gleichen Zeitraum die Wertschöpfung um gut 60% gewachsen. Stark rückläufig war die Wertschöpfung aufgrund des Einbruchs im Jahr 2020 vor allem im Gastgewerbe.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Schweiz",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08476",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2.6",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-13T10:06:15",
		"id": 8476
	},
	{
		"template": "template001_print",
		"data-id": 8477,
		"chart-id": 8477,
		"filter": "",
		"parentId": "8360",
		"children": [],
		"title": "Entwicklung Erwerbstätige",
		"subtitle": "",
		"lesehilfe": "Im Kanton Basel-Landschaft waren im Jahr 2021 rund 141 000 Einwohner erwerbstätig. Der Kanton Basel-Stadt verzeichnete im gleichen Jahr rund 96 000 Erwerbstätige. Zusammen mit den rund 34 000 Erwerbstätigen im Kanton Jura waren in den drei Kantonen insgesamt etwa 271 000 Personen erwerbstätig.",
		"erlaeuterungen": "Seit 2010 stammen die Daten zu den Erwerbstätigen aus der Strukturerhebung. Es handelt sich um eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Erwerbstätige",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08477",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-09-15T09:04:42",
		"id": 8477
	},
	{
		"template": "line001_print",
		"data-id": 8478,
		"chart-id": 8478,
		"filter": "",
		"parentId": "8361",
		"children": [],
		"title": "Entwicklung Grenzgänger",
		"subtitle": "indexiert (1. Quartal 2014 = 100)",
		"lesehilfe": "Alle betrachteten Kantone verzeichnen seit 2014 einen Anstieg an ausländischen Grenzgängern. Im Kanton Jura beträgt der Anstieg rund 60%, der Bestand im 2. Quartal 2023 liegt bei 11 100 Grenzgängern. Weniger stark gestiegen sind die Grenzgängerzahlen in Basel-Landschaft (+25% auf rund 24 400) und Basel-Stadt (+3% auf 34 600). In der gesamten Schweiz arbeiten im 2. Quartal 2023 rund 390 900 Grenzgänger, 37% mehr als im 1. Quartal 2014.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Das BFS schätzt die Zahl der aktiven Grenzgänger aufgrund Daten verschiedener Quellen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Grenzgänger",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.7",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:31",
		"id": 8478
	},
	{
		"template": "template001_print",
		"data-id": 8479,
		"chart-id": 8479,
		"filter": "",
		"parentId": "8362",
		"children": [],
		"title": "Grenzgänger",
		"subtitle": "2023, 2. Quartal",
		"lesehilfe": "Die meisten Grenzgänger arbeiten in Basel-Stadt, der Bestand im 2. Quartal 2023 beträgt rund 34 600. In Basel-Landschaft sind es 24 400, im Jura 11 100 Grenzgänger. In der gesamten Schweiz beträgt der Wert ca. 391 900.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Das BFS schätzt die Zahl der aktiven Grenzgänger aufgrund Daten verschiedener Quellen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Grenzgänger",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.5",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-14T08:05:27",
		"id": 8479
	},
	{
		"template": "template001_print",
		"data-id": 8480,
		"chart-id": 8480,
		"filter": "",
		"parentId": "8363",
		"children": [],
		"title": "Arbeitspendler Basel-Stadt",
		"subtitle": "Pooling 2017-2021",
		"lesehilfe": "Im Mittel der Jahre 2017 bis 2021 pendelten rund 92 200 Personen nach Basel-Stadt, um einer Erwerbstätigkeit nachzugehen. Die meisten von ihnen kommen aus dem Kanton Basel-Landschaft (ca. 39 600) oder aus dem Ausland (fast 35 000), vornehmlich aus Frankreich und Deutschland. Andere Schweizer Kantone spielen eine kleinere Rolle. 23 737 Personen aus Basel-Stadt arbeiten in anderen Kantonen oder im Ausland, fast 14 800 von ihnen in Basel-Landschaft.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2017 bis 2021, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2017-2021 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Basel-Stadt",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08480",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.9",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-20T04:19:21",
		"id": 8480
	},
	{
		"template": "template001_print",
		"data-id": 8481,
		"chart-id": 8481,
		"filter": "",
		"parentId": "8364",
		"children": [],
		"title": "Arbeitspendler Basel-Landschaft",
		"subtitle": "Pooling 2017-2021",
		"lesehilfe": "Im Kanton Basel-Landschaft gibt es im Mittel der Jahre 2017 bis 2021 etwas mehr Weg- als Zupendler (54 100 gegenüber rund 54 000). Die meisten Wegpendler arbeiten in Basel-Stadt, rund 39 600. Die meisten Zupendler kommen mit rund 22 300 Personen aus dem Ausland nach Basel-Landschaft, gefolgt von Basel-Stadt mit etwa 14 800 Arbeitskräften.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamt für Statistik (Durchschnitt der Jahre 2017 bis 2021, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2017-2021 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Basel-Landschaft",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08481",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.10",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-12T09:36:38",
		"id": 8481
	},
	{
		"template": "template001_print",
		"data-id": 8482,
		"chart-id": 8482,
		"filter": "",
		"parentId": "8365",
		"children": [],
		"title": "Arbeitspendler Jura",
		"subtitle": "Pooling 2017-2021",
		"lesehilfe": "Im Kanton Jura gibt es im Mittel der Jahre 2017 bis 2021 deutlich weniger Weg- und Zupendler als in den beiden Basler Kantonen. Rund 5 100 Personen aus dem Jura pendelten zum Arbeiten in einen anderen Kanton oder ins Ausland, die meisten von ihnen mit rund 2 900 in den Kanton Bern, gefolgt von Neuenburg mit etwa 1 000 Personen. Fast drei Viertel der restlichen Wegpendler arbeiten in den Kantonen Basel-Stadt, Basel-Landschaft und Solothurn. Die meisten der insgesamt rund 10 900 Zupendler, die zum Arbeiten in den Jura kommen, stammen mit etwa 8 600 Personen aus dem Ausland.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2017 bis 2021, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2017-2021 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Jura",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08482",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.11",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-12T09:36:39",
		"id": 8482
	},
	{
		"template": "template001_print",
		"data-id": 8483,
		"chart-id": 8483,
		"filter": "",
		"parentId": "8366",
		"children": [],
		"title": "Arbeitspendler BS/BL/JU",
		"subtitle": "Pooling 2017-2021",
		"lesehilfe": "Fasst man die drei Kantone Basel-Stadt, Basel-Landschaft und Jura zusammen, so pendeln im Mittel der Jahre 2017 bis 2021 insgesamt rund 27 803 Personen zur Arbeit aus diesem Gebiet weg, 102 022 kommen von auswärts an ihren Arbeitsplatz. Mit 9 131 Personen pendelt die grösste Gruppe in den Aargau. Bei den Zupendlern kommt die grosse Mehrheit mit rund 65 578 Arbeitskräften aus dem Ausland.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2017 bis 2021, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2017-2021 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler BS/BL/JU",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08483",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.12",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-20T04:19:20",
		"id": 8483
	},
	{
		"template": "template001_print",
		"data-id": 8484,
		"chart-id": 8484,
		"filter": "",
		"parentId": "8367",
		"children": [],
		"title": "Arbeitspendler",
		"subtitle": "Pooling 2017-2021",
		"lesehilfe": "Der durchschnittliche jährliche Saldo aus Zu- und Wegpendlern der Jahre 2017 bis 2021 ist für Basel-Stadt (+68 489) und Jura (+5 801) positiv, für Basel-Landschaft (-70) negativ. Werden die drei Kantone zusammen betrachtet, gibt es rund 74 220 mehr Zu- als Wegpendler.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2017 bis 2021, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2017 bis 2021 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2017-2021 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08484",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.8",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-20T04:19:21",
		"id": 8484
	},
	{
		"template": "template001_print",
		"data-id": 8485,
		"chart-id": 8485,
		"filter": "",
		"parentId": "8368",
		"children": [],
		"title": "Entwicklung Tertiärquote",
		"subtitle": "",
		"lesehilfe": "Der Anteil von Personen, die einen Bildungsabschluss auf Niveau Tertiärstufe haben, liegt in Basel-Stadt am höchsten (2021: 52,5%). Basel-Landschaft liegt bei 41,8%, Jura bei 27,0%. Der Wert für die ganze Schweiz beträgt 40,7%.",
		"erlaeuterungen": "Der Indikator zeigt den prozentualen Anteil der Personen mit höchstem Bildungsabschluss Tertiärstufe an der ständigen Wohnbevölkerung ab 25 Jahren. Diese Altersgruppe hat in der Regel eine erste Ausbildung abgeschlossen und ist damit bereit für den Arbeitsmarkt. Personen mit einem Bildungsniveau auf Tertiärstufe haben eine höhere Berufsbildung oder eine Hochschule erfolgreich absolviert. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe von jährlich rund 5 000 in Basel-Stadt (7 000 in Basel-Landschaft, 2 000 in Jura) wohnhaften Personen ab 15 Jahren und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die <a href='http://www.statistik.bs.ch/grundlagen/glossar/?5b3731f0=true' target='_blank'>Konfidenzintervalle</a> auf dem 95%-Niveau. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Da die Frage zur höchsten abgeschlossenen Ausbildung im Fragebogen der Strukturerhebung 2020 verändert wurde, ist die Veränderung zwischen 2020 und den Vorjahren mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Tertiärquote",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.08485",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2.1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-26T08:26:31",
		"id": 8485
	},
	{
		"template": "template001_print",
		"data-id": 8486,
		"chart-id": 8486,
		"filter": "",
		"parentId": "8369",
		"children": [],
		"title": "Entwicklung Abschlussquote der Hochschulen",
		"subtitle": "",
		"lesehilfe": "Den höchsten Anteil neuer Absolventen weist 2022 mit 37,0% der Kanton Jura auf. In Basel-Stadt beträgt der Wert 25,3%, im Kanton Basel-Landschaft 34,7%. Im Schweizer Durchschnitt gibt es 32,6% neue Absolventen an den schweizerischen Hochschulen im Verhältnis zur gleichaltrigen Wohnbevölkerung.",
		"erlaeuterungen": "Anteil der neuen Absolventinnen und Absolventen: Lizenziat/Diplom UH, Diplom FH, Bachelor (UH, FH, PH) an den schweizerischen Hochschulen im Verhältnis zur gleichaltrigen Wohnbevölkerung. Rückwirkende Korrekturen sind möglich.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Bildungsperspektiven, Studierende und Abschlüsse der Hochschulen (SHIS-studex)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Abschlussquote der Hochschulen",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.08486",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2.2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-20T08:53:55",
		"id": 8486
	},
	{
		"template": "template001_print",
		"data-id": 8487,
		"chart-id": 8487,
		"filter": "",
		"parentId": "8370",
		"children": [],
		"title": "Exporte und Importe",
		"subtitle": "Anteil am nominalen BIP, 2021",
		"lesehilfe": "2021 betragen die Exporte aus Basel-Stadt 204,4% und die Importe 91,9% des kantonalen BIP. Beide Werte sind im regionalen Vergleich am höchsten. Die Exporte aus dem Kanton Basel-Landschaft entsprechen 28,0% des BIP; diejenige aus dem Jura betragen 49,9% des BIP. Der Wert der Exporte aus der Gesamtschweiz beträgt 35,5% des BIP.",
		"erlaeuterungen": "Nominaler Wert der Exporte und der Importe von Waren, Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten, im Verhältnis zum nominalen regionalen Bruttoinlandprodukt (BIP). Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"BAK Economics",
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Exporte und Importe",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08487",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.1",
		"stufe1": "3. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:06",
		"id": 8487
	},
	{
		"template": "line001_print",
		"data-id": 8488,
		"chart-id": 8488,
		"filter": "",
		"parentId": "8371",
		"children": [],
		"title": "Entwicklung Exporte",
		"subtitle": "indexiert (2016 = 100)",
		"lesehilfe": "Von 2016 bis 2021 haben die nominalen Warenexporte aus Basel-Stadt um über 46% zugenommen. Von 2020 bis 2021 betrug der Zuwachs knapp 15%. Auch im Kanton Basel-Landschaft sowie im Kanton Jura gab es nach dem Exportrückgang im 2020 im letzten Jahr wieder ein Plus. Im Kanton Basel-Landschaft stiegen die Exporte leicht um 0,7%, im Jura um 29%. Somit liegen die nominalen Warenexporte aller drei Kantone höher als 2016. Für die gesamte Region BS/BL/Ju ergibt sich im Zeitraum 2016-2021 ein Wachstum von fast 41%, für die gesamte Schweiz von über 23%.",
		"erlaeuterungen": "Entwicklung des nominalen Werts der Warenexporte ins Ausland. Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten. Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Exporte",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08488",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.2",
		"stufe1": "3. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:07",
		"id": 8488
	},
	{
		"template": "line001_print",
		"data-id": 8489,
		"chart-id": 8489,
		"filter": "",
		"parentId": "8372",
		"children": [],
		"title": "Entwicklung Logiernächte",
		"subtitle": "indexiert, 2014 = 100",
		"lesehilfe": "Zwischen 2014 und 2022 haben die Logiernächte in Basel-Stadt zugenommen, insgesamt um 11,9%. In den Jahren 2020 und 2021 wurden im Kanton Basel-Stadt (46,9 bzw. 67,5 Indexpunkte) und Basel-Landschaft (47,9 bzw. 59,9 Indexpunkte) pandemiebedingte sehr tiefe Werte verzeichnet. Im Kanton Jura stieg 2022 die Zahl der Übernachtungen um 13,2%. Der Wert in Basel-Landschaft sank gegenüber 2014 um 25,7%. <br>Zu den Logiernächtezahlen und der Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten.",
		"erlaeuterungen": "Logiernächte der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.<br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Logiernächte",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.08489",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "5.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-03-24T08:55:29",
		"id": 8489
	},
	{
		"template": "template001_print",
		"data-id": 8490,
		"chart-id": 8490,
		"filter": "",
		"parentId": "8373",
		"children": [],
		"title": "Entwicklung Anzahl Logiernächte",
		"subtitle": "",
		"lesehilfe": "In den drei Kantonen Basel-Stadt, Basel-Landschaft und Jura wurden im Jahr 2022 zusammen rund 1,7 Mio. Logiernächte verzeichnet. Der grösste Teil fiel mit 1,3 Mio. auf die baselstädtischen Beherbergungsbetriebe. Im Kanton Basel-Landschaft wurden 230 000, im Jura 120 000 Logiernächte gebucht. 2020 wurde ein pandemiebedingter Rückgang auf knapp 800 000 Übernachtungen registriert.<br>Zu den Logiernächtezahlen und der Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten.",
		"erlaeuterungen": "Logiernächte der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.<br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Anzahl Logiernächte",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.08490",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "5.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-03-10T01:29:33",
		"id": 8490
	},
	{
		"template": "line001_print",
		"data-id": 8491,
		"chart-id": 8491,
		"filter": "",
		"parentId": "8431",
		"children": [],
		"title": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre; BS, BL und JU",
		"subtitle": "indexiert (2014 = 100)",
		"lesehilfe": "Im regionalen Vergleich BS/BL/JU hat die 15- bis 64-jährige Wohnbevölkerung zwischen 2014 und 2022 in den Kantonen Basel-Stadt (+2,7%) und Basel-Landschaft zugenommen (+1,0%). Im Kanton Jura ist sie zurückgegangen (-0,9%).",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08491",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:37",
		"id": 8491
	},
	{
		"template": "line001_print",
		"data-id": 8492,
		"chart-id": 8492,
		"filter": "",
		"parentId": "8432",
		"children": [],
		"title": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre, BS/BL/JU und Schweiz",
		"subtitle": "indexiert (2014 = 100)",
		"lesehilfe": "In der Gesamtschweiz nahm die Zahl der 15- bis 64-Jährigen zwischen 2014 und 2022 um 4,5%, in der Region BS/BL/JU um 1,4% zu.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre, BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08492",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:38",
		"id": 8492
	},
	{
		"template": "template001_print",
		"data-id": 8493,
		"chart-id": 8493,
		"filter": "",
		"parentId": "8433",
		"children": [],
		"title": "Altersklassen von 15 bis 64 Jahren; BS, BL und JU",
		"subtitle": "Anteil an der Gesamtbevölkerung, 2022",
		"lesehilfe": "Die Altersklassen zwischen 15 und 64 Jahren weisen regional unterschiedliche Anteile an der jeweiligen Gesamtbevölkerung auf. So leben in Basel-Stadt vergleichsweise wenige Jugendliche und junge Erwachsene. Die 25- bis 44-Jährigen sind hingegen überdurchschnittlich vertreten. In den höheren Altersklassen ab 45 Jahren gleichen sich die Anteile wieder an, wobei der Kanton Basel-Landschaft bei den Altersklassen ab 45 Jahren insgesamt höhere Anteile aufweist.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Altersklassen von 15 bis 64 Jahren; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08493",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:38",
		"id": 8493
	},
	{
		"template": "template001_print",
		"data-id": 8494,
		"chart-id": 8494,
		"filter": "",
		"parentId": "8434",
		"children": [],
		"title": "Altersklassen von 15 bis 64 Jahren; BS/BL/JU und Schweiz",
		"subtitle": "Anteil an der Gesamtbevölkerung, 2022",
		"lesehilfe": "Die Anteile der Altersklassen der 15- bis 54-Jährigen an der Gesamtbevölkerung sind in der Region BS/BL/JU leicht niedriger als in der Gesamtschweiz.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Altersklassen von 15 bis 64 Jahren; BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08494",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.4",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:39",
		"id": 8494
	},
	{
		"template": "line001_print",
		"data-id": 8495,
		"chart-id": 8495,
		"filter": "",
		"parentId": "8435",
		"children": [],
		"title": "Entwicklung Altersquotient; BS, BL und JU",
		"subtitle": "Verhältnis der über 64-Jährigen zu den 20- bis 64-Jährigen",
		"lesehilfe": "Der Kanton Basel-Landschaft weist im Jahr 2022 mit 39,5 den höchsten Altersquotienten der Region BS/BL/JU auf, gefolgt von Jura (38,4) und Basel-Stadt (31,5). Während die Altersquotienten in den Kantonen Basel-Landschaft und Jura seit 2014 gestiegen sind, ist der Altersquotient in Basel-Stadt zurückgegangen.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember. Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Altersquotient; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08495",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.5",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:40",
		"id": 8495
	},
	{
		"template": "template001_print",
		"data-id": 8496,
		"chart-id": 8496,
		"filter": "",
		"parentId": "8436",
		"children": [],
		"title": "Entwicklung Altersquotient; BS/BL/JU und Schweiz",
		"subtitle": "Verhältnis der über 64-Jährigen zu den 20- bis 64-Jährigen",
		"lesehilfe": "Die Region BS/BL/JU weist mit 36,4 einen höheren Altersquotienten auf als die Gesamtschweiz (31,5).",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember. Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Altersquotient; BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08496",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3.6",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:41",
		"id": 8496
	},
	{
		"template": "template001_print",
		"data-id": 8497,
		"chart-id": 8497,
		"filter": "",
		"parentId": "8437",
		"children": [],
		"title": "Neugegründete Unternehmen",
		"subtitle": "2015-2020",
		"lesehilfe": "Über die Jahre 2015 bis 2020 sind in der Region BS/BL/JU insgesamt rund 14 300 neue Unternehmen gegründet worden – davon ca. 6 500 in Basel-Stadt, ca.6 200 in Basel-Landschaft und rund 1 700 im Jura. Der überwiegende Teil der Neugründungen ist im Dienstleistungssektor angesiedelt. Deren Anteil bewegt sich zwischen 90% in Basel-Stadt und 81% im Jura.",
		"erlaeuterungen": "Erfasst werden nur tatsächlich neu entstandene Unternehmen (d. h. keine Berücksichtigung von neuen Unternehmen aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen) mit marktwirtschaftlicher Tätigkeit (ohne Holdinggesellschaften) im Industrie- und Dienstleistungssektor.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neugegründete Unternehmen",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Neugründungen",
		"kuerzel": "I.06.2.08497",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.1",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:34",
		"id": 8497
	},
	{
		"template": "template001_print",
		"data-id": 8498,
		"chart-id": 8498,
		"filter": "",
		"parentId": "8438",
		"children": [],
		"title": "Beschäftigte nach Branche",
		"subtitle": "2021",
		"lesehilfe": "In Basel-Stadt sind rund 83% der Beschäftigten in einer Dienstleistungsbranche tätig und damit deutlich mehr als im Baselbiet (72%) oder im Jura (57%). Im Industriesektor ist für Basel-Stadt die Chemie- und Pharmabranche von besonderer Bedeutung. Die grösste Bedeutung hat der Industriesektor jedoch für den Kanton Jura mit einem Anteil von 37% der Beschäftigten (verglichen mit 26% in BL bzw. 17% in BS). Dabei ist insbesondere die Investitionsgüterindustrie zentral. Auch der Landwirtschaftssektor hat im Jura mit 7% einen höheren Beschäftigtenanteil als in den beiden Basel.",
		"erlaeuterungen": "Gezählt werden alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken) und ihre Tätigkeit in einer Arbeitsstätte mit Standort in BS/BL/JU verrichten (unabhängig vom Hauptsitz des Gesamtunternehmens).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Beschäftigte nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08498",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.4",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-20T08:53:53",
		"id": 8498
	},
	{
		"template": "template001_print",
		"data-id": 8499,
		"chart-id": 8499,
		"filter": "",
		"parentId": "8439",
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "2021",
		"lesehilfe": "Im Kanton Basel-Stadt gab es im Jahr 2021 17 502 Arbeitsstätten. Davon waren 1 816 Arbeitsstätten bzw. 10,4% in der Branche «Handel und Reparatur» angesiedelt. Im Baselbiet und im Jura liegt dieser Anteil etwas höher bei 13,2% bzw. 12,5%. In allen drei Kantonen weisen vor allem der Handel, das Gesundheitswesen sowie die freiberuflichen, wissenschaftlichen und technischen Dienstleistungen grössere Anteile auf. Während in Basel-Stadt die Landwirtschaft nur wenig Bedeutung hat, finden sich im Jura ähnlich viele Arbeitsstätten in der Landwirtschaft wie in der Industrie.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08499",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.3",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-20T08:53:53",
		"id": 8499
	},
	{
		"template": "template001_print",
		"data-id": 8500,
		"chart-id": 8500,
		"filter": "",
		"parentId": "8440",
		"children": [],
		"title": "Durchschnittliche Zahl der Beschäftigten pro Arbeitsstätte",
		"subtitle": "2021",
		"lesehilfe": "In einer Baselbieter Arbeitsstätte sind im Durchschnitt rund 8 Personen beschäftigt. Dieser Wert liegt nahe am gesamtschweizerischen Durchschnitt. Im Jura liegt der Wert etwas tiefer bei rund 7 Beschäftigten, da dort u. a. die Landwirtschaft mit typischerweise kleineren Arbeitsstätten eine höhere Bedeutung hat. In Basel-Stadt hingegen fällt die durchschnittliche Arbeitsstättengrösse mit rund 11 Beschäftigten deutlich höher aus, was mit den grösseren Arbeitsstätten in der Industrie und im Speziellen in der Chemie-/Pharmabranche erklärt werden kann.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Durchschnittliche Zahl der Beschäftigten pro Arbeitsstätte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08500",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.5",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-20T08:53:53",
		"id": 8500
	},
	{
		"template": "template001_print",
		"data-id": 8501,
		"chart-id": 8501,
		"filter": "",
		"parentId": "8441",
		"children": [],
		"title": "Veränderung der Beschäftigtenzahl",
		"subtitle": "2021 gegenüber 2014",
		"lesehilfe": "Zwischen 2014 und 2021 ist die Zahl der Beschäftigten in der Region BS/BL/JU insgesamt um 3,3% gewachsen und damit weniger stark als in der Gesamtschweiz (+7,3%). Das Beschäftigungswachstum liegt in Basel-Landschaft (+5,1%) und in Basel-Stadt (1,0%) unter dem Schweizer Wert, im Kanton Jura (+7,7%) darüber.",
		"erlaeuterungen": "Gezählt werden alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken) und ihre Tätigkeit in einer Arbeitsstätte mit Standort in BS/BL/JU verrichten (unabhängig vom Hauptsitz des Gesamtunternehmens).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Veränderung der Beschäftigtenzahl",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08501",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.7",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-01-02T08:14:06",
		"id": 8501
	},
	{
		"template": "line001_print",
		"data-id": 8502,
		"chart-id": 8502,
		"filter": "",
		"parentId": "8442",
		"children": [],
		"title": "Entwicklung monatliche Arbeitslosenquoten",
		"subtitle": "",
		"lesehilfe": "Die Arbeitslosenquoten in den Kantonen BS, BL und JU haben sich in den letzten Jahren sehr ähnlich entwickelt: Nach einem markanten Anstieg aufgrund der COVID-19-Pandemie im Jahr 2020 ist die Arbeitslosigkeit 2021 und 2022 tendentiell stark rückläufig. Das Niveau fällt jedoch unterschiedlich aus. Während sich die Arbeitslosenquote im Kanton Basel-Landschaft unter dem Schweizer Durchschnitt bewegt, fällt die Arbeitslosigkeit in Basel-Stadt und im Jura höher aus. Im Dezember 2022 lagen die Arbeitslosenquoten bei 1,8% (BL), 2,9% (BS) und 3,7% (JU). <br>Die höhere Quote des Kantons Jura hat unter anderem mit der unterschiedlichen Berechnungsmethode zu tun (siehe Erläuterungen und methodischen Hinweise).",
		"erlaeuterungen": "Arbeitslosenquote gemäss SECO, welche nur die Anzahl der Arbeitslosen berücksichtigt, die in den regionalen Arbeitsvermittlungszentren angemeldet sind. Im Kanton Jura werden dadurch auch die Arbeitslosen gezählt, welche Sozialhilfe beziehen. In BS und BL werden diese von anderen Organisationen betreut und werden daher nicht in der Berechnung miteinbezogen. Dieser organisatorische Unterschied führt zu einem verzerrten Vergleich.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung monatliche Arbeitslosenquoten",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08502",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.4",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-26T08:26:30",
		"id": 8502
	},
	{
		"template": "template001_print",
		"data-id": 8503,
		"chart-id": 8503,
		"filter": "",
		"parentId": "8443",
		"children": [],
		"title": "Entwicklung Steuerertrag pro Kopf der Wohnbevölkerung",
		"subtitle": "in Franken",
		"lesehilfe": "Der Steuerertrag pro Kopf liegt im Baselbiet 2017 mit etwas über 8 000 Franken im gesamtschweizerischen Durchschnitt. Im Jura beträgt der Wert etwas mehr als 6 000 Franken. Den höchsten Steuerertrag pro Person erzielt Basel-Stadt mit rund 14 000 Franken. Verglichen mit 2014 hat sich der Steuerertrag pro Kopf in den beiden Basel erhöht und im Jura leicht reduziert.",
		"erlaeuterungen": "Steuerertrag der Kantone und ihrer Gemeinden nach national vergleichbaren Kriterien (FS-Modell). Im Steuerertrag enthalten sind die direkten Steuern der natürlichen Personen (Einkommens-, Vermögens- und Quellensteuer) und der juristischen Personen (Gewinn- und Kapitalsteuer).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)",
			"Eidgenössische Finanzverwaltung, Finanzstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Steuerertrag pro Kopf der Wohnbevölkerung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:36",
		"id": 8503
	},
	{
		"template": "template001_print",
		"data-id": 8504,
		"chart-id": 8504,
		"filter": "",
		"parentId": "8444",
		"children": [],
		"title": "Anteil Steuerertrag nach natürlichen und juristischen Personen",
		"subtitle": "2017",
		"lesehilfe": "Im schweizerischen Vergleich haben die Steuererträge der juristischen Personen im Kanton Basel-Stadt eine überdurchschnittliche Bedeutung. Deren Anteil liegt bei 30%, verglichen mit 18% in der Gesamtschweiz. Im Baselbiet tragen umgekehrt die natürlichen Personen einen überdurchschnittlichen Anteil an den Steuererträgen von 88% (Schweiz: 82%). Im Jura entsprechen die Anteile in etwa dem Schweizer Durchschnitt.",
		"erlaeuterungen": "Steuerertrag der Kantone und ihrer Gemeinden nach national vergleichbaren Kriterien (FS-Modell). Im Steuerertrag enthalten sind die direkten Steuern der natürlichen Personen (Einkommens-, Vermögens- und Quellensteuer) und der juristischen Personen (Gewinn- und Kapitalsteuer).",
		"quellenangabe": [
			"Eidgenössische Finanzverwaltung, Finanzstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Anteil Steuerertrag nach natürlichen und juristischen Personen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:36",
		"id": 8504
	},
	{
		"template": "template001_print",
		"data-id": 8505,
		"chart-id": 8505,
		"filter": "",
		"parentId": "8445",
		"children": [],
		"title": "Entwicklung Abschlussquote auf Sekundarstufe II",
		"subtitle": "",
		"lesehilfe": "Der Anteil der Jugendlichen, die bis zum 25. Altersjahr einen Erstabschluss der Sekundarstufe II erworben haben, war 2020 im Kanton Basel-Landschaft mit 89,0% am höchsten. Er lag damit unter dem Schweizer Schnitt von 90,2%. Den tiefsten Wert aller Kantone wies mit 84,0% der Kanton Basel-Stadt auf.",
		"erlaeuterungen": "Bei der Berechnung werden die folgenden Abschlüsse berücksichtigt: - Berufliche Grundbildung: eidgenössische Fähigkeitszeugnisse und Berufsatteste gemäss der Statistik der beruflichen Grundbildung (SBG); - Allgemeinbildung: gymnasiale Maturitätszeugnisse, Fachmittelschulausweise und Abschlüsse der internationalen Schulen in der Schweiz gemäss der Statistik der Bildungsabschlüsse (SBA). Die Referenzbevölkerung besteht aus allen Personen, die im Alter des Beendens der obligatorischen Schule in der Schweiz wohnten. Ausgenommen sind Grenzgängerinnen und Grenzgänger sowie Personen, die im Zuge der jüngsten Zuwanderung nach beendeter obligatorischer Schulzeit in die Schweiz gekommen sind. Jugendliche, die das Land vor dem Erwerb eines Abschlusses auf der Sekundarstufe II verlassen haben, werden ebenfalls nicht berücksichtigt. Ausserdem werden bei der Abschlussquote nur Personen bis zu einem Alter von 25 Jahren betrachtet. Für eine bessere Stabilität der Ergebnisse wird ein Dreijahresdurchschnitt berechnet. Die Quote für das Jahr t entspricht folglich dem Durchschnitt der für die Jahre t-1, t und t+1 erhaltenen Werte.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Längsschnittanalysen im Bildungsbereich (LABB)"
		],
		"externalLinks": [
			"Weiterführende Informationen zum Thema finden Sie auf der <a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/bildungsindikatoren/themen/bildungserfolg/abschlussquote-sekii.html' target = '_blank'>Homepage des Bundesamtes für Statistik</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Abschlussquote auf Sekundarstufe II",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.08505",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2.3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-01T09:02:26",
		"id": 8505
	},
	{
		"template": "template001_print",
		"data-id": 8506,
		"chart-id": 8506,
		"filter": "",
		"parentId": "8446",
		"children": [],
		"title": "Entwicklung Nettoerwerbstätigenquote der 50- bis 64-Jährigen",
		"subtitle": "",
		"lesehilfe": "Die Nettoerwerbstätigenquote der im Kanton Basel-Stadt wohnhaften 50- bis 64-Jährigen liegt im Jahr 2021 bei 69,9%. Das 95%-Vertrauensintervall für diese Quote liegt zwischen 67,1% und 72,7%. Im Kanton Basel-Landschaft liegt die Quote bei 76,4% und im Kanton Jura bei 71,7%. Der Wert für die Schweiz beträgt 75,8%.",
		"erlaeuterungen": "Anteil der erwerbstätigen Wohnbevölkerung an der erwerbsfähigen Wohnbevölkerung (50 bis 64 Jahre; Nettoerwerbstätigenquote) in Prozent. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe (in Basel-Stadt zum Beispiel jährlich rund 5 000 dort wohnhafte Personen, für die Schweiz rund 270 000 Personen, jeweils ab 15 Jahren) und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Nettoerwerbstätigenquote der 50- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08506",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-09-15T09:04:40",
		"id": 8506
	},
	{
		"template": "template001_print",
		"data-id": 8507,
		"chart-id": 8507,
		"filter": "",
		"parentId": "8447",
		"children": [],
		"title": "Entwicklung Nettoerwerbstätigenquote der Frauen",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2021 beträgt die Nettoerwerbstätigenquote der im Kanton Basel-Stadt wohnhaften Frauen 69,5%. Das 95%-Vertrauensintervall für diese Quote liegt zwischen 67,3% und 71,7%. Im Kanton Basel-Landschaft liegt die Quote bei 71,2% und im Kanton Jura bei 67,2%. Der Wert für die Schweiz beträgt 71,8%.",
		"erlaeuterungen": "Anteil der erwerbstätigen Frauen an den erwerbsfähigen Frauen in der Wohnbevölkerung (15 bis 64 Jahre; Nettoerwerbstätigenquote) in Prozent. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe (in Basel-Stadt zum Beispiel jährlich rund 5 000 dort wohnhafte Personen, für die Schweiz rund 270 000 Personen, jeweils ab 15 Jahren) und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Nettoerwerbstätigenquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08507",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-09-15T09:04:42",
		"id": 8507
	},
	{
		"template": "line001_print",
		"data-id": 8508,
		"chart-id": 8508,
		"filter": "",
		"parentId": "8462",
		"children": [],
		"title": "Entwicklung Importe",
		"subtitle": "indexiert (2016 = 100)",
		"lesehilfe": "Der Wert der Warenimporte aus dem Ausland ist in Basel-Stadt zwischen 2016 und 2021 um über 30% gestiegen. Im Kanton Basel-Landschaft liegt der Wert über 24% höher als 2016. Im Jura ist der Wert nach einem Rückgang 2020 wieder gestiegen. Für die gesamte Region BS/BL/JU ergibt sich eine Zunahme um rund 29% seit 2016, für die gesamte Schweiz von ca. 16%.",
		"erlaeuterungen": "Entwicklung des nominalen Werts der Warenimporte aus dem Ausland. Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten. Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Importe",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08508",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.3",
		"stufe1": "3. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:08",
		"id": 8508
	},
	{
		"template": "line001_print",
		"data-id": 8864,
		"chart-id": 8864,
		"filter": "",
		"parentId": "8863",
		"children": [],
		"title": "Anteil Grenzgänger an der Beschäftigung",
		"subtitle": "2023, 2. Quartal",
		"lesehilfe": "Im Kanton Jura kommen rund 25 Grenzgänger auf 100 Stellen (Beschäftigungsstand: 2021). Auch der Anteil in den Kantonen Basel-Stadt (18%) und Basel-Landschaft (16%) ist im Vergleich zur gesamten Schweiz (7%) deutlich höher.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Beschäftigte (besetzte Stellen): Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Grenzgänger an der Beschäftigung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Ausländische Erwerbstätige",
		"kuerzel": "I.03.5.08864",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1.6",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-01T09:02:24",
		"id": 8864
	},
	{
		"template": "line001_print",
		"data-id": 8874,
		"chart-id": 8874,
		"filter": "",
		"parentId": "8868",
		"children": [],
		"title": "Entwicklung Handelsbilanz",
		"subtitle": "in Mio. Franken",
		"lesehilfe": "Die Handelsbilanz im Kanton Basel-Stadt ist 2021 gegenüber dem Vorjahr um 7 Milliarden auf 42,1 Milliarden Franken gestiegen. In Basel-Landschaft beträgt sie 2021 minus 691 Millionen. Im Jura liegt sie bei knapp 1,4 Milliarden Franken. In der Schweiz ist die Handelsbilanz seit 2018 zum dritten mal in Folge gestiegen und liegt 2021 bei über 58 Milliarden Franken.",
		"erlaeuterungen": "Die Handelsbilanz entspricht der Differenz zwischen den nominalen Exporten und den nominalen Importen im Warenhandel. Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmers, welches die Waren aus- oder einführt, berücksichtig.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Handelsbilanz",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08874",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "3.4",
		"stufe1": "3. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-27T08:46:08",
		"id": 8874
	},
	{
		"template": "template001_print",
		"data-id": 8876,
		"chart-id": 8876,
		"filter": "",
		"parentId": "8873",
		"children": [],
		"title": "Entwicklung Bettenangebot",
		"subtitle": "",
		"lesehilfe": "In den drei Kantonen Basel-Stadt, Basel-Landschaft und Jura wurden im Jahr 2022 zusammen 13 000 Betten angeboten. Mit Abstand die meisten bot Basel-Stadt mit knapp 9 300 an. Das Bettenangebot nahm in Basel-Stadt im Vergleich zu 2021 um 9,5% zu. 2020 wurde im Vergleich zum Vorjahr ein pandemiebedingter Rückgang registriert.  In Basel-Landschaft wurde im Zeitraum von 2018 bis 2022 Rückgänge verzeichnet (-7,6% auf 2 130). Im Jura wurde 2022 im Vergleich zu 2018 eine Zunahme um 6,1% registiert.  <br>Zur Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten.",
		"erlaeuterungen": "Anzahl angebotene Betten der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen. <br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Bettenangebot",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.08876",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "5.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-03-10T01:29:33",
		"id": 8876
	},
	{
		"template": "line001_print",
		"data-id": 8972,
		"chart-id": 8972,
		"filter": "",
		"parentId": "8969",
		"children": [],
		"title": "Entwicklung Neugründungsrate",
		"subtitle": "Anteil am Unternehmensbestand",
		"lesehilfe": "Der Anteil der neugegründeten Unternehmen am Total der Unternehmen liegt in der Region BS/BL/JU im Jahr 2020 bei 6,6%, und damit auf einem ähnlichen Niveau wie in den Vorjahren (mit Ausnahme von 2014). Höher liegt die Neugründungsrate im Kanton Basel-Stadt (7,6%) und in der Gesamtschweiz (7,1%).",
		"erlaeuterungen": "Die Neugründungsrate misst den Anteil aller in einem Jahr neugegründeten Unternehmen am Total der im selben Jahr aktiven Unternehmen. Erfasst werden nur tatsächlich neuentstandene Unternehmen (d. h. keine Berücksichtigung von neuen Unternehmen aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen) mit marktwirtschaftlicher Tätigkeit (ohne Holdinggesellschaften) im Industrie- und Dienstleistungssektor.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Neugründungsrate",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Neugründungen",
		"kuerzel": "I.06.2.08972",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.2",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2020-07-07T09:09:40",
		"id": 8972
	},
	{
		"template": "line001_print",
		"data-id": 8973,
		"chart-id": 8973,
		"filter": "",
		"parentId": "8970",
		"children": [],
		"title": "Entwicklung Beschäftigung",
		"subtitle": "",
		"lesehilfe": "Basel-Stadt zählt rund 193 002 Beschäftigte und damit fast so viele wie die beiden Kantone Basel-Landschaft und Jura zusammen. Die Beschäftigung in der Region BS/BL/JU hat im Jahr 2021 gegenüber dem Vorjahr um 2,2% zugenommen.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Beschäftigung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08973",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3.6",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-20T08:53:54",
		"id": 8973
	}
];