var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 22288,
		"chart-id": 22288,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Schweizer Mietpreisindizes im Vergleich",
		"subtitle": "Basis Mai 2000 = 100",
		"lesehilfe": "Der Mietpreisindex von Basel-Stadt liegt bei 139 Punkten, die Nettomieten sind damit von Mai 2000 bis Mai 2025 um 39 Prozent gestiegen.",
		"erlaeuterungen": "Indexstand im Mai des jeweiligen Jahres, Referenzzeitpunkt ist Mai des Jahres 2000. Die Indizes unterscheiden sich methodisch, bezüglich Stichprobengrösse und Erhebungsvorgehen. Die unterschiedlichen zeitlichen Entwicklungen sind daher mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung",
			"Statistik Stadt Zürich, Mietpreisindex",
			"Bundesamt für Statistik (BFS), Mietpreisindex",
			"Office cantonal de la statistique Genève, Loyers"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schweizer Mietpreisindizes im Vergleich",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22288
	},
	{
		"template": "template001",
		"data-id": 22289,
		"chart-id": 22289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Quartil",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Kanton Basel-Stadt, 2015 - 2023",
		"lesehilfe": "Der Median der Preise von Mietwohnungen lag 2023 bei geschätzt 19,7 Franken pro m<sup>2</sup>. Das erste Quartil der Mieten lag bei 16,3 Franken pro m<sup>2</sup>, das bedeutet ein Viertel aller Mieten pro m<sup>2</sup> war günstiger als dieser Wert. Das dritte Quartil bei 23,4 Franken pro m<sup>2</sup>. Alle drei Quartilsmieten sind kontinuierlich gestiegen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Quartile sind die drei Werte einer Häufigkeitsverteilung (hier Nettomietpreise pro m<sup>2</sup>), die diese in vier gleich große Bereiche teilen: 25% aller Fälle liegen im Bereich bis zum 1. Quartil der Verteilung. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle, welche den wahren Wert mit einer Wahrscheinlichkeit von 95% umfassen. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit jenen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Quartil",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22289
	},
	{
		"template": "template001",
		"data-id": 22290,
		"chart-id": 22290,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Dauer des Mietverhältnisses",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Kanton Basel-Stadt, 2020 - 2023",
		"lesehilfe": "Einzugsmieten von Wohnungen im Kanton Basel-Stadt betrugen 2023 im Schnitt 21,4 Franken pro m<sup>2</sup> (95%-Konfidenzintervall: 20,9 - 21,9 Franken pro m<sup>2</sup>). Die Mieten von älteren Mietverhältnisse lagen durchschnittlich bei 18,5 Franken pro m<sup>2</sup>. Die Mieten von neueren Mietverhältnissen lagen somit 15,7% über denjenigen von älteren Mietverhältnissen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Als Einzugsmieten gelten die in den letzten zwei Jahren abgeschlossenen Mietverträge. Bestandesmieten gelten für Mietverhältnisse, die bereits länger als zwei Jahre dauern. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle, welche den wahren Wert mit einer Wahrscheinlichkeit von 95% umfassen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Dauer des Mietverhältnisses",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22290
	},
	{
		"template": "template001",
		"data-id": 22291,
		"chart-id": 22291,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerkündigungen",
		"subtitle": "Anzahl von Umbau oder Abbruch betroffener Wohnungen",
		"lesehilfe": "Die Anzahl leergekündigter Wohnungen aufgrund von Umbau lag in den Jahren 2022 (276 Wohnungen) und 2023 (103 Wohnungen) deutlich tiefer als in den Vorjahren.",
		"erlaeuterungen": "Gemäss Bautätigkeit des Gebäude- und Wohnungsregisters sowie Belegungsangaben aus dem Einwohnerregister. Ein Gebäude muss beim Umbau seit mindestens 15 Jahren bestehen, mindestens über vier Wohnungen verfügen zwei Jahre vor Baubeginn und 90% Neumieter aufweisen ein Jahr nach Bauvollendung des Umbaus, um als betroffen berücksichtigt zu werden. Ein Abbruch hat stets den Auszug der kompletten Mieterschaft zur Folge. Die hier verwendeten Registerangaben geben keinen Aufschluss darüber, welche Partei das Mietverhältnis beendet hat und aus welchem Grund. Auch wird nicht berücksichtig, ob das Mietverhältnis befristet oder unbefristet war.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Bevölkerungsdienste und Migration Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerkündigungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22291
	},
	{
		"template": "template001",
		"data-id": 22292,
		"chart-id": 22292,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"subtitle": "Anzahl Bauprojekte nach Baueingabe",
		"lesehilfe": "Im 2021 und im 1. Halbjahr 2022 (2022-H1)  ist ein deutlicher Anstieg unter den Projekten, die unter die Bedingungen der Wohnschutzgesetzgebung erfüllt hätten, sichtbar. Seit der zweiten Jahreshälfte 2022 ist ein Einbruch festzustellen. Dieser betrifft Umbauprojekte generell, wie auch die durch die geänderte Gesetzgebung betroffenen Umbauprojekte. Die Anzahl der nicht unter die Wohnschutzgesetzgebung fallenden Projekte war weniger stark rückläufig.",
		"erlaeuterungen": "Bewilligungspflichte Umbauprojekte (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe. \"Unter Gesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen können (oder hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22292
	},
	{
		"template": "template001",
		"data-id": 22293,
		"chart-id": 22293,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sanierungsvolumen in Mio. Franken",
		"subtitle": "Projektgesamtkosten nach Baueingabe",
		"lesehilfe": "Die gemäss eingereichtem Umbauprojekt angegebenen Projektgesamtkosten sind insbesondere ab 2021 deutlich angestiegen, ehe sie ab der zweiten Hälfte 2022 wieder deutlich zurückgingen. Die Projektgesamtkosten nicht von der geänderter Gesetzgebung betroffener Umbauprojekte blieben in diesem Zeitraum stabil.",
		"erlaeuterungen": "Bewilligungspflichte Umbauprojekte (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe, ohne Baunebenkosten. \"Unter Gesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen können (oder hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sanierungsvolumen in Mio. Franken",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22293
	},
	{
		"template": "template001",
		"data-id": 22294,
		"chart-id": 22294,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Umwandlungen in Stockwerkeigentum",
		"subtitle": "Anzahl Bewilligungen durch die Wohnschutzkommission",
		"lesehilfe": "Nach Inkraftreten der Wohnraumschutzverordnung (WRSchV) gab es 2023 insgesamt 3 Fälle und ein Jahr danach 4 Fälle, wo für die Begründung von Stockwerkeigentum eine Bewilligung der Wohnschutzkommission Voraussetzung war.",
		"erlaeuterungen": "Fälle, in denen eine Bewilligung der Wohnschutzkommission Voraussetzung ist für die Begründung von Stockwerkeigentum.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Umwandlungen in Stockwerkeigentum",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22294
	},
	{
		"template": "template001",
		"data-id": 22295,
		"chart-id": 22295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fördervolumen Gebäudeprogramm",
		"subtitle": "Auszahlungen pro Jahr für Wärmedämmung in CHF",
		"lesehilfe": "Die jährlich ausbezahlten Förderbeiträge für die Wärmedämmung von Bestandsgebäuden (Einfamilien- und Mehrfamilienhäuser) haben sich seit 2017 von gut CHF 0,9 Mio. auf knapp CHF 3,4 Mio. erhöht. Insbesondere bei Mehrfamilienhäuser ist ein starker Anstieg zu verzeichnen ist, während sich die Entwicklung bei den Einfamilienhäusern auf stabilem Niveau verhält.",
		"erlaeuterungen": "Gemäss Gebäudeprogramm ausbezahlte Förderbeiträge nach Kanton und Gebäudekategorie.",
		"quellenangabe": [
			"Gebäudeprogramm"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fördervolumen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22295
	},
	{
		"template": "template001",
		"data-id": 22296,
		"chart-id": 22296,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Abgebrochene Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In den letzten zwanzig Jahren wurden im Durchschnitt rund hundert Wohnungen abgebrochen. Im Jahr 2024 war die Anzahl abgebrochener Wohnungen mit 77 unterdurchschnittlich.",
		"erlaeuterungen": "Abgebrochene Wohnungen nach Jahr des Abbruches.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Abgebrochene Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22296
	},
	{
		"template": "template001",
		"data-id": 22297,
		"chart-id": 22297,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungsneubau",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der neugebauten Wohnungen lag 2024 bei 151 Einheiten und damit deutlich unter dem Wert der Vorjahre. Dies lag mitunter daran, dass sehr wenige neue Wohnungen aus Arealentwicklungen verzeichnet werden  konnten.",
		"erlaeuterungen": "Als Arealentwicklungen werden Areale bezeichnet, auf denen vorher keine oder nur eine sehr kleine Wohnutzung (bspw. vereinzelte Dienstwohnungen) bestand. Zu den grössten Arealentwicklungen der letzten Jahre gehören beispielsweise Projekte auf den Arealen Erlenmatt, Westfeld und Lysbüchel sowie das Meret Oppenheim Hochhaus.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungsneubau",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-6",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22297
	},
	{
		"template": "template001",
		"data-id": 22298,
		"chart-id": 22298,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Baubewilligte Wohnungen und Gebäude",
		"subtitle": "Anzahl bewilligte Gebäude und Wohnungen",
		"lesehilfe": "Von 2021 bis 2023 wurde eine geringe Anzahl Wohnungen bewilligt. 2024 nahm sie wieder zu und lässt ab 2026 eine höhere Wohnbauproduktion erwarten.",
		"erlaeuterungen": "Es werden bewilligte Wohnungen und bewohnbare Gebäude in Neubauprojekten gezählt. Umbauprojekte mit Wohnungszuwachs werden demzufolge nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Baubewilligte Wohnungen und Gebäude",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-7",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22298
	},
	{
		"template": "line001",
		"data-id": 22299,
		"chart-id": 7586,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"subtitle": "",
		"lesehilfe": "Mit dem vor gut zehn Jahren einsetzenden Anstieg der Wohnbevölkerung ging auch die Basler Leerwohnungsquote bis 2017 auf Werte im Bereich der anderen grösseren Schweizer Städte zurück. Seit 2019 hat die Stadt Basel die anderen Grossstädte bezüglich der Leerwohnungsziffer deutlich überholt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde",
			"Schweiz"
		],
		"description": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-8",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22299
	},
	{
		"template": "line001",
		"data-id": 22300,
		"chart-id": 12722,
		"filter": "",
		"parentId": "12722",
		"children": [],
		"title": "Bodenpreisindex",
		"subtitle": "Basel-Stadt, Basis 2014 = 100",
		"lesehilfe": "Der Index für Einfamilienhaus-Grundstücke erreichte im Jahr 2023 den Stand von 168 Punkten, was einem prozentualen Anstieg von 68% gegenüber dem Basisjahr 2014 entspricht. Bei den Mehrfamilienhaus-Grundstücken lag er bei 218 Punkten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bodenpreisindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-9",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22300
	},
	{
		"template": "template001",
		"data-id": 22301,
		"chart-id": 22301,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"subtitle": "Basel-Stadt, 2022 - 2024",
		"lesehilfe": "2024 gab es 124 Prüfungs- und Bewilligungsverfahren für Umbauten, Renovationen- und Sanierungen. 18 Gesuche wurden für die Begründung von Stockwerkeigentum eingereicht und 3 Gesuche für die Festlegung von maximalen Nettomietzinsen bei Abbruch und Ersatzneubau.",
		"erlaeuterungen": "Es werden die jährlich neu eintreffenden Gesuche ausgewiesen.",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22301
	},
	{
		"template": "template001",
		"data-id": 22302,
		"chart-id": 22302,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22302
	},
	{
		"template": "template001",
		"data-id": 22303,
		"chart-id": 22303,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22303
	}
];