var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 22288,
		"chart-id": 22288,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Schweizer Mietpreisindizes im Vergleich",
		"subtitle": "indexiert (Basis Mai 2000 = 100)",
		"lesehilfe": "Der Mietpreisindex von Basel-Stadt liegt bei 139 Punkten, die Nettomieten sind damit von Mai 2000 bis Mai 2025 um 39 Prozent gestiegen.",
		"erlaeuterungen": "Indexstand im Mai des jeweiligen Jahres, Referenzzeitpunkt ist Mai des Jahres 2000. Die Indizes unterscheiden sich methodisch, bezüglich Stichprobengrösse und Erhebungsvorgehen. Die unterschiedlichen zeitlichen Entwicklungen sind daher mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung",
			"Statistik Stadt Zürich, Mietpreisindex",
			"Bundesamt für Statistik (BFS), Mietpreisindex",
			"Office cantonal de la statistique Genève, Loyers"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schweizer Mietpreisindizes im Vergleich",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22288
	},
	{
		"template": "template001",
		"data-id": 22289,
		"chart-id": 22289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Quartil",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Basel-Stadt, 2015 - 2023",
		"lesehilfe": "Der Median der Preise von Mietwohnungen lag im Jahr 2023 bei geschätzt 19,7 Franken pro m<sup>2</sup>. Das erste Quartil lag bei 16,3 Franken pro m<sup>2</sup>; das bedeutet, dass ein Viertel aller Mieten pro m<sup>2</sup> unter und drei Viertel über diesem Preis lagen. Das dritte Quartil stand bei bei 23,4 Franken pro m<sup>2</sup>. Alle drei Quartilsmieten sind kontinuierlich gestiegen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Quartile sind die drei Werte einer Häufigkeitsverteilung (hier Nettomietpreise pro m<sup>2</sup>), die diese in vier gleich große Bereiche teilen: 25% aller Fälle liegen im Bereich bis zum 1. Quartil der Verteilung. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung können die Ergebnisse nur bedingt mit jenen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Quartil",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22289
	},
	{
		"template": "template001",
		"data-id": 22290,
		"chart-id": 22290,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Dauer des Mietverhältnisses",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Basel-Stadt, 2020 - 2023",
		"lesehilfe": "Einzugsmieten von Wohnungen im Kanton Basel-Stadt betrugen im Jahr 2023 im Schnitt 21,4 Franken pro m<sup>2</sup> (95%-Konfidenzintervall: 20,9 - 21,9 Franken pro m<sup>2</sup>). Die Mieten von älteren Mietverhältnissen lagen durchschnittlich bei 18,5 Franken pro m<sup>2</sup>. Die Mieten von neueren Mietverhältnissen lagen somit 15,7% über denjenigen von älteren Mietverhältnissen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Als Einzugsmieten gelten die in den letzten zwei Jahren abgeschlossenen Mietverträge. Bestandesmieten gelten für Mietverhältnisse, die bereits länger als zwei Jahre dauern. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle, welche den wahren Wert mit einer Wahrscheinlichkeit von 95% umfassen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Dauer des Mietverhältnisses",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22290
	},
	{
		"template": "template001",
		"data-id": 22291,
		"chart-id": 22291,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerkündigungen",
		"subtitle": "Anzahl betroffene Wohnungen, Basel-Stadt",
		"lesehilfe": "Im Jahr 2019 wurden für 480 Wohnungen Leerkündigungen aufgrund eines Umbaus registriert – die Zahl ist gegen Ende des Beobachtungszeitraums deutlich rückläufig. Für 219 weitere erfolgte eine Leerkündigung aufgrund eines Abbruchs. Auch hier ist seit 2019 ein deutlicher Rückgang sichtbar.",
		"erlaeuterungen": "Die Auswertung erfolgt anhand der im Gebäude- und Wohnungsregister (GWR) hinterlegten Bautätigkeit sowie Belegungsangaben aus dem Einwohnerregister. Um für die Auswertung berücksichtigt werden zu können, muss ein Gebäude beim <i>Umbau</i> seit mindestens 15 Jahren bestehen und zwei Jahre vor Baubeginn über mindestens vier Wohnungen verfügen. Damit die Wohnungen als von Leerkündigungen betroffen gezählt werden, müssen 90% der Mieterschaft (relativ zu den Bewohnenden zwei Jahre vor Baubeginn) ein Jahr nach Bauvollendung  weniger als 2 Jahre in der Liegenschaft angemeldet sein. Ein <i>Abbruch</i> hat stets den Auszug der kompletten Mieterschaft zur Folge, wobei hier der Wohnungsbestand drei Jahre vor Baubeginn als Grundlage dient. Die verwendeten Registerangaben geben keinen Aufschluss darüber, welche Partei das Mietverhältnis beendet hat und aus welchem Grund. Auch wird nicht berücksichtigt, ob das Mietverhältnis befristet oder unbefristet war. Das Jahr bezeichnet das Jahr des Baubeginns.<br><br>Datenstand ist Mitte Juni 2025. Aufgrund der Zählweise, die sich auf ein Jahr nach Bauvollendung bezieht, werden nur Werte bis 2023 publiziert. Bei überdurchschnittlich langen Bauprojekten können sich die Werte der letzten Jahre (insbesondere die Leerkündigungen nach Umbau 2023) bei einer Aktualisierung erhöhen, da diese Projekte allenfalls hinzukommen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Bevölkerungsdienste und Migration Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerkündigungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-23T07:42:50",
		"id": 22291
	},
	{
		"template": "template001",
		"data-id": 22292,
		"chart-id": 22292,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"subtitle": "Anzahl Bauprojekte von Wohngebäuden nach Baueingabe, Basel-Stadt",
		"lesehilfe": "Seit der zweiten Jahreshälfte 2022 ist ein Einbruch bei Baugesuchen für Sanierung, Umbau oder Renovation festzustellen. Die Anzahl der nicht unter die Wohnschutzgesetzgebung fallenden Projekte war weniger stark rückläufig. Kurz davor im Jahr 2021 und im 1. Halbjahr 2022 ist ein deutlicher Anstieg von Bauge-suchen sichtbar, welche unter die Wohnschutzgesetzgebung gefallen wäre.",
		"erlaeuterungen": "Berücksichtigt sind nur Projekte mit einer Baueingabe. Umbau-, Sanierungs- und Renovationspro-jekte ohne Baubewilligungspflicht fallen nicht unter die Auswertung. Ausgewertet sind. Baueingaben (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe. \"Unter Gesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen können (oder hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude und mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22292
	},
	{
		"template": "template001",
		"data-id": 22293,
		"chart-id": 22293,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sanierungsvolumen in Franken",
		"subtitle": "Projektgesamtkosten nach Baueingabe, Basel-Stadt",
		"lesehilfe": "Die in Baugesuchen für Sanierungen, Umbauten und Re-novationen angegebenen Projektgesamtkosten sind insbesondere im Jahr 2021 deutlich gestiegen, ehe sie ab der zweiten Hälfte 2022 wieder deutlich zurückgingen. In Bezug auf Projekte, die nicht von der geänderten Gesetzgebung betroffenen ist der Effekt weniger deutlich.",
		"erlaeuterungen": "Bewilligungspflichte Umbauprojekte (Baubegehren sowie vereinfachte und technische Baubegehren) mit Berücksichtigt sind nur Projekte mit einer Baueingabe. Umbau-, Sanierungs- und Renovationsprojekte ohne Baubewilligungspflicht fallen nicht unter die Auswertung. Ausgewertet sind Baueingaben (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe, ohne Baunebenkosten. \"Unter Gesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen können (oder hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude und mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sanierungsvolumen in Franken",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22293
	},
	{
		"template": "template001",
		"data-id": 22294,
		"chart-id": 22294,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Umwandlungen in Stockwerkeigentum",
		"subtitle": "Anzahl Bewilligungen durch die Wohnschutzkommission, Basel-Stadt",
		"lesehilfe": "Die Anzahl betroffener Stammparzellen verhält sich auf tiefen Nivau, steigt in der zweiten Jahreshälfte 2021 jedoch deutlich an auf 25 und dann in der ersten Jahreshälfte 2022 äusserst stark auf 207, bevor sie danach wieder auf das vorangegangene Nivau sinkt. Entsprechend verhält sich die auf diesen Parzellen ermittelte Anzahl Wohnungen, welche insbesondere in der ersten Jahreshälfte 2022 mit 1'800 ihren absoluten Höchstwert erreicht.",
		"erlaeuterungen": "Anzahl Stammparzellen gemäss Grundbuch, auf denen Stockwerkeigentum begründet wurde und auf denen Wohngebäude mit Wohnungen gemäss Gebäude- und Wohnunngsregister existieren. Unberücksichtig sind Mansarden bzw. bewohnbare Einzelzimmer, Alters- und Genossenschaftswohnungen sowie Büros, Garagen, Lager, Ateliers und andere nicht zum Wohnen genutzte Einheiten. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Umwandlungen in Stockwerkeigentum",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22294
	},
	{
		"template": "template001",
		"data-id": 22295,
		"chart-id": 22295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fördervolumen Gebäudeprogramm",
		"subtitle": "Auszahlungen pro Jahr für Wärmedämmung in Franken, Basel-Stadt",
		"lesehilfe": "Die jährlich im Rahmen des Gebäudeprogramms von Kanton und Bund ausbezahlten Förderbeiträge für die Wärmedämmung von Bestandsgebäuden (Einfamilien- und Mehrfamilienhäuser) haben sich im Kanton Basel-Stadt seit 2017 von gut 1,8 Mio . Franken auf knapp 3,4 Mio. Franken erhöht. Insbesondere bei Mehrfamilienhäusern ist ein starker Anstieg zu verzeichnen, während sich die Entwicklung bei Einfamilienhäusern auf stabilem Niveau bewegt.",
		"erlaeuterungen": "Gemäss Gebäudeprogramm von Kanton und Bund ausbezahlte Förderbeiträge nach Gebäudekategorie. Die Auszahlung der Fördergelder erfolgt nach Abschluss der Sanierung, zwischen Förderzusage und Auszahlung können mehrere Jahre vergehen. Weitere Informationen zum Gebäudeprogramm finden sich hier: <a href='https://www.dasgebaeudeprogramm.ch/de' target='_blank'>Gebäudeprogramm</a>",
		"quellenangabe": [
			"Gebäudeprogramm"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fördervolumen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22295
	},
	{
		"template": "template001",
		"data-id": 22296,
		"chart-id": 22296,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Abgebrochene Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In den letzten 20 Jahren wurden im Durchschnitt jährlich rund hundert Wohnungen abgebrochen. Im Jahr 2024 war die Anzahl abgebrochener Wohnungen mit 77 unterdurchschnittlich.",
		"erlaeuterungen": "Abgebrochene Wohnungen nach Jahr des Abbruchs.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Abgebrochene Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22296
	},
	{
		"template": "template001",
		"data-id": 22297,
		"chart-id": 22297,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungsneubau",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der neugebauten Wohnungen lag 2024 bei 151 Einheiten und damit deutlich unter dem Wert der Vorjahre. Insbesondere resultierten aus Arealentwicklungen nur sehr wenige neue Wohnungen.",
		"erlaeuterungen": "Als Arealentwicklungen werden Areale bezeichnet, auf denen vorher keine oder kaum Wohnnutzung bestand. Zu den grössten Arealentwicklungen der letzten Jahre gehören beispielsweise Projekte auf den Arealen Erlenmatt, Westfeld und Lysbüchel sowie das Meret Oppenheim Hochhaus.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungsneubau",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-6",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22297
	},
	{
		"template": "template001",
		"data-id": 22298,
		"chart-id": 22298,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Baubewilligte Wohnungen und Gebäude",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von 2021 bis 2023 wurde eine geringe Anzahl Wohnungen bewilligt. 2024 nahmen die Bewilligungen wieder zu. Dies lässt ab 2026 eine höhere Wohnbauproduktion erwarten.",
		"erlaeuterungen": "Gezählt werden bewilligte Wohnungen und bewohnbare Gebäude in Neubauprojekten nach Jahr der Baubewilligung. Umbauprojekte mit Wohnungszuwachs werden demzufolge nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Baubewilligte Wohnungen und Gebäude",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-7",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22298
	},
	{
		"template": "line001",
		"data-id": 22299,
		"chart-id": 22299,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"subtitle": "",
		"lesehilfe": "Mit dem vor gut zehn Jahren einsetzenden Anstieg der Wohnbevölkerung ging auch die Basler Leerwohnungsquote bis 2017 auf Werte im Bereich der anderen grösseren Schweizer Städte zurück. Seit 2019 hat die Stadt Basel die anderen Grossstädte bezüglich der Leerwohnungsziffer deutlich überholt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde",
			"Schweiz"
		],
		"description": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-8",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22299
	},
	{
		"template": "line001",
		"data-id": 22300,
		"chart-id": 12722,
		"filter": "",
		"parentId": "12722",
		"children": [],
		"title": "Bodenpreisindex",
		"subtitle": "indexiert (Basis 2014 = 100), Basel-Stadt",
		"lesehilfe": "Der Index für Einfamilienhaus-Grundstücke erreichte im Jahr 2023 den Stand von 168 Punkten, was einem prozentualen Anstieg von 68% gegenüber dem Basisjahr 2014 entspricht. Bei den Mehrfamilienhaus-Grundstücken lag er bei 218 Punkten.",
		"erlaeuterungen": "Das methodische Vorgehen ist im <a href='https://statistik.bs.ch/files/berichte-analysen/Methodenbericht-Bodenpreisindex.pdf' target='_blank'>Methodenbericht</a> beschrieben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bodenpreisindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-9",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22300
	},
	{
		"template": "template001",
		"data-id": 22301,
		"chart-id": 22301,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2024 gab es 124 Prüfungs- und Bewilligungsverfahren für Umbauten, Renovationen und Sanierungen. 18 Gesuche wurden für die Begründung von Stockwerkeigentum eingereicht und 3 Gesuche für die Festlegung von maximalen Nettomietzinsen bei Abbruch und Ersatzneubau.",
		"erlaeuterungen": "Ausgewiesen werden die jährlich neu eintreffenden Gesuche.",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22301
	},
	{
		"template": "template001",
		"data-id": 22302,
		"chart-id": 22302,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22302
	},
	{
		"template": "template001",
		"data-id": 22303,
		"chart-id": 22303,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22303
	},
	{
		"template": "template001",
		"data-id": 22326,
		"chart-id": 22326,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Förderzusagen Gebäudeprogramm",
		"subtitle": "Verpflichtungen pro Jahr für Wärmedämmung indexiert (Basis 2017 = 100), Basel-Stadt",
		"lesehilfe": "Zwischen 2017 und 2023 haben die zugesagten Förderbeiträge für Wärmedämmungen schweizweit umd 13% zugenommen. Im Kanton Basel-Stadt haben sich diese Beiträge bis 2021 fast verzweieinhalbfacht, während sie 2022 dann stark zurückgingen und ab 2023 dann wieder deutlich zunahmen.",
		"erlaeuterungen": "Gemäss Gebäudeprogramm indexierte zugesagte Förderbeiträge. Weitere Informationen zum Gebäudeprogramm finden sich hier: <a href='https://www.dasgebaeudeprogramm.ch/de' target='_blank'>Gebäudeprogramm</a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Förderzusagen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-16T09:09:32",
		"id": 22326
	}
];