var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 22288,
		"chart-id": 22288,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreisindex",
		"subtitle": "Vergleich von Basel-Stadt mit anderen Schweizer Städten",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22288
	},
	{
		"template": "template001",
		"data-id": 22289,
		"chart-id": 22289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Quartil",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Quartil",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22289
	},
	{
		"template": "template001",
		"data-id": 22290,
		"chart-id": 22290,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bestandes- und Einzugsmieten",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bestandes- und Einzugsmieten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22290
	},
	{
		"template": "template001",
		"data-id": 22291,
		"chart-id": 22291,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerkündigungen",
		"subtitle": "Anzahl von Umbau oder Abbruch betroffener Wohnungen",
		"lesehilfe": "Die Anzahl von Umbau und nicht von Leerkündigung betroffener Wohnungen ist seit 2016 rückläufig und betrug 2023 noch gut 500 Einheiten. Die Anzahl von Umbau und Leerkündigung betroffener Wohnungen verhält sich über den Beobachtungszeitraum konstant auf tiefem Niveau und erreichte 2021 einen Höchstwert von über 100 Einheiten.",
		"erlaeuterungen": "Gemäss Bautätigkeit des Gebäude- und Wohnungsregisters sowie Belegungsangaben aus dem Einwohnerregister. Ein Gebäude muss beim Umbau seit mindestens 15 Jahren bestehen, mindestens über vier Wohnungen verfügen zwei Jahre vor Baubeginn und 90% Neumieter aufweisen ein Jahr nach Bauvollendung des Umbaus, um als betroffen berücksichtigt zu werden. Ein Abbruch hat stets den Auszug der kompletten Mieterschaft zur Folge. Die hier verwendeten Registerangaben geben keinen Aufschluss darüber, welche Partei das Mietverhältnis beendet hat und aus welchem Grund!",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Bevölkerungsdienste und Migration Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerkündigungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22291
	},
	{
		"template": "template001",
		"data-id": 22292,
		"chart-id": 22292,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl baubewilligungspflichtige Sanierungen",
		"subtitle": "Anzahl Bauprojekte nach Baueingabe",
		"lesehilfe": "Hat die Anzahl Projekte seit der ersten Jahreshälfte 2018 insbesondere seit 2021 deutlich zugenommen, ist seit der zweiten Jahreshälfte 2022 ein Eindbruch frestzustellen, und zwar sowohl generell bei Umbauprojekten wie auch bei den durch die geänderte Gesetzgebung betroffenen Umbauprojekte. Die Anzahl nicht betroffener Projekte ging gleichzeitig nur leicht zurück.",
		"erlaeuterungen": "Bewilligungspflichte Umbauprojekte (Baubegehren sowie vereinfachte und technische Baubegehren) in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl baubewilligungspflichtige Sanierungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22292
	},
	{
		"template": "template001",
		"data-id": 22293,
		"chart-id": 22293,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sanierungsvolumen in Mio. Franken",
		"subtitle": "Projektgesamtkosten nach Baueingabe",
		"lesehilfe": "Die gemäss eingereichtem Umbauprojekt angegebenen Projektgesamtkosten sind insbesondere ab 2021 deutlich angestiegen, ehe sie ab der zweiten Hälfte 2022 wieder deutlich zurückgingen. Die Projektgesamtkosten nicht von der geänderter Gesetzgebung betroffener Umbauprojekte blieben in diesem Zeitraum stabil.",
		"erlaeuterungen": "Bewilligungspflichte Umbauprojekte (Baubegehren sowie vereinfachte und technische Baubegehren) in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe, ohne Baunebenkosten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sanierungsvolumen in Mio. Franken",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22293
	},
	{
		"template": "template001",
		"data-id": 22294,
		"chart-id": 22294,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Umwandlungen in Stockwerkeigentum",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Umwandlungen in Stockwerkeigentum",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22294
	},
	{
		"template": "line001",
		"data-id": 22295,
		"chart-id": 22295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fördervolumen Gebäudeprogramm",
		"subtitle": "Auszahlungen pro Jahr für Wärmedämmung in Mio. CHF",
		"lesehilfe": "Die jährlich ausbezahlten Förderbeiträge für die Wärmedämmung von Bestandsgebäuden haben sich seit 2017 von gut CHF 2 Mio. auf über CHF 4 Mio. verdoppelt, wobei insbesondere bei Mehrfamilienhäuser ein starker Anstieg zu verzeichnen ist, während sich die Entwicklung bei den Einfamilienhäusern auf stabilem Niveau verhält.",
		"erlaeuterungen": "Gemäss Gebäudeprogramm ausbezahlte Förderbeiträge nach Kanton und Gebäudekategorie.",
		"quellenangabe": [
			"Gebäudeprogramm"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fördervolumen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22295
	},
	{
		"template": "template001",
		"data-id": 22296,
		"chart-id": 22296,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Abbruch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In den letzten zwanzig Jahren wurden im Durchschnitt rund hundert Wohnungen abgebrochen. Im Jahr 2024 war die Anzahl abgebrochener Wohnungen mit 77 unterdurchschnittlich.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Abbruch",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22296
	},
	{
		"template": "template001",
		"data-id": 22297,
		"chart-id": 22297,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2024 bei 511 Einheiten und damit deutlich unter dem Wert der Vorjahre. Dies lag daran, dass sehr wenige neue Wohnungen aus Arealentwicklungen verzeichnet werden  konnten.",
		"erlaeuterungen": "Als Arealentwicklungen werden Areale bezeichnet, auf denen vorher keine oder nur eine sehr kleine Wohnutzung (bspw. Vereinzelte Dienstwohnungen) bestand.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-6",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22297
	},
	{
		"template": "template001",
		"data-id": 22298,
		"chart-id": 22298,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bewilligte Wohnungen und Gebäude",
		"subtitle": "Anzahl bewilligte Gebäude und Wohnungen",
		"lesehilfe": "Von 2021 bis 2023 wurde eine geringe Anzahl Wohnungen bewilligt. 2024 nahm sie wieder zu und lässt ab 2026 eine höhere Wohnbauproduktion erwarten.",
		"erlaeuterungen": "Es werden bewilligte Wohnungen und bewohnbare Gebäude in Neubauprojekten gezählt. Umbauprojekte mit Wohnungszuwachs werden denzufolge nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bewilligte Wohnungen und Gebäude",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-7",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22298
	},
	{
		"template": "template001",
		"data-id": 22299,
		"chart-id": 22299,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerstand",
		"subtitle": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"lesehilfe": "Mit dem vor gut zehn Jahren einsetzenden Anstieg der Wohnbevölkerung ging auch die Basler Leerwohnungsquote bis 2017 auf Werte im Bereich der anderen grösseren Schweizer Städte zurück. Seit 2019 hat die Stadt Basel die anderen Grossstädte bezüglich der Leerwohnungsziffer deutlich überholt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerstand",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-8",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22299
	},
	{
		"template": "line001",
		"data-id": 22300,
		"chart-id": 22300,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bodenpreisindex",
		"subtitle": "Basel-Stadt, Basis 2014 = 100",
		"lesehilfe": "Der Index für Einfamilienhaus-Grundstücke erreichte im Jahr 2023 den Stand von 168 Punkten, was einem prozentualen Anstieg von 68% gegenüber dem Basisjahr 2014 entspricht. Bei den Mehrfamilienhaus-Grundstücken lag er bei 218 Punkten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bodenpreisindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-9",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22300
	},
	{
		"template": "template001",
		"data-id": 22301,
		"chart-id": 22301,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Gesuche WSK",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Gesuche WSK",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22301
	},
	{
		"template": "template001",
		"data-id": 22302,
		"chart-id": 22302,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Verfügungen inkl. Anzahl betroffener Wohnverhältnisse",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22302
	},
	{
		"template": "template001",
		"data-id": 22303,
		"chart-id": 22303,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"subtitle": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Höhe der bewilligten Mietzinsaufschläge/Mietzinsfestlegungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-10T12:50:45",
		"id": 22303
	}
];