var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 7599,
		"chart-id": 7599,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittlere Fläche der gebauten Wohnungen",
		"subtitle": "in Quadratmeter nach Zimmerzahl, Basel-Stadt",
		"lesehilfe": "Die durchschnittlichen Wohnungsflächen der Neubauwohnungen sind 2021 in allen Zimmerzahlkategorien ausser bei den Wohnungen mit 6 und mehr Zimmern grösser als die Werte im Gesamtbestand.",
		"erlaeuterungen": "Als Wohnungsfläche gelten sämtliche bewohnbaren Flächen einer Wohnung, also die Summe der Flächen sämtlicher Zimmer, Küchen, Kochnischen, Badezimmer, Toilettenräume, Abstellräume, Gänge, Veranden etc. einer Wohnung (ohne Terrassen oder offene Balkone).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Fläche der gebauten Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07599",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "05",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "",
		"id": 7599
	},
	{
		"template": "template001",
		"data-id": 7601,
		"chart-id": 7601,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zimmerzahl der gebauten Wohnungen",
		"subtitle": "in Prozent, Basel-Stadt",
		"lesehilfe": "In den letzten zehn Jahren waren Zwei- oder Dreizimmerwohnungen die häufigsten Kategorien der Neubauwohnungen. Durchschnittlich betrug ihr Anteil rund zwei Drittel aller neuerstellten Wohnungen.",
		"erlaeuterungen": "Es werden die neuerstellten Wohnungen in Neubauten gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zimmerzahl der gebauten Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07601",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "06",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "",
		"id": 7601
	},
	{
		"template": "line001",
		"data-id": 9465,
		"chart-id": 9465,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Neuerstellte Genossenschaftswohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil der Genossenschaftswohnungen betrug von 2013 bis 2021 durchschnittlich knapp 11%. Bei den in diesem Zeitraum neuerstellten Logis lag er mit 13% leicht höher. 2017 und 2021 waren überdurchschnittlich ergiebige Jahre für den genossenschaftlichen Wohnungsbau. Dageben waren die Anteile 2013 bis 2016 gering.",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche per 31.12. von mindestens einer Person belegt waren. Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neuerstellte Genossenschaftswohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09465",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "07",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-01-07T03:57:57",
		"id": 9465
	}
];